---
sidebar: sidebar
permalink: hu-aix-70.html
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap
summary: The AIX Host Utilities assists you to manage ONTAP storage attached to an AIX host.
---
= Install AIX Host Utilities 7.0 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/hu/aix-install-hu-introduction.adoc[] .

AIX Host Utilities 7.0 support the following transport protocols and AIX environments:

* FC, FCoE, and iSCSI
* AIX Microsoft Multipath I/O (MPIO) (Native OS)
* PowerVM 
+
For information about PowerVM, see the IBM PowerVM Live Partition Mobility Red Book.

.About this task
* You download the AIX Host Utilities from the NetApp Support site in a compressed `tar.gz` file.
* You need to install the AIX Host Utilities kit with AIX MPIO to manage ONTAP storage attached to an AIX host.

.Before you begin

* Use the https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that all components in your iSCSI, FC, or FCoE configuration are supported.
* Enable dynamic tracking for all FC and FCoE initiators.

.Steps

. Log in to your host.
+
[role="tabbed-block"]
====
.AIX
--
On an AIX host, log in as *root*.
--

.PowerVM
--
On a PowerVM host:

.. Log in as *padmin*.
.. Become a root user:
+
[source,cli]
----
oem_setup_env
----
--
====

. Go to the https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0[NetApp Support Site^] and download the compressed file containing the Host Utilities to a directory on your host.

. Go to the directory containing the download.

. Decompress the file and extract the SAN Toolkit software package:
+
[source,cli]
----
tar -xvf ntap_aix_host_utilities_7.0.tar.gz
----
+
The following directory is created when you decompress the file: `ntap_aix_host_utilities_7.0`. This directory contains one of the following subdirectories: MPIO, NON_MPIO, or SAN_Tool_Kit.

. Install the AIX MPIO:
+
[source,cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit
----

. Install the SAN Toolkit:
+
[source,cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit
----

. Reboot the host.

. Verify the installation:
+
[source,cli]
----
lslpp -l |grep -i netapp
----
+
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities	
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----

. Confirm the software version:
+
[source,cli]
----
sanlun version
----
+
----
7.0.725.3521
----

. Verify that the SCSI UNMAP `lbp_enabled` parameter is added to the ODM:
+
[source,cli]
----
odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"
----
+
----
attribute = "lbp_enabled"
----
+
[source,cli]
----
odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`
----
+
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----

include::_include/hu/aix-install-whats-next.adoc[]

// 2025 MAY 20, ONTAPDOC-2365 
// 2024 Sep 06, AIX 7.0