---
sidebar: sidebar
permalink: hu-centos-8x.html
keywords: host utilities, centos, linux, 8.5, 8.4, 8.3, 8.2, 8.1, 8.0 netapp, ontap
summary: Install Linux Host Utilities on a CentOS 8.x host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure CentOS 8.x for FCP and iSCSI for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a CentOS 8.x host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-enable-san-boot.adoc[]

== Step 2: Install the Linux Host Utilities

include::_include/hu/install-linux-host-utilities-80.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with CentOS 8.x to manage ONTAP LUNs.

include::_include/hu/linux-centos-multipathing.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-customize-parameters.adoc[]

== Step 6: Review the known issues

There are no known issues.

For CentOS Red Hat compatible kernel known issues, see the link:hu-rhel-8x.html#known-problems-and-limitations[known issues] for the Red Hat Enterprise Linux (RHEL) 8.x series.

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]

include::_include/hu/kvm-centos.adoc[]

// 2025 Dec 17, ONTAPDOC-3531
// 2025 JUN 30, ONTAPDOC-3068