---
sidebar: sidebar
permalink: hu-luhu-80.html
keywords: host utilities, unified, oracle, linux, 8.0, netapp, ontap
summary: Describes how to use the Linux Host Utilities 8.0 with ONTAP
---
= Install Linux Host Utilities 8.0 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/hu/install-linux-hu-introduction.adoc[]

Linux Host Utilities 8.0 supports the following distribution types:

*	Red Hat Enterprise Linux (RHEL)
*	SUSE Linux Enterprise Server
*	Oracle Linux
*	Ubuntu

NOTE: The Linux Host Utilities software doesn't support NVMe over Fibre Channel (NVMe/FC) and NVMe over TCP (NVMe/TCP) host protocols.

.About this task

When you install the Linux Host Utilities, it doesn't change any settings on your Linux host. 

.Before you begin
* For reliable operation, use the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that your iSCSI, FC, or FCoE configuration is supported.
* Install the host bus adapter (HBA) management packages available on the vendor support site. The management software enables the `sanlun` commands to gather information about the FC HBAs, such as their WWPNs. 
+
Refer to the vendor documentation to verify that the following packages are correctly installed. These packages are required to support the `sanlun fcp show adapter` command:
+
** Marvell QLogic HBA – QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand Manager core application CLI

.Steps

. If you have a version of Linux Host Utilities currently installed, remove it:
+
[role="tabbed-block"]
====
.RHEL and SUSE Linux Enterprise Server
--
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-x-x
----
--
.Ubuntu
--
[source, cli]
----
sudo apt remove netapp_linux_unified_host_utilities-x-x
----
--
====
+
For earlier versions of Linux Host Utilities, go to the directory where the host utility software is installed and enter the uninstall command to remove the installed package.

. The NetApp Linux Host Utilities software package is available on the NetApp Support Site in a 64-bit .rpm file. Download the 64-bit file from the link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/8.0/downloads[NetApp Support Site^] to your host.

. Go to the directory to which you downloaded the software package and install it:
+
[role="tabbed-block"]
=====
.RHEL and SUSE Linux Enterprise Server
--
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-8-0.x86_xx.rpm
----

You should see an output similar to the following example:

----
rpm -ivh netapp_linux_unified_host_utilities-8-0.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]

----
--

.Ubuntu
--
[source, cli]
----
sudo apt install /<path_to_file>/netapp_linux_unified_host_utilities-8-0.x86_xx.deb
----
[NOTE]
====
If you are using an Ubuntu host OS, you need to manually link it to the HBA library:

[source, cli]
----
cp /opt/QLogic_Corporation/QConvergeConsoleCLI/lib64/libHBAAPI.so.2.0.2 /usr/lib64/libHBAAPI.so
----
====
--
=====
. Verify the installation:
+
[source, cli]
----
sanlun version
----
+
You should see an output similar to the following example:
+
----
sanlun version 8.0.386.1644
----

include::_include/hu/linux-install-hu-whats-next.adoc[]

// 2025 SEP 18, ONTAPDOC-3352