---
sidebar: sidebar
permalink: hu-luhu-release-notes.html
keywords: host utilities, linux, 8.0, netapp, ontap, release, notes, linux
summary: Release Notes for Linux Host Utilities
---
= Linux Host Utilities Release Notes
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The release notes describe new features, enhancements, known issues, limitations, and important cautions for configuring and managing your specific host with your ONTAP storage system.

For specific information about the operating system versions and updates that the Host Utilities support, see the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^].

== What's New in Linux Host Utilities 8.0
The Linux Host Utilities 8.0 release contains the following new features and enhancements

Linux Host Utilities 8.0 includes support for 64-bit speed QLogic and Emulex FC host bus adapters (HBA). 

The following operating systems are supported:

* Red Hat Enterprise Linux (RHEL) 9 and 8 series
* SUSE Linux Enterprise Server 
* Oracle Linux 9 and 8 series
* Ubuntu

[NOTE]
NetApp continues to work with the Linux Host Utilities to add support for features after the initial release. For latest information about the features that are supported and the new features that have been added, see the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^].
 
== Known issues

There are no known issues for Linux Host Utilities 8.0.

link:https://mysupport.netapp.com/site/bugs-online/product[NetApp Bugs Online^] provides complete information for most known issues, including suggested workarounds where possible.

== What's next

link:hu-luhu-80.html[Learn about installing Linux Host Utilities]