---
sidebar: sidebar
permalink: hu-ol-8x.html
keywords: host utilities, oracle, linux, 8.10, 8.9, 8.8, 8.7, 8.6, 8.5, 8.4, 8.3, 8.2, 8.1, 8.0, netapp, ontap
summary: Describes how to use Oracle Linux 8.x with ONTAP
---
= Configure Oracle Linux 8.x for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on an Oracle Linux 8.x host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities-80.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Oracle Linux 8.x to manage ONTAP LUNs.

NOTE: You can use the link:hu-rhel-8x.html#rhel-rhck[recommended settings for Red Hat Enterprise Linux (RHEL) 8.x] to configure Red Hat Compatible Kernel for Oracle Linux 8.x.

include::_include/hu/linux-ol-multipathing-chk-config.adoc[]

== Step 4: Confirm the iSCSI configuration for your host

include::_include/hu/linux-iscsi-configuration.adoc[]

== Step 5: Optionally, exclude a device from multipathing

include::_include/hu/exclude-device.adoc[]

== Step 6: Customize multipath parameters for ONTAP LUNs

include::_include/hu/linux-customize-parameters.adoc[]

== Step 7: Review the known issues

There are no known issues.

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]