---
sidebar: sidebar
permalink: hu-ol-9x.html
keywords: host utilities, oracle, linux, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0 netapp, ontap
summary: Install the Linux Host Utilities on an Oracle Linux 9.x host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure Oracle Linux 9.x for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on an Oracle Linux 9.x host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/rhel-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities-80.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Oracle Linux 9.x to manage ONTAP LUNs.

include::_include/hu/linux-ol-multipathing.adoc[]

== Step 4: Confirm the iSCSI configuration for your host

To ensure that multipathing is configured correctly for your host, set the timeout parameter and confirm that the iSCSI service is running and connecting to the iSCSI targets.

.Before you begin
Verify that the iSCSI initiator package (iscsi-initiator-utils) is installed. 

.Steps
. Set iSCSI Initiator node name:
+
[source,cli]
----
Edit /etc/iscsi/initiatorname.iscsi.
Format: InitiatorName=iqn.YYYY-MM.com.vendor:<host_name>
Use lowercase, max 223 chars.
----

. Configure the iSCSI session timeout parameter:
+
[source,cli]
----
Edit /etc/iscsi/iscsid.conf:
node.session.timeo.replacement_timeout = 5
----
+
The iSCSI `replacement_timeout` parameter controls how long the iSCSI layer should wait for a timed-out path or session to reestablish itself before failing any commands on it. NetApp recommends setting the value of `replacement_timeout` to 5 in the iSCSI configuration file for Oracle Linux 9.x.

. Enable the iSCSI service:
+
[source,cli]
----
$systemctl enable iscsid
----

. Start the iSCSI service:
+
[source,cli]
----
$systemctl start iscsid
----

. Verify that the iSCSI service is running:
+
[source,cli]
----
$systemctl status iscsid
----
+
.Show example
[%collapsible]
====
----
● iscsid.service - Open-iSCSI
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; preset: disabled)
     Active: active (running) since Tue 2025-12-02 11:36:21 EST; 2 weeks 1 day ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
             man:iscsiuio(8)
             man:iscsiadm(8)
   Main PID: 2263 (iscsid)
     Status: "Ready to process requests"
      Tasks: 1 (limit: 816061)
     Memory: 18.5M
        CPU: 14.480s
     CGroup: /system.slice/iscsid.service
             └─2263 /usr/sbin/iscsid -f -d2
----
====

. Discover the iSCSI targets:
+
[source,cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.show example
[%collapsible]
====
----
iscsiadm --mode discovery --op update --type sendtargets --portal  192.168.30.87
192.168.30.87:3260,1139 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.31.97:3260,1142 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.31.87:3260,1141 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.30.97:3260,1140 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
----
====

. Log in to the targets:
+
[source,cli]
----
$iscsiadm --mode node -l all
----

. Set the automatic iSCSI login upon host boot:
+
[source,cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
You should an ouptput similar to the following example:
+
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 -p 192.168.30.87:3260 -o update -n node.startup -v automatic
----
. Verify the iSCSI sessions:
+
[source,cli]
----
$iscsiadm --mode session
----
+
.Show example
[%collapsible]
====
----
iscsiadm --mode session
tcp: [1] 192.168.30.87:3260,1139 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [2] 192.168.31.97:3260,1142 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [3] 192.168.31.87:3260,1141 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [4] 192.168.30.97:3260,1140 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
----
====

== Step 5: Optionally, exclude a device from multipathing

If required, you can exclude a device from multipathing by adding the WWID for the unwanted device to the "blacklist" stanza for the `multipath.conf` file.

.Steps

. Determine the WWID:
+
[source,cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" is the local SCSI disk that you want to add to the blacklist.
+
An example WWID is `360030057024d0730239134810c0cb833`.

. Add the WWID to the "blacklist" stanza:
+
[source,cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----

== Step 6: Customize multipath parameters for ONTAP LUNs

If your host is connected to LUNs from other vendors and any of the multipath parameter settings are overridden, you need to correct them by adding stanzas later in the `multipath.conf` file that apply specifically to ONTAP LUNs. If you don't do this, the ONTAP LUNs might not work as expected. 

Check your `/etc/multipath.conf` file, especially in the defaults section, for settings that might be overriding the <<multipath-parameter-settings,default settings for multipath parameters>>. 

CAUTION: You shouldn't override the recommended parameter settings for ONTAP LUNs. These settings are required for optimal performance of your host configuration. Contact NetApp support, your OS vendor, or both for more information.

The following example shows how to correct an overridden default. In this example, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that aren't compatible with ONTAP LUNs, and you can't remove these parameters because ONTAP storage arrays are still attached to the host. Instead, you correct the values for `path_checker` and `no_path_retry` by adding a device stanza to the `multipath.conf` file that applies specifically to the ONTAP LUNs.

.Show example
[%collapsible]
====
[subs=+quotes]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====

== Step 7: Review the known issues

Oracle Linux 9.3, 9.2, 9.1, and 9.0 with ONTAP storage has the following known issue:

[cols="20,40,40",options="header"]
|===
|NetApp Bug ID	|Title	|Description
|https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1508554[1508554^]	|SAN LUN utility with Emulex HBA needs symbolic links from library packages	|When you execute the Linux Host Utilities CLI command - "sanlun fcp show adapter -v" on a SAN host, the command fails with an error message displaying that the library dependencies required for an host bus adapter (HBA) discovery cannot be located:
----
[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded
----
|===

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]