---
sidebar: sidebar
permalink: hu-solaris-80-cmd.html
keywords: host utilities, unified, solaris, 8.0, netapp, ontap
summary: Describes how to use the Solaris Host Utilities 8.0 with ONTAP
---
= Use the Solaris Host Utilities 8.0 command reference with ONTAP storage 
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the Solaris Host Utilities 8.0 sample command reference for an end-to-end validation of the NetApp storage configuration using the Host Utilities tool.

== List all host initiators mapped to host
You can retrieve a list of all host initiators mapped to a host.

[source,cli]
----
sanlun fcp show adapter -v
----
.Show example
[%collapsible]
====
----
adapter name:      qlc0
WWPN:              2100f4e9d40fe3e0
WWNN:              2000f4e9d40fe3e0
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c4
 
adapter name:      qlc1
WWPN:              2100f4e9d40fe3e1
WWNN:              2000f4e9d40fe3e1
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c5
----
====


== List all LUNs mapped to host
You can retrieve a list of all LUNs mapped to a host.

[source,cli]
----
sanlun lun show -p -v all
----
.Show example
[%collapsible]
====
----

ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 21g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native

----
====

== List all LUNs mapped to host from a given SVM/ List all attributes of a given LUN mapped to host

You can retrieve a list of all LUNs mapped to a host from a specific SVM.

[source,cli]
----
sanlun lun show -p -v <svm_name>
----
.Show example
[%collapsible]
====
----
ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 20g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native
----
====

== List ONTAP LUN attributes by host device filename
You can retrieve a list of all ONTAP LUN attributes by specifying a host device filename.

[source,cli]
----
sanlun lun show all
----
.Show example
[%collapsible]
====
[source,curl]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                /vol/test1/lun1                         /dev/rdsk/
c0t600A098038314B314E5D574632365A51d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc1            FCP      20g        cDOT
----
====






