---
sidebar: sidebar
permalink: hu-sles-16spx.html
keywords: host utilities, suse linux enterprise server 16,netapp, ontap, fcp, iscsi
summary: Install the Linux Host Utilities on a SUSE Linux Enterprise Server 16 to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure SUSE Linux Enterprise Server 16 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a SUSE Linux Enterprise Server 16 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with SUSE Linux Enterprise Server 16 to manage ONTAP LUNs.

include::_include/hu/multipathing.adoc[]

== Step 4: Confirm the iSCSI configuration for your host

include::_include/hu/linux-iscsi-configuration-sles.adoc[]

== Step 5: Optionally, exclude a device from multipathing

include::_include/hu/exclude-device.adoc[]

== Step 6: Customize multipath parameters for ONTAP LUNs

include::_include/hu/linux-customize-parameters.adoc[]

== Step 7: Review the known issues

There are no known issues.

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]

include::_include/hu/kvm-sles.adoc[]

// 2026 JAN 28, ONTAPDOC-3486
// 2025 Dec 17, ONTAPDOC-3531