---
sidebar: sidebar
permalink: hu-solaris-san-toolkit.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Solaris Host Utilities 8.0 with ONTAP
---
= Learn about the Solaris SAN Toolkit
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Solaris Host Utilities is a NetApp host software that provides a command line toolkit on your Oracle Solaris host. The toolkit is installed when you install the NetApp Host Utilities package. This kit provides the `sanlun` utility which helps you manage LUNs and host bus adapters (HBAs). The `sanlun` command returns information about the LUNs mapped to your host, multipathing, and information necessary to create initiator groups. The following example output shows the ONTAP LUN information returned for the `sanlun lun show` command:

.Show example output
[%collapsible]
====
----
#sanlun lun show all
controller(7mode)/ device host lun
vserver(Cmode)                     lun-pathname       filename                                       adapter protocol size mode
-----------------------------------------------------------------------------------------------------------------------------------
data_vserver                     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3   FCP       10g cDOT
data_vserver                     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3   FCP       10g cDOT

----
====

[NOTE]
This toolkit is common across all Host Utilities configurations and protocols. As a result, all of the components don't apply to every configuration. Unused components don't affect your system performance.

include::_include/hu/solaris-command-reference-whats-next.adoc[]