---
sidebar: sidebar
permalink: hu-wuhu-80.html
keywords: windows, 7.2, host utilities, SAN, windows
summary: Windows Host Utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for ONTAP and E-Series platforms.
---
= Install Windows Host Utilities 8.0 for ONTAP storage
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
The Windows Host Utilities enable you to connect a Windows host computer to NetApp storage systems.

[[supported-windows-versions-80]]
The Windows Host Utilities support the following versions of Windows:

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016

include::_include/windows/windows-install-chunk-a.adoc[]
|===
|Program |Purpose

| `\NetAppQCLI\fcconfig.exe`
|Used by the installation program to set the HBA parameters.
| `\NetAppQCLI\fcconfig.ini`
|Used by the installation program to set the HBA parameters.
|`san_version.exe`
|Displays the version of the Host Utilities and FC HBAs.
|===

The Host Utilities support different Windows host configurations, protocols, and multipathing options. For more information, see the https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].


== Step 1: Verify your host and storage system configuration

Verify that your host and storage system configuration are supported before you install Windows Host Utilities for the <<supported-windows-versions-80,supported Windows version>>.

.Steps

. Check the supported configuration in the http://mysupport.netapp.com/matrix[Interoperability Matrix Tool^].
. Check the hotfixes required for the respective host in the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[SAN host Windows documentation].
+
[NOTE]
The link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html[Use Windows server 2022 with ONTAP] document provides instructions on link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes[installing Windows hotfixes] for Windows server 2022. Refer to the  Windows documents in the host configurations category to find the relevant hotfix information for earlier versions of Windows server.

. Add the iSCSI, FCP, or NVMe-oF license and start the target service.

. Verify your cabling.
+
See the https://docs.netapp.com/us-en/ontap/san-config/index.html[SAN configuration reference^] documentation or https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html[E-Series hardware cabling^] for detailed cabling and configuration information.

== Step 2: Configure FC HBAs and switches

Install and configure one or more supported FC host bus adapters (HBAs) for FC connections to the storage system.

The Windows Host Utilities installer sets the required FC HBA settings.

[CAUTION]
Don't change the HBA settings manually.

.Steps

. Install one or more supported FC HBAs according to the instructions provided by the HBA vendor.
. Obtain the supported HBA drivers and management utilities and install them according to the instructions provided by the HBA vendor.
. Connect the HBAs to your FC switches or directly to the storage system.
. Create zones on the FC switch according to your FC switch documentation.
. For ONTAP, zone the switch by the WWPN. Be sure to use the WWPN of the logical interfaces (LIFs) and not the WWPN of the physical ports on the storage controllers. See the https://docs.netapp.com/us-en/ontap/san-config/index.html[SAN configuration reference^] documentation for more information.

include::_include/windows/windows-install-host-utilities.adoc[]

[role="tabbed-block"]
====

.Install interactively
--

Install the Windows Host Utilities software package interactively by running the installation program and following the prompts.

. Download the executable file from the https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads[NetApp Support Site^].
. Change to the directory where you downloaded the executable file.
. Run the `netapp_windows_host_utilities_7.2_x64` file and follow the instructions on the screen.
. Reboot the Windows host when prompted.
--

.Install from a command line
--

Perform a quiet (unattended) installation of the Windows Host Utilities by entering the appropriate commands at the Windows command prompt. The system automatically reboots when the installation is complete.


. Enter the following command at the Windows command prompt:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

* `installer` is the name of the `.msi` file for your CPU architecture.
* MULTIPATHING specifies whether MPIO support is installed. The allowed values are "0" for no and "1" for yes.
* `inst_path` is the path where the Host Utilities files are installed. The default path is `C:\Program Files\NetApp\Windows Host Utilities\`.

[NOTE]
To see the standard Microsoft Installer (MSI) options for logging and other functions, enter `msiexec /help` at the Windows command prompt. For example, the `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` command displays logging information.

--
====

include::_include/windows/windows-install-whats-next.adoc[]

// 2025 ARR 28, ontap-sanhost-issue-218