---
sidebar: sidebar
permalink: hu_aix_72.html
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap
summary: Describes how to use IBM AIX 7.2 and/or PowerVM VIOS 3.1 with with ONTAP
---

= Use IBM AIX 7.2 and/or PowerVM (VIOS 3.1) with ONTAP
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure IBM AIX 7.2 and/or PowerVM (VIOS 3.1) with ONTAP as the target.

== Install the AIX/VIOS host utilities

You must install the AIX Host Utilities Kit while using AIX MPIO with NetApp ONTAP storage.

You can download the compressed file containing the Host Utilities software packages from the link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads[NetApp Support Site^]. After you have the file, you must decompress it to get the two software packages you need to install the host utilities.

NetApp AIX Host Utilities 6.1 is the latest release. This release addresses the memory leak issue that was reported in the previous releases. Refer to release notes section for additional information.

.Steps

. Login to your host.
+
* On an AIX host, log in as *root*.
+
* On a PowerVM host, log in as *padmin*, and then enter the `oem_setup_env` command to become root.

.	Download a copy of the compressed file containing the Host Utilities from NetApp Support Site to a directory on your host.

.	 Go to the directory containing the download.

. Uncompress the file and extract the SAN Toolkit software package.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
The following directory is created when you decompress the file: `ntap_aix_host_utilities_6.1`.  This directory will have one of the following subdirectories:  MPIO, NON_MPIO, or SAN_Tool_Kit.

.	Install the AIX MPIO:
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Install the SAN Toolkit:
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Reboot the host.

== SAN toolkit

include::_include/hu/reuse_hu_san_toolkit_withoutexample.adoc[]

.Example

In the following example, the `sanlun lun show` command returns LUN information.

----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----

== SAN booting

.Before you begin

If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

SAN booting is the process of setting up a SAN-attached disk (a LUN) as a boot device for an AIX/PowerVM host.  You can set up a SAN boot LUN to work in an AIX MPIO environment that is running the AIX Host Utilities with either the FC or FCoE protocol. The method you use for creating a SAN boot LUN and installing a new OS image on it in an AIX MPIO environment can vary, depending on which protocol you are using.

== Multipathing

Multipathing allows you to configure multiple network paths between the host and storage system. If one path fails, traffic continues on the remaining paths. The AIX and PowerVM environments of the Host Utilities use AIX’s native multipathing solution (MPIO).

For AIX, Path Control Module (PCM) is responsible for controlling multiple paths. PCM is a storage vendor supplied code that handles path management. This gets installed and enabled as part of the Host Utilities installation.

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----

include::_include/hu/reuse_hu_asa_configuration.adoc[]

NOTE: All SAN Arrays (ASA) configurations are supported beginning in ONTAP 9.8 for AIX Hosts.

----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----

== Recommended Settings

Following are some recommended parameter settings for ONTAP LUNs.  The critical parameters for ONTAP LUNs are set automatically after installing the NetApp Host Utilities Kit.

[cols=4*, options="header"]
|===
| Parameter
| Environment
| Value for AIX
| Note
| algorithm | MPIO | round_robin | Set by Host Utilities
| hcheck_cmd | MPIO | inquiry | Set by Host Utilities
| hcheck_interval | MPIO | 30 | Set by Host Utilities
| hcheck_mode | MPIO | nonactive | Set by Host Utilities
| lun_reset_spt | MPIO / non-MPIO | yes | Set by Host Utilities
| max_transfer | MPIO / non-MPIO | FC LUNs: 0x100000 bytes | Set by Host Utilities
| qfull_dly | MPIO / non-MPIO | 2-second delay | Set by Host Utilities
| queue_depth | MPIO / non-MPIO | 64 | Set by Host Utilities
| reserve_policy | MPIO / non-MPIO | no_reserve | Set by Host Utilities
| rw_timeout (disk) | MPIO / non-MPIO | 30 seconds | Uses OS Default values
| dyntrk | MPIO / non-MPIO | Yes | Uses OS Default values
| fc_err_recov | MPIO / non-MPIO | Fast_fail | Uses OS Default values
| q_type | MPIO / non-MPIO | simple | Uses OS Default values
| num_cmd_elems | MPIO / non-MPIO | 1024 for AIX
3072 for VIOS | FC EN1B, FC EN1C
| num_cmd_elems | MPIO / non-MPIO | 1024 for AIX | FC EN0G
|===

//GitHub issue #114

== Recommended settings for MetroCluster

By default, the AIX operating system enforces a shorter I/O timeout when no paths to a LUN are available. This might occur in configurations including single-switch SAN fabric and MetroCluster configurations that experience unplanned failovers. For additional information and recommended changes to default settings, refer to link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318[NetApp KB1001318^]

== AIX support with SnapMirror active sync

Beginning with ONTAP 9.11.1, AIX is supported with SnapMirror active sync. With an AIX configuration, the primary cluster is the "active" cluster.

In an AIX configuration, failovers are disruptive. With each failover, you will need to perform a re-scan on the host for I/O operations to resume.

To configure AIX for SnapMirror active sync, refer to the Knowledge Base article link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)[How to configure an AIX host for SnapMirror active sync^].

== Known issues

The IBM AIX 7.2 and/or PowerVM (VIOS 3.1) with ONTAP release has the following known issues:

[cols=4*,options="header"]
|===
| NetApp Bug ID
| Title
| Description
| Partner ID

| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1416221[1416221^] | AIX 7200-05-01 encountered I/O disruption on virtual iSCSI disks(VIOS 3.1.1.x) during storage failover | I/O disruption can happen during storage failover operations on AIX 7.2 TL5 hosts on the virtual iSCSI disks mapped through the VIOS 3.1.1.x. By default, the `rw_timeout` value of the virtual iSCSI disks (hdisk) on VIOC will be 45 seconds. If an I/O delay greater than 45 seconds happens during storage failover, an I/O failure might occur. To avoid this situation, refer to the workaround mentioned in the BURT. As per IBM, after applying APAR - IJ34739 (upcoming release) we can dynamically change the rw_timeout value using the `chdev` command. | NA


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1414700[1414700^] | AIX 7.2 TL04 encountered I/O disruption on virtual iSCSI disks(VIOS 3.1.1.x) during storage failover | I/O disruption can happen during storage failover operations on AIX 7.2 TL4 hosts on the virtual iSCSI disks mapped through the VIOS 3.1.1.x. By default, the `rw_timeout` value of vSCSI adapter on VIOC is 45 seconds. If an I/O delay of  more than 45 seconds happens during a storage failover, I/O failure might  occur. To avoid this situation, refer to the workaround mentioned in the BURT. | NA

| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1307653[1307653^] | Seeing I/O issues on VIOS 3.1.1.10 during SFO faults and straight I/O | On VIOS 3.1.1 IO failures may be seen on NPIV client disk which are backed by 16/32Gb FC adapters.  Also, a `vfchost` driver may get into a state where it stops processing I/O requests from the client. Applying IBM APAR IJ22290 IBM APAR IJ23222 will fix the issue. | NA

|===

// BURT 1483343, 2022-16-06
