---
sidebar: sidebar
permalink: hu_aix_72_sanbooting_powervm_vscsi.html
keywords: host utilities, aix, powervm, 7.2 netapp, ontap, luns, configure, discover, configuring, discovering
summary: Describes how to use discover and configure LUNs with PowerVM vSCSI
---

= (PowerVM vSCSI) Discovering and configuring LUNs
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you are using PowerVM vSCSI and VIO servers, you must use the padmin login and the commands appropriate for it to configure and discover LUNs.

.Steps

. Log in to the host as padmin.

. On the AIX host, enter the following command to discover the newly created LUNs:
+
`cfgdev`
+
The cfgdev command causes:
+
* The initiators to log into the fabric.
+
* The system to check for new devices.
+
* The system to create new device entries where the new LUNs are mapped as MPIO devices using the default PCM.

. To verify that the hdisk MPIO devices were created, enter the following command:
+
`lsdev -type disk`
+
The LUNs appear on the host as disks. You can use these disks the same way you use local disks on the host.
+
Write down the hdisk instance numbers. You use them when you perform the path configuration.
+
The `lsdev -type disk` command produces the following type of output.  The output in this example has been truncated.
+
----
vioserver$ lsdev -type disk NetApp
name     status      description
hdisk0   Available   16 Bit LVD SCSI Disk Drive
hdisk1   Available   16 Bit LVD SCSI Disk Drive
hdisk2   Available   MPIO NetApp FCP Default PCM Disk
hdisk3   Available   MPIO NetApp FCP Default PCM Disk
hdisk4   Available   MPIO NetApp FCP Default PCM Disk
hdisk5   Available   MPIO NetApp FCP Default PCM Disk
hdisk6   Available   MPIO NetApp FCP Default PCM Disk
----

. To get information about you setup, enter the following command:
+
`lsdev -dev hdisk_name -attr`
+
The `lsdev -dev hdisk_name -attr` command produces the following output:
+
----
vioserver$ lsdev -dev hdisk2 -attr
attribute value                   description                user-settable
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistent Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----

. If your configuration does not support ALUA, you must execute the dotpaths utility to set the path priorities. The dotpaths utility is installed when you install the Host Utilities. Do not use the dotpaths utility if ALUA is enabled. Switch to the `oem_setup_env` mode to execute the dotpaths by entering the following command:
+
`oem_setup_env`
+
When you enter the `oem_setup_env` mode, the command line prompt changes from a dollar sign to a pound sign and you remain in `oem_setup_env` mode until you halt it by entering a command such as exit.
+
.Example
+
``# vioserver$ oem_setup_env`

. If your configuration supports ALUA, you can use it to set path priority.  Verify that ALUA is enabled:
+
`lun igroup show -instance igroup_name`

.. If ALUA is not enabled, enable it:
+
`igroup set igroup_name alua yes`
+
. If your configuration does not support ALUA, you must execute the dotpaths utility to set the path priorities. The dotpaths utility is installed when you install the Host Utilities. Do not use the dotpaths utility if ALUA is enabled.

.. To set the priority for all Data ONTAP LUNs enter:
+
`dotpaths`

.. To set priority for a specific set of disk enter:
+
`dotpaths [-hqv] [hdiskN ...]`
+
Use the `-v` option to enable verbose mode and display all the priorities.  Use the `-q` option to query all or individual disk priorities.
+
The following is an example of using the dotpaths utility:
+
----
vioserver# dotpaths -v
hdisk2 (path 0): Optimized path - Setting priority to 255
hdisk2 (path 1): Optimized path - Setting priority to 255
hdisk2 (path 2): Unoptimized path - Current priority of 1 is correct
hdisk2 (path 3): Unoptimized path - Current priority of 1 is correct
...
Path priority set and/or verified for 22 disks, 86 total paths.
vioserver#
----

. To verify that the host has discovered the LUNs, enter the following command:
+
`# sanlun lun show -p`
+
.Example
+
This example shows typical output of the `sanlun lun show -p` command for a direct-attached configuration. It also includes the `sanlun lun show -d hdisk9 -v` command to display information about hdisk9. The output from this command has been truncated.
+
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ------------- ----------
host      controller  AIX            controller    AIX MPIO
path      path        MPIO   host    target        path
state     type        path   adapter port          priority
--------- ----------- ------ ------- ------------- ----------
up        secondary   path0  fcs0    3b              1
up        primary     path1  fcs0    3a              1
up        secondary   path2  fcs0    3a              1
up        primary     path3  fcs0    3b              1
up        secondary   path4  fcs0    4b              1
up        secondary   path5  fcs0    4a              1
up        primary     path6  fcs0    4b              1
up        primary     path7  fcs0    4a              1
up        secondary   path8  fcs1    3b              1
up        primary     path9  fcs1    3a              1
up        secondary   path10 fcs1    3a              1
up        primary     path11 fcs1    3b              1
up        secondary   path12 fcs1    4b              1
up        secondary   path13 fcs1    4a              1
up        primary     path14 fcs1    4b              1
up        primary     path15 fcs1    4a              1
----
+
----
sanlun lun show -vd hdisk10
                                                                      device          host                  lun
vserver              lun-pathname                                     filename        adapter    protocol   size    mode
------------------------------------------------------------------------------------------------------------------------
GPFS_p520_FC         /vol/GPFS_p520_FC_FlexVol_2/GPFS_p520_FC_LUN_2_4 hdisk10         fcs3       FCP        100g    C
             LUN Serial number: 1k/yM$-ia5HC
         Controller Model Name: N5600
          Vserver FCP nodename: 200200a0980c892f
          Vserver FCP portname: 200a00a0980c892f
              Vserver LIF name: GPFS_p520_FC_2
            Vserver IP address: 10.225.121.100
           Vserver volume name: GPFS_p520_FC_FlexVol_2  MSID::0x00000000000000000000000080000420
         Vserver snapshot name:
----
