---
sidebar: sidebar
permalink: hu_aix_72.html
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap
summary: Describes how to use IBM AIX 7.2 and/or PowerVM VIOS 3.1 with with ONTAP
---

= Using IBM AIX 7.2 and/or PowerVM (VIOS 3.1) with NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


== Installing the AIX/VIOS Host Utilities

You must install the AIX Host Utilities Kit while using AIX MPIO with NetApp ONTAP Storage.

You can download the compressed file containing the Host Utilities software packages from the NetApp Support Site. After you have the file, you must decompress it to get the two software packages you need to install the Host Utilities.

NetApp AIX Host Utilities 6.1 is the latest release. This release addresses the memory leak issue that was reported in the previous releases. Refer to release notes section for additional information.

.Steps

. Login to your host.
+
* On an AIX host, log in as *root*.
+
* On a PowerVM host, log in as *padmin*, and then enter the `oem_setup_env` command to become root.

.	Download a copy of the compressed file containing the Host Utilities from NetApp Support Site to a directory on your host.

.	 Go to the directory containing the download.

. Uncompress the file and extract the SAN Toolkit software package.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
The following directory is created when you decompress the file: `ntap_aix_host_utilities_6.1`.  This directory will have one of the following subdirectories:  MPIO, NON_MPIO, or SAN_Tool_Kit.

.	Install the AIX MPIO:
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Install the SAN Toolkit:
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Reboot the host.

== SAN Toolkit

include::_include/hu/reuse_hu_san_toolkit_withoutexample.adoc[]

.Example

In the following example, the `sanlun lun show` command returns LUN information.

----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----

== SAN Booting

.What you'll need
If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

SAN booting is the process of setting up a SAN-attached disk (a LUN) as a boot device for an AIX/PowerVM host.  You can set up a SAN boot LUN to work in an AIX MPIO environment that is running the AIX Host Utilities with either the FC or FCoE protocol. The method you use for creating a SAN boot LUN and installing a new OS image on it in an AIX MPIO environment can vary, depending on which protocol you are using.

== Multipathing

Multipathing allows you to configure multiple network paths between the host and storage system. If one path fails, traffic continues on the remaining paths. The AIX and PowerVM environments of the Host Utilities use AIX’s native multipathing solution (MPIO).

For AIX, Path Control Module (PCM) is responsible for controlling multiple paths. PCM is a storage vendor supplied code that handles path management. This gets installed and enabled as part of the Host Utilities installation.

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----

include::_include/hu/reuse_hu_asa_configuration.adoc[]

NOTE: All SAN Arrays (ASA) configurations are supported beginning in ONTAP 9.8 for AIX Hosts.

----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----

== Recommended Settings

Following are some recommended parameter settings for NetApp ONTAP LUN’s.  The critical parameters for ONTAP LUN’s are set automatically after installing the NetApp Host Utilities Kit.

[cols=4*, options="header"]
|===
| Parameter
| Environment
| Value for AIX
| Note
| algorithm | MPIO | round_robin | Set by Host Utilities
| hcheck_cmd | MPIO | inquiry | Set by Host Utilities
| hcheck_interval | MPIO | 30 | Set by Host Utilities
| hcheck_mode | MPIO | nonactive | Set by Host Utilities
| lun_reset_spt | MPIO / non-MPIO | yes | Set by Host Utilities
| max_transfer | MPIO / non-MPIO | FC LUNs: 0x100000 bytes | Set by Host Utilities
| qfull_dly | MPIO / non-MPIO | 2-second delay | Set by Host Utilities
| queue_depth | MPIO / non-MPIO | 64 | Set by Host Utilities
| reserve_policy | MPIO / non-MPIO | no_reserve | Set by Host Utilities
| re_timeout (disk) | MPIO / non-MPIO | 30 seconds | Uses OS Default values
| dyntrk | MPIO / non-MPIO | Yes | Uses OS Default values
| fc_err_recov | MPIO / non-MPIO | Fast_fail | Uses OS Default values
| q_type | MPIO / non-MPIO | simple | Uses OS Default values
| num_cmd_elems | MPIO / non-MPIO | 1024 for AIX
3072 for VIOS | FC EN1B, FC EN1C
| num_cmd_elems | MPIO / non-MPIO | 1024 for AIX | FC EN0G
|===

== Recommended Settings for MetroCluster

By default, the AIX operating system enforces a shorter I/O timeout if when no paths to a LUN are available. This might occur in configurations including single-switch SAN fabric and MetroCluster configurations that experience unplanned failovers. For additional information and recommended changes to default settings, please refer to link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318[NetApp KB1001318^]

== Required settings to support AIX with SMBC

Beginning in ONTAP 9.11.1, AIX is supported with SnapMirror Business Continuity (SMBC). The following settings are required in ONTAP and the AIX storage stack to support AIX with SMBC.

=== ONTAP Settings

If a storage failover (SFO) event occurs on both clusters around the same time (concurrent SFO), I/O is expected to fail because the primary path of the LUN might return `LU NOT SUPPORTED`. To avoid I/O failure, you must set the following bootarg on all 4 nodes of both clusters:

`bootarg.scsit.zrto_consensus_debounce_time_limit to 600s`

.Steps

. Use the following command to set the bootarg. The command must be run on all four nodes in the source and destination clusters :
+
`system node run -node _node name_ -command "bootargs set bootarg.scsit.zrto_consensus_debounce_time_limit 60000000”`

. Verify the bootarg is set correctly:
+
`system node run -node _node name_ -command "bootargs get bootarg.scsit.zrto_consensus_debounce_time_limit”`

. Use one of the following options to activate the bootarg:
+
.. Log in to the clustershell of the cluster by using the diagnostic login and run the following command:
+
`sudo sysctl sysvar.scsit.bootargs.rescan=true`
+
.. Alternatively, you can perform a storage failover on both of the clusters to activate the bootarg.
+
For example  if "cluster 1" consists of Node 1, Node 2, Node 3 and Node 4, the following steps must be performed sequentially:
+
... Storage failover takeover of Node 1 by Node 2.
... Storage failover giveback of Node 1 by Node 2.
... Storage failover takeover of Node 2 by Node 1.
... Storage failover giveback of Node 2 by Node 1.
+
The above example shows the steps for Node 1 and Node 2 on "cluster 1". This must be followed by:
+
... Storage failover takeover of Node 3 by Node 4.
... Storage failover giveback of Node 3 by Node 4.
... Storage failover takeover of Node 4 by Node 3.
... Storage failover giveback of Node 4 by Node 3.

=== AIX host behavior

Beginning in ONTAP 9.11.1, AIX hosts configured with SMBC LUNs only discover paths from the primary cluster after the LUN map. The LUN paths from the secondary cluster will return a `LU_NOT_SUPPORTED SCSI` response during LUN discovery. This means that the secondary cluster LUN paths will not be visible to the host. This target side response also results in the following behavioral changes on the host:

. A planned failover (PFO) or automatic unplanned failover (AUFO) event results in the loss of all LUN paths and application I/O failure. You must perform a manual AIX host rescan to discover the paths from the new primary cluster.

. During concurrent storage failover operations (SFO) on both the primary and secondary clusters, applications might experience I/O outage. To resolve this, a manual host rescan might be required.

The following example displays the LUN path status on AIX host during steady state. Only the primary cluster paths are displayed:

*Example*

----
#lsmpio -l hdiskx

[root@aix_server /]: lsmpio -l hdisk3
name    path_id  status   path_status  parent  connection

hdisk3  4        Enabled  Sel,Opt      fscsi6  2023d039ea1ee6a8,1000000000000
hdisk3  5        Enabled  Sel,Opt      fscsi6  2025d039ea1ee6a8,1000000000000
hdisk3  6        Enabled  Sel,Opt      fscsi7  2024d039ea1ee6a8,1000000000000
hdisk3  7        Enabled  Sel,Opt      fscsi7  2026d039ea1ee6a8,1000000000000
----

=== AIX host remediation after a PFO or AUFO event

.About this task

The AIX storage stack does not perform an automatic rescan of the LUNS after the LUN state changes from `LU_NOT_SUPPORTED` to `SCSI_GOOD`.  After a PFO or AUFO event, you must perform the following AIX host remediation steps to discover the LUN paths from the new primary cluster.

.Steps

. Perform a rescan for new ONTAP devices:
`#cfgmgr`

. Check the multipathing status on each ONTAP device:
+
In the following example, `hdisk3 0` to `hdisk3 3` shows the old primary cluster paths in a failed state.`hdisk3 4` to `hdisk3 7` shows the new primary cluster paths.
+
*Example*
+
----
#lsmpio -l hdiskx

[root@aix_server /]: lsmpio -l hdisk3
name    path_id  status   path_status  parent  connection

hdisk3  0        Failed   Opt,Fai      fscsi6  2005d039ea1e44e4,1000000000000
hdisk3  1        Failed   Opt,Fai      fscsi6  2003d039ea1e44e4,1000000000000
hdisk3  2        Failed   Opt,Fai      fscsi7  2006d039ea1e44e4,1000000000000
hdisk3  3        Failed   Opt,Fai      fscsi7  2004d039ea1e44e4,1000000000000
hdisk3  4        Enabled  Sel,Opt      fscsi6  2023d039ea1ee6a8,1000000000000
hdisk3  5        Enabled  Sel,Opt      fscsi6  2025d039ea1ee6a8,1000000000000
hdisk3  6        Enabled  Sel,Opt      fscsi7  2024d039ea1ee6a8,1000000000000
hdisk3  7        Enabled  Sel,Opt      fscsi7  2026d039ea1ee6a8,1000000000000
----

. Remove the failed paths from the old primary cluster for all devices:
+
*Example*
+
----
#rmpath [-l _name_] [-p _parentname_] [-w _connectionlocation_] [-i_ pathID_] [-d] [-g]

[root@aix_server /]: rmpath -l hdisk3  -p fscsi6 -w 2005d039ea1e44e4,1000000000000 -i 0  -d
path Deleted
[root@aix_server /]: rmpath -l hdisk3  -p fscsi6 -w 2003d039ea1e44e4,1000000000000 -i 1  -d
path Deleted
[root@aix_server /]: rmpath -l hdisk3  -p fscsi7 -w 2006d039ea1e44e4,1000000000000 -i 2  -d
path Deleted
[root@aix_server /]: rmpath -l hdisk3  -p fscsi7 -w 2004d039ea1e44e4,1000000000000 -i 3  -d
path Deleted
----

. Verify the path status:
+
*Example*
+
----
[root@aix_server /]: lsmpio -l hdisk3
name    path_id  status   path_status  parent  connection

hdisk3  4        Enabled  Sel,Opt      fscsi6  2023d039ea1ee6a8,1000000000000
hdisk3  5        Enabled  Sel,Opt      fscsi6  2025d039ea1ee6a8,1000000000000
hdisk3  6        Enabled  Sel,Opt      fscsi7  2024d039ea1ee6a8,1000000000000
hdisk3  7        Enabled  Sel,Opt      fscsi7  2026d039ea1ee6a8,1000000000000
[root@aix_server /]:
----

== Known Problems and Limitations

[cols=4*,options="header"]
|===
| NetApp Bug ID
| Title
| Description
| Partner ID

| 1416221 | AIX 7200-05-01 encountered I/O disruption on virtual iSCSI disks(VIOS 3.1.1.x) during storage failover | I/O disruption can happen during storage failover operations on AIX 7.2 TL5 hosts on the virtual iSCSI disks mapped through the VIOS 3.1.1.x. By default, the `rw_timeout` value of the virtual iSCSI disks (hdisk) on VIOC will be 45 seconds. If an I/O delay greater than 45 seconds happens during storage failover, an I/O failure might occur. To avoid this situation, refer to the workaround mentioned in the BURT. As per IBM, after applying APAR - IJ34739 (upcoming release) we can dynamically change the rw_timeout value using the `chdev` command. | NA


| 1414700 | AIX 7.2 TL04 encountered I/O disruption on virtual iSCSI disks(VIOS 3.1.1.x) during storage failover | I/O disruption can happen during storage failover operations on AIX 7.2 TL4 hosts on the virtual iSCSI disks mapped through the VIOS 3.1.1.x. By default, the `rw_timeout` value of vSCSI adapter on VIOC is 45 seconds. If an I/O delay of  more than 45 seconds happens during a storage failover, I/O failure might  occur. To avoid this situation, refer to the workaround mentioned in the BURT. | NA

| 1307653 | Seeing I/O issues on VIOS 3.1.1.10 during SFO faults and straight I/O | On VIOS 3.1.1 IO failures may be seen on NPIV client disk which are backed by 16/32Gb FC adapters.  Also, a `vfchost` driver may get into a state where it stops processing I/O requests from the client. Applying IBM APAR IJ22290 IBM APAR IJ23222 will fix the issue. | NA

|===

// BURT 1483343, 2022-16-06
