---
sidebar: sidebar
permalink: hu_aix_61_rn.html
keywords: host utilities, aix, 6.1 netapp, ontap
summary: Release Notes for Linux Unified Host Utilities 7.1
---

= AIX Host Utilities 6.1 Release Notes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
These Release Notes contain the latest information for the AIX Host Utilities 6.1, including updates about known problems and limitations, information on tunable parameters, and any important cautions. The Release Notes also include any issues that may have been discovered since the Host Utilities were released.

These Release Notes are updated when new information on using the AIX Host Utilities becomes available.

== About the AIX Host Utilities 6.1 release

The AIX Host Utilities enable you to connect an AIX host to NetApp storage. The AIX Host Utilities support multiple environments and the FC, FCoE, and iSCSI protocols. The  supported environments are AIX MPIO (Native OS) and PowerVM.

[NOTE]
====
* For specific information about the operating system versions and updates that the Host Utilities support, see the link:https://mysupport.netapp.com/matrix/imt.jsp?components=85803;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

* For more information about PowerVM feature, see the IBM PowerVM Live Partition Mobility Red Book.
====

The Host Utilities software is packaged as a single, compressed file. You can download the compressed file and the documentation from the link:http://support.netapp.com[NetApp Support Site]. The link:https://docs.netapp.com/us-en/ontap-sanhost/hu_aix_61.html[AIX Host Utilities 6.1 / FCP and ISCSi Host Configuration Guide] available provides instructions for installing and setting up the Host Utilities to work with your environment and protocol.

[NOTE]
You must enable Dynamic Tracking for all FC and FCoE initiators for clustered Data ONTAP deployments.

== AIX Host Utilities 6.1 enhancements

The release of the AIX Host Utilities 6.1 added following updates.

*October 2021*
The release of the AIX Host Utilities 6.1 added the following feature.

*	Added fix for the Burt: 872113, which was reported with AIX Host Utilities 6.0 release.
+
With AIX Host Utilities 6.1, only the sanlun binary is changed. The MPIO and related ODM remains unchanged.
+
The sample command output from the aix host will be:
+
----
aix_host #: lslpp -l |grep -i netapp
  NetApp.MPIO_Host_Utilities_Kit.config
                             6.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             6.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             6.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             6.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.SAN_toolkit.sanlun  6.1.0.0  COMMITTED  NetApp SAN Toolkit sanlun
aix_host #:

aix_host #: sanlun version
6.1.451.438
----

== Known Problems and Limitations
To use the Host Utilities most efficiently, you should be aware that performance can be affected by known issues about a particular feature, such as a network, or by features that the Host Utilities do not support, such as a specific version of an operating system.

[cols=3,options="header"]
|===
|NetApp Bug ID	|Title	|Description
|1069147	|AIX HU Sanlun reports incorrect HBA speed	|This seems to be a reporting issue only. In order to identify the actual speed, use the `fcstat fcsx |grep "Port Speed"`.
|===
Bugs might have been fixed in a maintenance or patch release. link:https://mysupport.netapp.com/site/[NetApp Bugs Online] provides complete information for most known issues, including suggested workarounds where possible.

Some keyword combinations and Bug Type(s) that you might want to use include the following:

*	FCP General: Displays FC and HBA bugs that are not associated with a specific host.
*	FCP - AIX


== About SAN Host Configuration documentation
Documentation for SAN Host Utilities is included in the ONTAP SAN Host Configuration documentation. ONTAP SAN HOST configuration documentation is cumulative, covering all current SAN HOST releases. Any functional differences across releases are noted in context.


== Where to find product documentation and other information
You can access documentation for all NetApp products and find other product information resources, such as technical reports and white papers on the Product Documentation page of the NetApp corporate site.

.Related information

*Configuring and managing your ONTAP storage system*

*	The link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html[ONTAP Software Setup Guide] for your version of ONTAP
*	The link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP San Administration Guide] for your version of ONTAP
*	The link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes] for your version of ONTAP
* link:https://mysupport.netapp.com/site/[NetApp Interoperability Matrix]
* link:https://hwu.netapp.com/[Hardware Universe] (formerly the System Configuration Guide)
* link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[Supported Fibre Channel SAN topologies]
* link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343[Configuring your host for Host Utilities]
