---
sidebar: sidebar
permalink: hu_aix_rn.html
keywords: host utilities, aix, 6.1 netapp, 7.0, ontap, powervm
summary: Release Notes for AIX Host Utilities 6.1
---
= AIX Host Utilities Release Notes
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The release notes describe new features and enhancements, issues fixed in the current release, known problems and limitations, and important cautions related to configuring and managing your specific AIX host with your ONTAP storage system.

For specific information about the operating system versions and updates that the Host Utilities support, see the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^].

The AIX Host Utilities releases contain the following new features and enhancements.

== What's new in AIX Host Utilities 8.0
An IBM Interim Fix (ifix) is available for AIX Host Utilities 8.0 that ensures that the `sanlun fcp show adapter –v` command displays the correct HBA speed information, such as supported and negotiated speeds for the adapters. You can install the ifix on the following AIX and VIOS versions:

* AIX: 7.3 TL3 SP0, 7.3 TL2 SP2, 7.3 TL1 SP4, 7.2 TL5 SP9, 7.2 TL5 SP8
* VIOS: 4.1.1.0, 4.1.0.21, 3.1.4.50, 3.1.4.41

For more details about the IBM ifixes, refer to <KB_Article>.

There isn't an IBM ifix available for installation that displays the correct HBA speed information for all AIX and VIOS versions.

== What's new in AIX Host Utilities 7.0
AIX Host Utilities 7.0 supports SCSI UNMAP on the AIX host OS. With AIX Host Utilities 7.0, SCSI thin provisioning functions seamlessly with AIX and NetApp LUNs for FC devices.

== What's new in AIX Host Utilities 6.1
AIX Host Utilities 6.1 includes support for the memory fault issue that occurred in AIX host OS versions earlier than 6.1. With AIX Host Utilities 6.1, only the sanlun binary has changed. The Microsoft Multipath I/O (MPIO) and related ODM remain unchanged.

== Supported AIX environments and protocols
You can use the following support and features with the NVMe-oF host configuration for AIX hosts:

* Beginning with ONTAP 9.13.1, NVMe/FC support is added for IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2, and VIOS 3.1.4.21 with SAN boot support for both physical and virtual stacks. See the IBM documentation for more information on setting up SAN boot support.

* NVMe/FC is supported with Power9 and Power10 IBM servers.

* A separate PCM (Path Control Module), such as Host Utilities for AIX SCSI Multipath I/O (MPIO) support, isn't required for NVMe devices.

* Virtualization support with NetApp (VIOS/PowerVM) is introduced with VIOS 3.1.4.21. This is _only_ supported through NPIV (N_PortID Virtualization) storage virtualization mode using the Power10 IBM server.

== Known issues and limitations
You should be aware of the following known issues and limitations that might impact performance on your specific host:

** Qlogic/Marvel 32G FC HBAs on an AIX host doesn't support NVMe/FC.
** SAN booting isn't supported for NVMe/FC devices using a Power9 IBM server.

[cols=3,options="header"]
|===
|Bug ID	|Title	|Description
|N/A
|SCSI UNMAP support for ONTAP iSCSI LUNs |AIX Host Utilities 7.0 only supports the SCSI UNMAP feature for FC devices. SCSI UNMAP support for iSCSI devices are not included in this release.
|link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1069147[1069147^]
|AIX HU Sanlun reports incorrect HBA speed	|Instances of sanlun displaying incorrect HBA speeds are reported while running the `sanlun fcp show adapter –v` command.  The `sanlun fcp show adapter –v` command displays the HBA cards information, such as supported and negotiated speeds for the adapters. This seems to be a reporting issue only. To identify the actual speed, use the `fcstat fcsx` command.
|===

link:https://mysupport.netapp.com/site/[NetApp Bugs Online^] provides complete information for most known issues, including suggested workarounds where possible. Some keyword combinations and bug types that you might want to use include the following:

*	FCP General: Displays FC and HBA bugs that are not associated with a specific host.
*	FCP - AIX
