---
sidebar: sidebar
permalink: hu_aix_61.html
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap
summary: Describes how to use IBM AIX 7.2 and/or PowerVM VIOS 3.1 with with ONTAP
---
= Install AIX Host Utilities 6.1 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The AIX Host Utilities help you manage ONTAP storage attached to an AIX host and assist technical support with gathering configuration data.

The AIX Host Utilities support the following transport protocols and AIX environments.

* FC, FCoE, and iSCSI
* AIX Microsoft Multipath I/O (MPIO) (Native OS)
* PowerVM 
+
For more information about PowerVM, see the IBM PowerVM Live Partition Mobility Red Book.

.About this task
* You download the AIX Host Utilities from the NetApp Support site in a compressed `tar.gz` file.
* You can only install the AIX Host Utilities kit when you're using AIX MPIO with ONTAP storage.

.Before you begin

* Use the https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that all components in your iSCSI, FC, or FCoE configuration are supported.

* Enable dynamic tracking for all FC and FCoE initiators.



.Steps

. Log in to your host.
+
[role="tabbed-block"]
====
.AIX
--
On an AIX host, log in as *root*.
--

.PowerVM
--
On a PowerVM host:

.. Log in as *padmin*.
.. Become a root user:
+
[source,cli]
----
`oem_setup_env`
----
--
====

. Go to the https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads[NetApp Support Site^] and download the compressed file containing the Host Utilities to a directory on your host.

. Go to the directory containing the download.

. Decompress the file and extract the SAN Toolkit software package.
+
`# tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
The following directory is created when you decompress the file: `ntap_aix_host_utilities_6.1`. This directory will have one of the following subdirectories: MPIO, NON_MPIO, or SAN_Tool_Kit.

. Install the AIX MPIO:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Install the SAN Toolkit:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Reboot the host.

. Verify the installation:
+
----
# sanlun version
----

include::_include/hu/aix-whats-next.adoc[]

