---
sidebar: sidebar
permalink: hu_centos_81.html
keywords: host utilities, centos, linux, 8.1, netapp, ontap
summary: Install Linux Host Utilities on an CentOS 8.1 host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure CentOS 8.1 for FCP and iSCSI for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a CentOS 8.1 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities-80.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with CentOS 8.1 to manage ONTAP LUNs.

include::_include/hu/linux-centos-multipathing.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-customize-parameters.adoc[]

== Step 6: Review the known issues

There are no known issues for CentOS 8.1 for FCP and iSCSI with ONTAP storage.

For CentOS Red Hat compatible kernel known issues, see the link:hu_rhel_81.html#known-problems-and-limitations[known issues] for Red Hat Enterprise Linux (RHEL) 8.1.

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]

// 2025 JUN 30, ONTAPDOC-3068