---
sidebar: sidebar
permalink: hu_citrix_84.html
keywords: host utilities, citrix, XenServer, 8 series, netapp, ontap, san, boot
summary: Describes how to use Citrix XenServer 8.4 with ONTAP
---

= Configure Citrix Xenserver 8.4  for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a Citrix Xenserver 8.4  host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Citrix Xenserver 8.4 to manage ONTAP LUNs.

For Citrix Xenserver 8.4  the `/etc/multipath.conf` file must exist, but you do not need to make specific changes to the file. Citrix Xenserver  8.4 is compiled with all settings required to recognize and correctly manage ONTAP LUNs.

You can use the `/sbin/mpathutil` status command to verify the settings for your ONTAP LUNs.

include::_include/hu/citrix-8x-multipathing.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/citrix-multipath-parameters.adoc[]

== Step 6: Review the known issues

There are no known issues for the FC host configuration for Citrix Xenserver 8.4 with ONTAP release.

== What's next?

•	link:https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71_cmd.html[Learn about using the Linux Host Utilities tool].
•	Learn about ASM mirroring.
Automatic Storage Management (ASM) mirroring might require changes to the Linux multipath settings to allow ASM to recognize a problem and switch over to an alternate failure group. Most ASM configurations on ONTAP use external redundancy, which means that data protection is provided by the external array and ASM doesn't mirror data. Some sites use ASM with normal redundancy to provide two-way mirroring, normally across different sites. See link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html[Oracle databases on ONTAP] for further information.

//ONTAPDOC-3030 29-May-2025