---
sidebar: sidebar
permalink: hu_hpux_60.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the HP-UX Host Utilities 6.0 with ONTAP storage
---
= Install HP-UX Host Utilities 6.0 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The HP-UX Host Utilities help you manage ONTAP storage attached to an HP-UX host. NetApp strongly recommends installing the HP-UX Host Utilities, but it isn't mandatory. The utilities improve management and assist NetApp customer support in gathering information about your configuration.

The HP-UX Host Utilities support the following environments:

* Native Microsoft Multipath I/O (MPIO)
* Veritas Dynamic Multipathing (DMP)

.Before you begin

For reliable operation, use the https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that your iSCSI, FC, or FCoE configuration is supported.

.Steps

. Log in to your HP-UX host host.

. Download the HP-UX Host Utilities file `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` from the link:https://mysupport.netapp.com/site/[NetApp Support Site^] to your HP-UX host.

. Decompress the `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` file:
+
[source,cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
The system places the extracted software in the directory where you uncompressed the depot file.

. Install the software:
+
[source,cli]
----
swinstall -s /depot_path
----
+
`depot_path` provides the path and name of the depot file.
+
The `swinstall` command runs an installation script that verifies the status of your HP-UX setup. If your system meets the requirements, this script installs the `sanlun` utility and diagnostic scripts in the `/opt/NetApp/santools/bin` directory.

. Verify the installation:
+
[source,cli]
----
sanlun version
----

== What's next?

link:hu-hpux-sanlun-toolkit.html[Learn about the SAN Toolkit].