---
sidebar: sidebar
permalink: hu_hpux_11iv3.html
keywords: host utilities, hp_ux, 11iv3, netapp, ontap
summary: Install Linux Host Utilities on a HP-UX 11i v3 host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure HP-UX 11i v3 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The HP-UX Host Utilities software provides management and diagnostic tools for HP-UX hosts that are connected to ONTAP storage. When you install the HP-UX Host Utilities on a HP-UX 11i v3 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

== Step 1: Optionally, enable SAN booting

Configure your host to use SAN booting to simplify deployment and improve scalability. SAN booting is the process of setting up a SAN-attached disk (a LUN) as a boot device for a HP-UX host. The Host Utilities support SAN booting with FC and FCoE protocols in HP-UX environments.

.Steps
. Use the link:https://mysupport.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that your Linux OS, host bus adapter (HBA), HBA firmware, HBA boot BIOS, and ONTAP version support SAN booting.

. Follow the best practices for setting up a SAN boot in the HP-UX vendor documentation.


== Step 2: Install the HP-UX Host Utilities

NetApp strongly recommends installing the HP-UX Host Utilities to support ONTAP LUN management and assist technical support with gathering configuration data.

link:hu_hpux_60.html[Install HP-UX Host Utilities 6.0] 

== Step 3: Confirm the multipath configuration for your host

Use multipathing with HP-UX 11i v3 to manage ONTAP LUNs. Multipathing allows you to configure multiple network paths between the host and storage system. If one path fails, traffic continues on the remaining paths. 

After installing HP-UX Host Utilities, verify that you have the NetApp recommended settings configured for your ONTAP LUNs. 

.About this task
The HP-UX Host Utilities support Native Microsoft Multipath I/O (MPIO) and Veritas Dynamic Multipathing. The following steps are for the Native MPIO solution.

.Steps

. When you install the HP-UX Host Utilities, the following recommended default settings are automatically loaded for ONTAP LUNs.
+
.Show parameter settings
[%collapsible]
====
[cols=2*, options="header"]
|===
| Parameter
| Uses Default Value
| transient_secs | 120
| leg_mpath_enable | TRUE
| max_q_depth  | 8
| path_fail_secs | 120
| load_bal_policy | Round_robin
| lua_enabled  | TRUE
| esd_secs | 30
|===
====

. Verify the parameter settings and path status for your ONTAP LUNs:
+
[source,cli]
----
sanlun lun show
----
+
The default multipath parameters support ASA, AFF, and FAS configurations. The following example outputs show the correct parameter settings and path status for ONTAP LUNs in an ASA, AFF, or FAS configuration.
+
[role="tabbed-block"]
====
.ASA configuration
--
An ASA configuration optimizes all paths to a given LUN, keeping them active. This improves performance by serving I/O operations through all paths at the same time.

----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
--

.AFF or FAS configuration
--
An AFF or FAS configuration should have two groups of paths with higher and lower priorities. Higher priority Active/Optimized paths are served by the controller where the aggregate is located. Lower priority paths are active but non-optimized because they are served by a different controller. Non-optimized paths are only used when optimized paths aren’t available.

The following example displays the output for an ONTAP LUN with two Active/Optimized paths and two Active/Non-Optimized paths:

----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
--
====

== Step 4: Review the known issues

The HP-UX 11i v3 with ONTAP storage release has the following known issues:

[cols=4*, options="header"]
|===
| NetApp Bug ID
| Title
| Description
| Partner ID
| 1447287 | AUFO event on the isolated master cluster in SnapMirror active sync configuration causes temporary disruption on the HP-UX host | This issue occurs when there is an automatic unplanned failover (AUFO) event on the isolated master cluster in the SnapMirror active sync configuration. It might take more than 120 seconds for I/O to resume on the HP-UX host, but this might not cause any I/O disruption or error messages. This issue causes dual event failure because the connection between the primary and the secondary cluster is lost and the connection between the primary cluster and the mediator is also lost. This is considered a rare event, unlike other AUFO events. | NA
| 1344935 | HP-UX 11.31 Host intermittently reporting path status incorrectly on ASA setup. | Path reporting issues with ASA configuration. | NA
| 1306354 | HP-UX LVM creation sends I/O of block size above 1MB | SCSI Maximum Transfer Length of 1MB is enforced in ONTAP All SAN Array. To restrict the Maximum Transfer Length from HP-UX hosts when connected to ONTAP All SAN Array, it is required to set the Maximum I/O size allowed by the HP-UX SCSI subsystem to 1MB.

Refer HP-UX vendor documentation for details. | NA
|===

== What's next

link:hu_hpux_60_cmd.html[Learn about using the HP-UX Host Utilities tool].

// BURT 1451508, 2022-02-01
