---
sidebar: sidebar
permalink: hu_hpux_60_rn.html
keywords: host utilities, hpux, 6.0, netapp, ontap, release, notes
summary: Release Notes for HPUX Host Utilities 6.0
---

= HP-UX Host Utilities 6.0 Release Notes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
The release notes describe new features and enhancements, issues fixed in the current release, known problems and limitations, and important cautions related to configuring and managing your specific HU-PUX host with your ONTAP storage system.

The HP-UX Host Utilities 6.0 continues to support versions of the following:

* HP-UX 11iv2
* HP-UX 11iv3

There are no new features, enhancements, known limitations, or cautions for the HU-PUX host utilities 6.0 release.

== Where to find product documentation and other information

You can access documentation for all NetApp products and find other product information resources, such as technical reports and white papers on the Product Documentation page of the NetApp corporate site.

.Related information

*Configuring and managing your ONTAP storage system*

* The link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html[ONTAP Software Setup Guide for your version of ONTAP^]
* The link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP San Administration Guide for your version of ONTAP^]
* The link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes for your version of ONTAP^]
* link:https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix^]
* link:https://hwu.netapp.com/[Hardware Universe^] (formerly the System Configuration Guide)
* link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[Supported Fibre Channel SAN topologies]
* link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343[Configuring your host for Host Utilities^]





