---
sidebar: sidebar
permalink: hu_hpux_60_rn.html
keywords: host utilities, hpux, 6.0, netapp, ontap, release, notes
summary: Release Notes for HPUX Host Utilities 6.0
---

= HP-UX Host Utilities 6.0 Release Notes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[lead]
This Release Notes document contains the latest information on the HP-UX Host Utilities 6.0 release, including updates about known problems, limitations, and configuring and managing your ONTAP storage system. The Release Notes document is updated when new information on using the HP-UX Host Utilities becomes available.

== About the HP-UX Host Utilities 6.0 release

The HP-UX Host Utilities supports several HP-UX environments and multiple protocols.
The HP-UX Host Utilities support the following environments:

* Native MPIO
* Veritas Dynamic Multipathing (DMP)

NOTE: To make it immediately clear which environment is being used, this document sometimes specifies “DMP” for the Veritas DMP environment and “MPIO” for the HP-UX native environment. In some cases, the commands you use might vary depending on which drivers you are using. In those cases, both the environment and driver types are specified.

== HP-UX Host Utilities 6.0 enhancements

The Release Notes are updated between product releases as new information is available. The HP-UX Host Utilities 6.0 continues to support versions of the following:

* HP-UX 11iv2
* HP-UX 11iv3

== Known Problems and Limitations

There are no known issues for the HP-UX 6.0 release.

== About SAN Host Configuration documentation

Documentation for SAN Host Utilities is included in the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration documentation.] The ONTAP SAN Host configuration documentation is cumulative, covering all current SAN Host releases. Any functional differences across releases are noted in context.

== Where to find product documentation and other information

You can access documentation for all NetApp products and find other product information resources, such as technical reports and white papers on the Product Documentation page of the NetApp corporate site.

.Related information

*Configuring and managing your ONTAP storage system*

* The link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html[ONTAP Software Setup Guide for your version of ONTAP^]
* The link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP San Administration Guide for your version of ONTAP^]
* The link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes for your version of ONTAP^]
* link:https://imt.netapp.com/matrix/#welcome[NetApp Interoperability Matrix^]
* link:https://hwu.netapp.com/[Hardware Universe^] (formerly the System Configuration Guide)
* link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[Supported Fibre Channel SAN topologies]
* link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343[Configuring your host for Host Utilities^]
