---
sidebar: sidebar
permalink: hu_luhu_71_rn.html
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes
summary: Release Notes for Linux Unified Host Utilities 7.1
---

= Linux Unified Host Utilities 7.1 Release Notes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The release notes describe new features and enhancements, known problems and limitations, and important cautions for configuring and managing your specific host with your ONTAP storage system.

For specific information about the operating system versions and updates that the Host Utilities support, see the link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

== What's New 
The Linux Host Utilities 7.1 release contains the following new features and enhancements:

* Linux Host Utilities is now called _Linux Unified Host Utilities_ because it supports NetApp E-Series storage systems running SANtricity as well as AFF, FAS, and ASA systems running ONTAP.
+
[NOTE]
Any mention of Host Utilities or Linux Host Utilities in this document refers to Linux Unified Host Utilities.

* The following operating systems are now supported:
**	SUSE Linux Enterprise Server 15 series
**	Oracle VM 3.2 series
**	Oracle Linux 6 and 7 series
**	Red Hat Enterprise Linux 6 and 7 series
**	SUSE Linux Enterprise Server 11 SP4
**	KVM and XEN, RHEV 6.4 and 6.5
**	Citrix XenServer 

* On Red Hat Enterprise Linux (RHEL) 6 and RHEL 7 hosts, a tuned package for setting server profiles is now supported. You can use the `tuned-adm` command to set different profiles, depending on the environment. For example, you can also use the virtual guest profile as a guest virtual machine and you can use the enterprise storage profile for configurations where LUNs from enterprise storage arrays are used. Using these tuned packages can result in improvement in throughput and latency in ONTAP.

* Adds support for 32GB FC adapters from Broadcom Emulex and Marvell Qlogic.

[NOTE]
NetApp continues to work with the Host Utilities to add support for features after the initial release. For latest information about the features that are supported and the new features that have been added, see the link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

== Fixed in this release

The intermittent host OS failure issue that occurs when running the `sanlun lun show -p` command in SLES12SP1, OL7.2, RHEL7.2, and RHEL 6.8 is fixed in this release.


== Known problems and limitations

The Linux Host Utilities 7.1 release has the following known problems and limitations.

[cols=3,options="header", cols= "10, 30, 30"]
|===
|NetApp Bug ID	|Title | Description
|1457017	|`sanlun` installation issues warning messages related to `libdevmapper.so` and `libnl.so` libraries. These warnings do not affect the functionality of `sanlun` kit. | When you execute the Linux Unified Host Utilities CLI command - "sanlun fcp show adapter -v" on a SAN host, the command fails with an error message displaying that the library dependencies required for an host bus adapter (HBA) discovery cannot be 
located:

[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded
Refer to the public report 1508554.
|===

link:https://mysupport.netapp.com/site/bugs-online/product[NetApp Bugs Online^] provides complete information for most known issues, including suggested workarounds where possible.


