---
sidebar: sidebar
permalink: hu_luhu_71.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Linux Host Utilities 7.1 with ONTAP
---
= Install Linux Host Utilities 7.1 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/hu/install-linux-hu-introduction.adoc[]

Linux Host Utilities 7.1 supports the following distribution types:

*	Red Hat Enterprise Linux
*	SUSE Linux Enterprise Server
*	Oracle Linux
*	Oracle VM
*	Citrix XenServer

NOTE: The Linux Host Utilities software doesn't support NVMe over Fibre Channel (NVMe/FC) and NVMe over TCP (NVMe/TCP) host protocols.

.About this task

When you install the Linux Host Utilities, it doesn't change any settings on your Linux host.

.Before you begin
* For reliable operation, use the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that your iSCSI, FC, or FCoE configuration is supported.
* Install the host bus adapter (HBA) management packages available on the vendor support site. The management software enables the `sanlun` commands to gather information about the FC HBAs, such as their WWPNs. 
+
Refer to the vendor documentation to verify that the following packages are correctly installed. These packages are required to support the `sanlun fcp show adapter` command:
+
** Marvell QLogic HBA – QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand Manager core application CLI
** Marvell Brocade HBA – Brocade Command Utility CLI

* Install the RPM "libhbaapi" and "libhbalinux" packages available for each Linux distribution on the Linux host OS.

.Steps

. If you have a version of Linux Host Utilities currently installed, remove it:
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
For earlier versions of Linux Host Utilities, go to the directory where the host utility software is installed and enter the uninstall command to remove the installed package.

. Download the 32-bit or 64-bit Linux Host Utilities software package from the link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads[NetApp Support Site^] to your host.

. Go to the directory to which you downloaded the software package and install it:
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
You should see an output similar to the following example:
+
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----

. Verify the installation:
+
[source, cli]
----
sanlun version
----
+
You should see an output similar to the following example:
+
----
sanlun version 7.1.386.1644
----

include::_include/hu/linux-install-hu-whats-next.adoc[]