---
sidebar: sidebar
permalink: hu_luhu_71.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Linux Unified Host Utilities 7.1 with ONTAP
---

= Linux Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


== Pre-requisites

.Before you begin

* For reliable operation, you must verify that your entire iSCSI, FC, or FCoE configuration is supported.
+
You can use the https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify your configuration.

* You must install the HBA management packages provided by the vendors on their web sites.
+
The management software enables the SAN Tool kit commands to gather information about the FC HBAs, such as their WWPNs. For sanlun fcp show adapter to work, ensure that the following packages are installed:

**	QLogic HBA – QConvergeConsole CLI
** Emulex HBA - OneCommand Manager core application CLI
** Brocade HBA – Brocade Command Utility CLI

RPM Packages “libhbaapi” & “libhbalinux” available for each Linux Distribution should be installed on the host OS.

== SAN Toolkit

Linux Unified Host Utilities is a NetApp host software that provides a command line tool kit on your Linux host.

include::_include/hu/reuse_hu_san_toolkit.adoc[]

NOTE: This toolkit is common across all configurations and protocols of the Host Utilities.  As a result some of its contents apply to one configuration, but not another.  Having unused components does not affect your system performance.

NOTE: The SAN toolkit is not supported on Citrix XenServer, Oracle VM, and Red Hat Enterprise Virtualization Hypervisor.

== Installing Linux Unified Host Utilities

include::_include/hu/reuse_hu_installing_luhu.adoc[]
