---
sidebar: sidebar
permalink: hu_luhu_71.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Linux Unified Host Utilities 7.1 with ONTAP
---

= Install Linux Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Unified Host Utilities assists you to manage NetApp ONTAP storage attached to a Linux host. NetApp strongly recommends installing the Linux Unified Host Utilities, but it is not mandatory. The utilities do not change any settings on your Linux host. The utilities improve management and assist NetApp customer support in gathering information about your configuration. 

The following Linux distributions are supported:

*	Red Hat Enterprise Linux
*	SUSE Linux Enterprise Server
*	Oracle Linux
*	Oracle VM
*	Citrix XenServer

.What you'll need

The NetApp Linux Unified Host Utilities software package is available on the link:https://mysupport.netapp.com/site/[NetApp Support Site^] in a 32-bit or 64-bit .rpm file. 

* For reliable operation, you must verify that your entire iSCSI, FC, or FCoE configuration is supported.
+
You can use the https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify your configuration.

* You must install the host bus adapter (HBA) management packages available on the vendor support site.
+
The management software enables the SAN toolkit commands to gather information about the FC HBAs, such as their WWPNs. For the `sanlun fcp show adapter` command to work, verify that the following packages are correctly installed:

** Marvell QLogic HBA – QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand Manager core application CLI
** Marvell Brocade HBA – Brocade Command Utility CLI

* RPM Packages "libhbaapi" and "libhbalinux" available for each Linux distribution should be installed on the host OS.


.Steps

. If you have a version of Linux Unified Host Utilities currently installed, use the following command to remove it:
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
For older versions of Linux Host Utilities, go to the directory where the host utility software is installed and enter the uninstall command to remove the installed package.

. Download the 32-bit or 64-bit Linux Unified Host Utilities software package from the link:https://mysupport.netapp.com/site/[NetApp Support Site^] to your host.

. Go to the directory to which you downloaded the software package and use the following command to install it:
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
*Example output*
+
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----

. Verify the installation:
+
[source, cli]
----
sanlun version
----
+
*Example output*
+
----
sanlun version 7.1.386.1644
----

== Recommended driver and firmware with Linux kernel

When you configure an FC environment that uses native, inbox drivers that are bundled with the Linux kernel, you can use the default values for the drivers. 

== SAN Toolkit

Linux Unified Host Utilities is a NetApp host software that provides a command line tool kit on your Linux host.

include::_include/hu/reuse_hu_san_toolkit.adoc[]

NOTE: This toolkit is common across all configurations and protocols of the Host Utilities. As a result some of its contents apply to one configuration, but not another. Having unused components does not affect your system performance.

NOTE: The SAN toolkit is not supported on Citrix XenServer, Oracle VM, and Red Hat Enterprise Virtualization Hypervisor.

== Command reference 

You can refer to the link:hu_luhu_71_cmd.html[sample command reference] to verify the installation.

