---
sidebar: sidebar
permalink: hu_luhu_71.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Linux Unified Host Utilities 7.1 with ONTAP
---

= Linux Unified Host Utilities 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Unified Host Utilities enable you to connect a Linux host to NetApp storage.

NetApp strongly recommends installing the Linux Unified Host Utilities, but it is not mandatory. The utilities do not change any settings on your Linux host. The utilities improve management and assist NetApp customer support in gathering information about your configuration. 

.Supported Linux versions 

*	Red Hat Enterprise Linux
*	SUSE Linux Enterprise Server
*	Oracle Linux
*	Oracle VM
*	Citrix XenServer
*	Veritas

The NetApp Linux Unified Host Utilities software package is available on the link:https://mysupport.netapp.com/site/[NetApp Support Site^] in a 32-bit or 64-bit .rpm file.

.What you'll need

* For reliable operation, you must verify that your entire iSCSI, FC, or FCoE configuration is supported.
+
You can use the https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify your configuration.

* You must install the HBA management packages provided by the vendors on their websites.
+
The management software enables the SAN toolkit commands to gather information about the FC HBAs, such as their WWPNs. For the `sanlun fcp show adapter` command to work, verify that the following packages are installed:

** QLogic HBA – QConvergeConsole CLI
** Emulex HBA - OneCommand Manager core application CLI
** Brocade HBA – Brocade Command Utility CLI
** RPM Packages "libhbaapi" and "libhbalinux" available for each Linux Distribution should be installed on the host OS.

== Default values recommended when using drivers bundled with Linux kernel
When you are setting up an FC environment that uses the native, inbox drivers that are bundled with the Linux kernel, you can use the default values for the drivers. In iSCSI environments where you are using a iSCSI solution software, you need to manually set certain recommended values depending on the OS version you are using.

== SAN Toolkit

Linux Unified Host Utilities is a NetApp host software that provides a command line tool kit on your Linux host.

include::_include/hu/reuse_hu_san_toolkit.adoc[]

NOTE: This toolkit is common across all configurations and protocols of the Host Utilities. As a result some of its contents apply to one configuration, but not another. Having unused components does not affect your system performance.

NOTE: The SAN toolkit is not supported on Citrix XenServer, Oracle VM, and Red Hat Enterprise Virtualization Hypervisor.

Review the link:hu_luhu_71_cmd.html[Sample Command reference].
