---
sidebar: sidebar
permalink: hu_luhu_71_rn.html
keywords: host utilities, linux, 7.1, netapp, ontap
summary: Release Notes for Linux Unified Host Utilities 7.1
---

= Linux Unified Host Utilities 7.1 Release Notes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This Release Notes document contains the latest information for the Linux Unified Host Utilities 7.1 release, including updates about known problems and limitations, any important cautions, new features, and enhancements. It also describes any issues that might have been discovered since the Host Utilities were released.

== About the Linux Unified Host Utilities 7.1 release
The Linux Unified Host Utilities support several Linux operating systems. The Host Utilities enable you to connect a Linux host to NetApp storage systems.

The Linux Unified Host Utilities 7.1 continues to support the following versions of Linux:

*	Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
*	Oracle Linux
*	Oracle VM
*	Citrix XenServer
* Veritas

[NOTE]
For specific information about the operating system versions and updates that the Host Utilities support, see the link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

The Host Utilities software is provided as both 32-bit and 64-bit .rpm  files. You can download the correct .rpm  file for your host architecture and the documentation from the link:https://mysupport.netapp.com/site/[NetApp Support Site^].

For instructions about installing and setting up, see the link:https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html[Linux Unified Host Utilities 7.1 Installation Guide].


== What's new in the 7.1 release

Linux Host Utilities is now called _Linux Unified Host Utilities_ because it supports NetApp E-Series storage systems running SANtricity as well as AFF and FAS systems running ONTAP.

[NOTE]
Any mention of Host Utilities or Linux Host Utilities in this document refers to Linux Unified Host Utilities.

* This release of the Linux Unified Host Utilities provides support for a tuned package for setting server profiles and improving I/O performance on Red Hat Enterprise Linux 6 and 7 hosts.

* The Linux Unified Host Utilities 7.1 continues to support versions of the following:

** Red Hat Enterprise Linux
** SUSE Linux Enterprise Server
** Oracle Linux
** Oracle VM
** Citrix XenServer
** Veritas

*	Red Hat Enterprise Linux 6 and 7 now have a tuned package with a `tuned-adm` command to set different server profiles on the host depending on the environment.
**	This includes an enterprise storage profile for configurations where LUNs from enterprise storage arrays are used. You can also use the virtual guest profile for Red Hat Enterprise Linux as a guest virtual machine. Using these tuned packages can result in marked improvement in throughput and latency on ONTAP.


[NOTE]
NetApp continues to work with the Host Utilities to add support for features after the initial release. For latest information about the features that are supported and the new features that have been added, see the link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].


== New features and enhancements

The Release Notes are updated between product releases as new information is available.

=== 7.1 enhancements

*	This release includes support for the following:
**	SUSE Linux Enterprise Server 15 series
**	Oracle VM 3.2 series
**	Oracle Linux 6 and 7 series
**	Red Hat Enterprise Linux 6 and 7 series
**	SUSE Linux Enterprise Server 11 SP4
**	KVM and XEN, RHEV 6.4 and 6.5
**	Citrix XenServer parameters

*	Adds support for 32 GB Fibre Channel adapters from Emulex and Qlogic.
*	Fixes `sanlun lun show -p getting SIGABRT` in SLES12SP1, OL7.2, RHEL7.2, and RHEL 6.8.
*	Extends support for Red Hat Linux 6.8, Oracle Linux 6.8, XenServer 7.0, Oracle VM 3.3 series, and Oracle VM 3.4 series operating systems.


== Known Problems and Limitations

[cols=2*,options="header"]
|===
|NetApp Bug ID	|Description
|1457017	|sanlun installation warnings for library files.
|===

Bugs might have been fixed in a maintenance or patch release. link:https://mysupport.netapp.com/site/bugs-online/product[NetApp Bugs Online] provides complete information for most known issues, including suggested workarounds where possible.

Some keyword combinations and bug types that you might want to use include the following:

*	FCP - Linux
*	iSCSI – Linux



Refer to the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration documentation] for more information on Host OS settings and configurations.

== About SAN Host Configuration documentation
Documentation for SAN Host Utilities is included in the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration documentation]. ONTAP SAN HOST configuration documentation is cumulative, covering all current SAN HOST releases. Any functional differences across releases are noted in context.

=== Additional information
==== Default values recommended when using drivers bundled with Linux kernel
When you are setting up an FC environment that uses the native, inbox drivers that are bundled with the Linux kernel, you can use the default values for the drivers. In iSCSI environments where you are using a iSCSI solution software, you need to manually set certain  recommended values depending on the OS version you are using.

== Where to find product documentation and other information
You can access documentation for all NetApp products and find other product information resources, such as technical reports and white papers on the Product Documentation page of the NetApp corporate site.

.Related information

*Configuring and managing your ONTAP storage system*

*	The link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html[ONTAP Software Setup Guide^] for your version of ONTAP
*	The link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP San Administration Guide^] for your version of ONTAP
*	The link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^] for your version of ONTAP

*Configuring and managing your E-Series storage system*

*	The SANtricity Storage Manager Configuration and Provisioning for Windows Express Guide that is appropriate for your protocol
*	The SANtricity Storage Manager Configuration and Provisioning Express Guide for your operating system, protocol, and version of SANtricity.
*	The SANtricity Storage Manager Software Installation Reference specific for your version of SANtricity.
*	The SANtricity Storage Manager Multipath Driver's Guide specific for your version of SANtricity.
*	The SANtricity Storage Manager Release Notes for your version of SANtricity.

Go to the link:https://docs.netapp.com/us-en/e-series/getting-started/index.html[E-Series documentation] to find SANtricity related documentation.
