---
sidebar: sidebar
permalink: hu_ol_94.html
keywords: host utilities, oracle, linux, 9.4, netapp, ontap
summary: Describes how to use Oracle Linux 9.4 with ONTAP
---

= Use Oracle Linux 9.4 with ONTAP
:hardbreaks:
:toclevels: 1P
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure Oracle Linux 9.4 with ONTAP as the target.

== Install the Linux Host Utilities

include::_include/hu/reuse_hu_installing_luhu_without32.adoc[]

== Use the SAN Toolkit

include::_include/hu/reuse_hu_san_toolkit_withoutexample.adoc[]

In the following example, the `sanlun lun show` command returns LUN information.
----
sanlun lun show all
----
.Show example
[%collapsible]
====
----
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
--------------------------------------------------------------------------------------------------------
vs_coexistence_147            /vol/fc_vol_2_9/dynamic_lun    /dev/sdcm       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_8/dynamic_lun    /dev/sdcl       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_7/dynamic_lun    /dev/sdck       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_6/dynamic_lun    /dev/sdcj       host12     FCP        10g     cDO

----
====

== Enable SAN booting
If you decide to use SAN booting, it must be supported by your configuration.

.Before you begin

Use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware, HBA boot BIOS, and the ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Enable multipathing

You can use multipathing with Oracle Linux 9.4 to manage ONTAP LUNs. To use multipathing, the `/etc/multipath.conf` file must exist. If the `/etc/multipath.conf` file doesn't exist, you can create an empty, zero-byte file by using the touch `/etc/multipath.conf` command. You don't need to make changes to the `/etc/multipath.conf` file because Oracle Linux 9.4 is compiled with all the settings required to recognize and correctly manage ONTAP LUNs.

NOTE: A single LUN shouldn't require more than four paths. More than four paths might cause path issues during storage failures.

include::_include/hu/reuse_hu_asa_configuration.adoc[]



.Show example
[%collapsible]
====
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
====


include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

.Show example
[%collapsible]
====
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====

== Recommended settings

The Oracle Linux 9.4 OS recognizes ONTAP LUNs and automatically sets all configuration parameters correctly for both ASA and non-ASA configurations. You can further optimize performance for your host configuration with the following recommended settings.

include::_include/hu/reuse-hu-systemctl-multipathd.adoc[]


[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | infinity
| failback | immediate
| fast_io_fail_tmo | 5
| features | 2 pg_init_retries 50
| flush_on_last_del | yes
| hardware_handler | 0
| no_path_retry | queue
| path_checker | tur
| path_grouping_policy | group_by_prio
| path_selector | service-time 0
| polling_interval | 5
| prio | ontap
| product | LUN
| retain_attached_hw_handler | yes
| rr_weight | uniform
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example demonstrates how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because other SAN arrays are still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

.Show example
[%collapsible]
====
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP"
 product "LUN"
 no_path_retry queue
 path_checker tur
 }
}
----
====

NOTE: To configure Oracle Linux 9.4 Red Hat Compatible Kernel (RHCK), use the link:hu_rhel_94.html#recommended-settings[recommended settings] for Red Hat Enterprise Linux (RHEL) 9.4.

include::_include/hu/reuse_hu_kvm_configuration.adoc[]

== Known issues

There are no known issues for the FC host configuration for OL 9.4 with ONTAP release.

//ONTAPDOC-2578 9-Dec-2024
