---
sidebar: sidebar
permalink: hu_ol_91.html
keywords: host utilities, oracle, linux, 9.1, netapp, ontap
summary: Install Linux Host Utilities on an Oracle Linux 9.1 host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure Oracle Linux 9.1 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure Oracle Linux 9.1 with ONTAP as the target.

== Install the Linux Host Utilities

NetApp strongly recommends installing the Linux Host Utilities to support ONTAP LUN management and assist technical support with gathering configuration data.

link:hu-luhu-80.html[Install Linux Host Utilities 8.0]. 

NOTE: Installing the Linux Host Utilities doesn't change any host timeout settings on your Linux host.

== SAN Toolkit

The toolkit is installed automatically when you install the NetApp Host Utilities package. This kit provides the `sanlun` utility, which helps you manage LUNs and host bus adapters (HBAs). The `sanlun` command returns information about the LUNs mapped to your host, multipathing, and information necessary to create initiator groups.

In the following example, the `sanlun lun show` command returns LUN information.
----
# sanlun lun show all
----

.Example output:
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       80.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       80.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       80.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       80.0g  cDOT
----

== SAN booting

.Before you begin

If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For OL 9.1 the `/etc/multipath.conf` file must exist, but you do not need to make specific changes to the file. OL 9.1 is compiled with all the settings required to recognize and correctly manage ONTAP LUNs.

include::_include/hu/linux-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Oracle Linux 9.1 to manage ONTAP LUNs.

NOTE: You can use the link:hu_rhel_91.html#rhel-rhck[recommended settings for Red Hat Enterprise Linux (RHEL) 9.1] to configure Red Hat Compatible Kernel for Oracle Linux 9.1.

include::_include/hu/linux-ol-multipathing.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-ol-customize-parameters.adoc[]

== Step 6: Review the known issues

The Oracle Linux 9.1 with NetApp ONTAP storage release has the following known issues:

[cols="20,40,40",options="header"]
|===
|NetApp Bug ID	|Title	|Description
|https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1508554[1508554^]	|SAN LUN utility with Emulex HBA needs symbolic links from library packages	a|When you execute the Linux Host Utilities CLI command - "sanlun fcp show adapter -v" on a SAN host, the command fails with an error message displaying that the library dependencies required for a host bus adapter (HBA) discovery cannot be located:
----
[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded
----
|===

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]
