---
sidebar: sidebar
permalink: hu_ol_93.html
keywords: host utilities, oracle, linux, 9.3, netapp, ontap
summary: Install the Linux Host Utilities on an Oracle Linux 9.3 host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure Oracle Linux 9.3 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on an Oracle Linux 9.3 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities-80.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Oracle Linux 9.3 to manage ONTAP LUNs.

NOTE: You can use the link:hu_rhel_93.html#rhel-rhck[recommended settings for Red Hat Enterprise Linux (RHEL) 9.3] to configure Red Hat Compatible Kernel for Oracle Linux 9.3.

include::_include/hu/linux-ol-multipathing-93-and-earlier.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-customize-parameters.adoc[]

== Step 6: Review the known issues

The Oracle Linux 9.3 with ONTAP storage release has the following known issue:

[cols="20,40,40",options="header"]
|===
|NetApp Bug ID	|Title	|Description
|https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1508554[1508554^]	|SAN LUN utility with Emulex HBA needs symbolic links from library packages	a|When you execute the Linux Host Utilities CLI command - "sanlun fcp show adapter -v" on a SAN host, the command fails with an error message displaying that the library dependencies required for an host bus adapter (HBA) discovery cannot be located:
----
[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded
----

|===

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]
