---
sidebar: sidebar
permalink: hu_ol_73.html
keywords: host utilities, oracle, linux, 7.3, netapp, ontap
summary: Install Linux Host Utilities on an Oracle Linux 7.3 host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure Oracle Linux 7.3 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on an Oracle Linux 7.3 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Oracle Linux 7.3 to manage ONTAP LUNs.

NOTE: You can use the link:hu_rhel_73.html#rhel-rhck[recommended settings for Red Hat Enterprise Linux (RHEL) 7.3] to configure Red Hat Compatible Kernel for Oracle Linux 7.3.

include::_include/hu/linux-ol-multipathing-chk-config-aff-fas.adoc[]

== Step 4: Optionally, exclude a device from multipathing

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-ol-customize-parameters.adoc[]

== Step 6: Review the known issues

There are no known issues.

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]

