---
sidebar: sidebar
permalink: hu_ol_71.html
keywords: Host Utilities, oracle, linux, 7.1, netapp, ontap
summary: Install Linux Host Utilities on an Oracle Linux 7.1 host to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure Oracle Linux 7.1 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on an Oracle Linux 7.1 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-configure-kvm-note.adoc[]

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with Oracle Linux 7.1 to manage ONTAP LUNs. Oracle Linux 7.1 supports Unbreakable Enterprise Kernel (UEK) R3 and UEK R4. The OS boots with UEK R3 kernel by default. 

NOTE: You can use the link:hu_rhel_71.html#rhel-rhck[recommended settings for Red Hat Enterprise Linux (RHEL) 7.1] to configure Red Hat Compatible Kernel for Oracle Linux 7.1.

include::_include/hu/linux-ol-multipathing-alua.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-ol-customize-parameters.adoc[]

== Step 6: Review the known issues

There are no known issues.

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]
