---
sidebar: sidebar
permalink: hu_rhel_93.html
keywords: host utilities, red hat, rhel, linux, 9.3, netapp, ontap, rhel 
summary: Describes how to use Red Hat Enterprise Linux 9.3 with ONTAP
---

= Use Red Hat Enterprise Linux 9.3 with ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure Red Hat Enterprise Linux 9.3 with ONTAP as the target. 

== Install the Linux Unified Host Utilities

include::_include/hu/reuse_hu_installing_luhu_without32.adoc[]

== SAN Tool Kit

include::_include/hu/reuse_hu_san_toolkit_withoutexample.adoc[]

In the following example, the `sanlun lun show` command returns LUN information.

[source,cli]
----
# sanlun lun show all
----
*Example output:*
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
vs_147_32glpe	         /vol/vol1/lun	 /dev/sdb	Host11  FCP        10g	cDOT				
vs_147_32glpe	         /vol/vol1/lun	 /dev/sdx	Host11  FCP        10g	cDOT				
vs_147_32glpe	         /vol/vol2/lun	 /dev/sdbt   host12 FCP        10g	cDOT				
vs_147_32glpe	         /vol/vol2/lun	 /dev/sdax	host12  FCP        10g	cDOT				
----

== SAN booting

.What you'll need
If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For Red Hat Enterprise Linux (RHEL) 9.3, the `/etc/multipath.conf` file must exist, but you do not need to make specific changes to the file. RHEL 9.3 is compiled with all settings required to recognize and correctly manage ONTAP LUNs.

include::_include/hu/reuse_hu_multipathing.adoc[]

include::_include/hu/reuse_hu_asa_configuration.adoc[]

----
# multipath -ll
3600a098038314359725d516c69733471 dm-22 NETAPP,LUN C-Mode
size=160G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:3:0  sdau 66:224 active ready running
  |- 12:0:4:0  sdco 69:192 active ready running
  |- 12:0:0:0  sdav 66:240 active ready running
  `- 11:0:2:0  sdat 66:208 active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# multipath -ll
3600a0980383149783224544d334a644d dm-10 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 12:0:0:18 sdbj 67:208 active ready running
| `- 11:0:1:18 sdan 66:112 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:18 sdt  65:48  active ready running
  `- 12:0:3:18 sdcf 69:48  active ready running

----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

== Recommended settings

The RHEL 9.3 OS is compiled to recognize ONTAP LUNs and automatically set all configuration parameters correctly for both ASA and non-ASA configurations. You can further optimize performance for your host configuration with the following recommended settings.

include::_include/hu/reuse_hu_recommended_settings.adoc[]

[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because other SAN arrays are still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
defaults {
   path_checker      readsector0
   no_path_retry     fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry    queue
      path_checker     tur
   }
}
----

include::_include/hu/reuse_hu_kvm_configuration.adoc[]

== Known issues

The RHEL 9.3 with ONTAP release has the following known issues:

[options="header", cols="20, 20, 50,20"]
|===
|NetApp Bug ID	|Title	|Description	|Bugzilla ID
|1508554   	|NetApp Linux Host Utilities CLI requires additional library package dependencies to support Emulex host bus adapter (HBA) adapter discovery	|In RHEL 9.x, the NetApp Linux SAN host utilities CLI `sanlun fcp show adapter -v` fails because the library package dependencies to support host bus adapter (HBA) discovery cannot be found. |Not applicable
|===

