---
sidebar: sidebar
permalink: hu_rhel_91.html
keywords: host utilities, red hat, rhel, linux, 9.1, netapp, ontap, rhel 
summary: Describes how to use Red Hat Enterprise Linux 9.1 with ONTAP
---

= Using Red Hat Enterprise Linux 9.1 with NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Install the Linux Unified Host Utilities

The NetApp Linux Unified Host Utilities software package is available on the NetApp Support Site in a 32-bit and 64-bit .rpm file. If you do not know which file is required for your configuration, use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify which one you need.
Installing the Linux Unified Host Utilities is strongly recommended, but not mandatory. The utilities do not change any settings on your Linux host. The utilities improve management and assist NetApp customer support in gathering information about your configuration.


include::_include/hu/reuse_hu_cloud_note.adoc[]

.What you'll need
If you have a version of Linux Unified Host Utilities currently installed, you should upgrade  or remove it and use the following steps to install the latest version.

. Download the 32-bit or 64-bit Linux Unified Host Utilities software package from the NetApp Support Site to your host.
. Use the following command to install the software package:
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64

== SAN Toolkit

include::_include/hu/reuse_hu_san_toolkit.adoc[]

== SAN Booting

.What you'll need
If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For Red Hat Enterprise Linux (RHEL) 9.1 the `/etc/multipath.conf` file must exist, but you do not need to make specific changes to the file. RHEL 9.1 is compiled with all settings required to recognize and correctly manage ONTAP LUNs.

include::_include/hu/reuse_hu_multipathing.adoc[]

include::_include/hu/reuse_hu_asa_configuration.adoc[]

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running

----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running

----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

== Recommended Settings

The RHEL 9.1 OS is compiled to recognize ONTAP LUNs and automatically set all configuration parameters correctly for both ASA and non-ASA configuration.

include::_include/hu/reuse_hu_recommended_settings.adoc[]

[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because of other SAN arrays still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----

include::_include/hu/reuse_hu_kvm_configuration.adoc[]

== Known Problems and Limitations

[options="header", cols="20, 20, 50,20"]
|===
|NetApp Bug ID	|Title	|Description	|Bugzilla ID
|1503468	|The nvme list-subsys operation/p printsing all paths together instead of 4 live paths	|In RHEL 9.1, the  "nvme list-subsys" command output is supposed to display 4 live paths only (per the amount  of LIFs configured on the target ). However, all paths are listed together for each device in the output for the total number of namespaces mapped. This issue occurs on all RHEL 9.1 NVMe configured hosts.
.|2130106
|1504250	|Intermittent NVMe/TCP I/Oio queue disruptiontear down during ONTAP storage failover (SFO) events.	|In RHEL 9.1, ONTAP SFO regression run by using the CM_Cluster_SFO_combined.thpl script causes intermittent NVMe/TCP I/O queue disruption during ONTAP SFO events.
The host attempts to reconnect the failed nvmeX controller every 10 seconds from the time the takeover is initiated until the giveback operation enables the reconnection to succeed. However, queue disruption breaks the reconnect attempts. 
Host multipath path validation fails after the giveback operation, and the nvmeX controller enters a “resetting” state. The state of the nvmeX controller remains static and does not recover until the host is rebooted. The host reconnects to the failed nmeX multipath controller during the giveback phase of a planned or unplanned SFO event. The host multipath validation succeeds after two takeover operations and four giveback operations are complete. |2134548
|1502137	|dev_loss_tmo value for FC devices gives -1 instead of infinite value	|In RHEL 9.1,  during multipathd parameter verification, the  correct  dev_loss_tmo value is  'infinity'.
However,  a different value, '-1' under /sysfs is displayed.
The multipathd show config command correctly displays  infinity.|2126324
|1508554   	|sanlun installation fails to pick libraries required for loading HBA info	|In RHEL 9.1 , the sanlun command does not work on hosts with Emulex HBA(Lpe36002,LPe32002 & Lpe35002)after installing the latest Emulex HBA CLI utility package "elxocmcore-rhel7-rhel8-rhel9-14.0.505.26-1" from the vendor site.

When the following command is run  onthe host, the following error occurs. .
[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library

Make sure the library installation package is correctly installed & loaded.
|N/A
|===

== Release Notes

include::_include/hu/reuse_hu_release_notes.adoc[]
