---
sidebar: sidebar
permalink: hu_rhel_87.html
keywords: host utilities, red hat, rhel, linux, 8.7, netapp, ontap
summary: Describes how to use Red Hat Enterprise Linux 8.7 with ONTAP
---

= Using Red Hat Enterprise Linux 8.7 with NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Install the Linux Unified Host Utilities

include::_include/hu/reuse_hu_installing_luhu_without32.adoc[]

include::_include/hu/reuse_hu_cloud_note.adoc[]

== SAN Toolkit

include::_include/hu/reuse_hu_san_toolkit.adoc[]

== SAN Booting

.What you'll need
If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For Red Hat Enterprise Linux (RHEL) 8.7 the `/etc/multipath.conf` file must exist, but you do not need to make specific changes to the file. RHEL 8.6 is compiled with all settings required to recognize and correctly manage ONTAP LUNs.

include::_include/hu/reuse_hu_multipathing.adoc[]

include::_include/hu/reuse_hu_asa_configuration.adoc[]

----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

== Recommended Settings

The RHEL 8.7 OS is compiled to recognize ONTAP LUNs and automatically set all configuration parameters correctly for both ASA and non-ASA configuration.

include::_include/hu/reuse_hu_recommended_settings.adoc[]

[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because of other SAN arrays still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----

include::_include/hu/reuse_hu_kvm_configuration.adoc[]

== Known Problems and Limitations

[cols="10,30,30,10",options="header"]
|===
|NetApp Bug ID	|Title	|Description	|Bugzilla ID
|1497900	|iSCSI sanboot OS installation fails while installing boot loader with an error `Failed to write boot loader configuration` on OCe14102-UX system
|OS installation fails for iSCSI with RHEL 8.7 in step installing boot loader.
Installation gives the error "The following error occured while installing boot loader .The system will not be bootable.Would you like to ignore this and continue with installation?failed to write boot loader configuration". This is observed in both BIOS and UEFI boot modes.
|2119771
|1479047	|Duplicate persistent discovery controllers created with `nvme discover -p` option	|NVMe Persistent Discovery Controllers (PDCs) can be created by appending the `-p` option to the `nvme discover` command. Multiple invocations of the same command should still end up with utmost one PDC itself for a given initiator-target combination. But certain hosts are known to create duplicate PDCs for this same case above, leading to wastage of resources on both the host and the target.	|2087000
|1501048	|sysfs filesystem returns SCSI-FC dev_loss_tmo value of -1 instead of infinity	|As part of multipathd parameters verification,the value of dev_loss_tmo is supposed to be `infinity` but sysfs filesystem returns SCSI-FC dev_loss_tmo value of -1 in RHEL 8.7. However, multipathd -k"show config"  returns dev_loss_tmo as "infinity"[look for NetApp Device specific dev_loss_tmo parameter value]. We don't seem to find any broken dev_loss_tmo functionality here. It could be the reporting issue by the sysfs filesystem.	|2124297  



== Release Notes

include::_include/hu/reuse_hu_release_notes.adoc[]
