---
sidebar: sidebar
permalink: hu_solaris_62.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Linux Unified Host Utilities 7.1 with ONTAP
---

= Solaris Host Utilities 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/



== Pre-requisites

.What you'll need

* For reliable operation, you must verify that your entire iSCSI,FC or FCoE configuration is supported.

You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify your configuration.

== SAN Toolkit

Solaris Host Utilities is a NetApp host software that provides a command line toolkit on your Oracle Solaris host. The toolkit is installed when you install the NetApp Host Utilities package. This kit provides the sanlun utility, which helps you manage LUNs and HBAs. The `sanlun` command returns information about the LUNs mapped to your host, multipathing, and information necessary to create initiator groups.

.Example

In the following example, the `sanlun lun show` command returns the LUN information.
----
data_vserver     /vol/vol1/lun1     /dev/rdsk/c0t600A098038304437522B4E694E49792Dd0s2 qlc3       FCP        10g     cDOT
data_vserver     /vol/vol0/lun2     /dev/rdsk/c0t600A098038304437522B4E694E497938d0s2 qlc3       FCP        10g     cDOT
data_vserver     /vol/vol2/lun3     /dev/rdsk/c0t600A098038304437522B4E694E497939d0s2 qlc3       FCP        10g     cDOT
data_vserver     /vol/vol3/lun4     /dev/rdsk/c0t600A098038304437522B4E694E497941d0s2 qlc3       FCP        10g     cDOT
----

There are This toolkit is common across all configurations and protocols of the Host Utilities. As a result, some of its contents apply to one configuration, but not another. Having unused components does not affect your system performance.

== Installing Solaris Host Utilities

The Solaris Host Utilities 6.2 supports several Solaris environments and multiple protocols. The primary Host Utilities environments are:

* Native OS with MPxIO with either the Fibre Channel (FC) or iSCSI protocol on a system using either a SPARC processor or an x86/64 processor.

*	Veritas Dynamic Multipathing (DMP) with either the FC or iSCSI protocol on a system using a SPARC processor and with the iSCSI protocol on system using an x86/64 processor.

The NetApp Solaris Host Utilities software package is available on the link:https://mysupport.netapp.com/site/[NetApp Support Site^] in a compressed  file format for your processor. You can download the Host Utilities software package for your environment from the Support site.

.Steps

.	Login to your host as root.
.	Download a copy of the compressed file containing the Host Utilities from NetApp Support Site to a directory on your host.
+
At the time this documentation was prepared, the compressed files were called:
+
* SPARC CPU: netapp_solaris_host_utilities_6_2_sparc.tar.gz
* x86/x64 CPU: netapp_solaris_host_utilities_6_2_amd.tar.gz

.	Go to the directory containing the download.
.	Unzip the file using the gunzip command
+
`# gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz`

.	Untar the file. You can use the tar xvf command to do this.
+
`# tar xvf netapp_solaris_host_utilities_6_2_sparc.tar`

.	Add the packages that you extracted from tar file to your host. You can use the ``pkgadd command to do this.
+
The packages are added to the `/opt/NTAP/SANToolkit/bin` directory. The following example uses the pkgadd command to install the Solaris installation package:
+
`# pkgadd -d ./NTAPSANTool.pkg`

.	Confirm that the toolkit was successfully installed by using the `pkginfo` command or the `ls - al` command.

. After you finish, you must configure the host parameters for your environment using `/opt/NTAP/SANToolkit/bin/host_config` command
+
** MPxIO
**	Veritas DMP

.	Install the SAN Toolkit:

.	Verify the installation:
+
`sanlun version`

== Sample command reference
=== List all host initiators mapped to host

----
# sanlun fcp show adapter -v
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


=== List all LUNs mapped to host

----
# sanlun lun show -p -v all

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----

=== List all LUNs mapped to host from a given SVM/ List all attributes of a given LUN mapped to host

----
# sanlun lun show -p -v sanboot_unix`
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----

=== List ONTAP LUN attributes by Host Device File name

----
# controller(7mode/E-Series)/                                         device                                            host                  lun
vserver(cDOT/FlashRay)        lun-pathname                          filename                                          adapter    protocol   size    product
--------------------------------------------------------------------------------------------------------------------------------------------------------
sanboot_unix                  /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2 qlc3       FCP        180.0g  cDOT
----
