---
sidebar: sidebar
permalink: hu_sles_15SP6.html
keywords: host utilities, suse linux enterprise server 15 sp6, suse, linux, 15 sp6, netapp, ontap, fcp, iscsi
summary: use the ONTAP SAN host configuration settings to configure the SUSE Linux Enterprise Server 15 SP6 host with the FCP and iSCSI protocols for operation with ONTAP LUNs.
---
= Configure SUSE Linux Enterprise Server 15 SP6 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure the SUSE Linux Enterprise Server 15 SP6 host with the FCP and iSCSI protocols for operation with ONTAP LUNs.   

== Install the Linux Host Utilities

include::_include/hu/install-linux-host-utilities.adoc[]

== Enable SAN booting
include::_include/hu/enable-san-boot-linux.adoc[]

== Multipathing

You can use multipathing with SUSE Linux Enterprise Server 15 SP6 to manage ONTAP LUNs. 

include::_include/hu/multipathing.adoc[]


=== Use multipathing to optimize performance
You can use the `multipath.conf` file to optimize the performance of your host configuration.

.Exclude a device from multipath

If you want to exclude a device from multipath, you can add the WWID for the unwanted device to the "blacklist" for the `multipath.conf` file using the following device stanza:

----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----

The following example determines a WWID and adds it to a "blacklist" stanza.

.Steps
. Determine the WWID:
+
`# /lib/udev/scsi_id -gud /dev/sda`
+
`360030057024d0730239134810c0cb833`
+
"sda" is the local SCSI disk that you want to add it to the blacklist.

. Add the WWID to the "blacklist" stanza in `/etc/multipath.conf`:
+
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----


.Recommended settings for ONTAP LUNs
You should always check your `/etc/multipath.conf` file, especially in the defaults section, for legacy settings that might be overriding the default settings. 

The following table shows the critical multipathd parameters for ONTAP LUNs. These parameters are compiled with native device mapper multipath libraries. If a host is connected to LUNs from other vendors and any of these parameters are overridden, you need to correct them by using stanzas later in the multipath.conf file that apply specifically to ONTAP LUNs. If you don't do this, the ONTAP LUNs might not work as expected. You should only override these default settings in consultation with NetApp support, an OS vendor, or both, and only when the impact is fully understood.

[cols=2]
[options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

The following example shows how to correct an overriden default setting in a `multipath.conf` file that defines values for `path_checker` and `no_path_retry` that aren't compatible with ONTAP LUNs. In this case, you cannot remove these parameters because SAN arrays are attached to the host. Instead, you can correct the values to "queue" and "tur" by adding a device stanza to the `multipath.conf` file that applies specifically to the ONTAP LUNs.

[subs=+quotes]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----



=== Examples of all ASA and non-ASA configurations
include::_include/hu/asa-configuration-intro-and-all-asa-example.adoc[]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----

include::_include/hu/non-asa-configuration-example.adoc[]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----

== Known issues

There are no known issues for the SUSE Linux Enterprise Server 15 SP6 with ONTAP release.