---
sidebar: sidebar
permalink: hu_sles_15SP2.html
keywords: host utilities, suse linux enterprise server 15 sp2, suse, linux, 15 sp2, netapp, ontap
summary: Install the Linux Host Utilities on a SUSE Linux Enterprise Server 15 SP2 to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure SUSE Linux Enterprise Server 15 SP2 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a SUSE Linux Enterprise Server 15 SP2 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 2: Confirm the multipath configuration for your host

You can use multipathing with SUSE Linux Enterprise Server 15 SP2 to manage ONTAP LUNs.

include::_include/hu/multipathing.adoc[]

include::_include/hu/enable-san-boot-linux.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/customize-parameters.adoc[]

== Step 6: Review the known issues

The SUSE Linux Enterprise Server 15 SP2 with ONTAP release has the following known issues:

[cols="1,3,3"]
[options="header"]
|===
| NetApp Bug ID
| Title
| Description

| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1308744[1308744^]

| iSCSI boot from SAN fails to boot with a static IP configuration after completing an SUSE Linux Enterprise Server 15S P2 OS installation

a| iSCSI sanbooted LUN failed to boot up after completing an SUSE Linux Enterprise Server 15 SP2 OS installation with a static IP configuration. Bootup failure occurs every time with the static IP configuration. This leads to the server refusing to continue the boot up process with the following error message:

----
dracut-cmdline[241]: warning: Empty autoconf values default to dhcp

dracut: FATAL: FATAL: For argument ip=eth4:static, setting client-ip does not make sense for dhcp

dracut: Refusing to continue

reboot: System halted

----

|===

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]

// 2024 SEP 2, ONTAPDOC-2345