---
sidebar: sidebar
permalink: hu_sles_15SP6.html
keywords: host utilities, suse linux enterprise server 15 sp6, suse, linux, 15 sp6, netapp, ontap, fcp, iscsi
summary: Use the ONTAP SAN host configuration settings to configure the SUSE Linux Enterprise Server 15 SP6 host with the FCP and iSCSI protocols for operation with ONTAP LUNs.
---
= Configure SUSE Linux Enterprise Server 15 SP6 with FCP and iSCSI for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a SUSE Linux Enterprise Server 15 SP6 host, it supports managing FCP and iSCSI protocol operations with ONTAP LUNs. NetApp strongly recommends installing the Linux Host Utilities to support ONTAP LUN management and assist technical support with gathering configuration data.

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 2: Confirm the multipath configuration for your host

You can use multipathing with SUSE Linux Enterprise Server 15 SP6 to manage ONTAP LUNs.

include::_include/hu/multipathing.adoc[]

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/enable-san-boot-linux.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/customize-parameters.adoc[]

include::_include/hu/hu-asm-mirroring.adoc[]

== Known issues

There are no known issues for the SUSE Linux Enterprise Server 15 SP6 with ONTAP release.