---
sidebar: sidebar
permalink: hu_sles_15.html
keywords: host utilities, suse linux enterprise server 15, suse, linux, 15, netapp, ontap
summary: Install the Linux Host Utilities on a SUSE Linux Enterprise Server 15 to manage FCP and iSCSI protocol operations with ONTAP LUNs.
---
= Configure SUSE Linux Enterprise Server 15 for FCP and iSCSI with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Linux Host Utilities software provides management and diagnostic tools for Linux hosts that are connected to ONTAP storage. When you install the Linux Host Utilities on a SUSE Linux Enterprise Server 15 host, you can use the Host Utilities to help you manage FCP and iSCSI protocol operations with ONTAP LUNs.

include::_include/hu/linux-enable-san-boot.adoc[]

include::_include/hu/install-linux-host-utilities.adoc[]

== Step 3: Confirm the multipath configuration for your host

You can use multipathing with SUSE Linux Enterprise Server 15 to manage ONTAP LUNs.

include::_include/hu/multipathing.adoc[]

include::_include/hu/exclude-device.adoc[]

include::_include/hu/linux-customize-parameters.adoc[]

== Step 6: Review the known issues

The SUSE Linux Enterprise Server 15 with ONTAP storage release has the following known issue:

[cols=3*,options="header"]
|===
| NetApp Bug ID
| Title
| Description
| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1154309[1154309^] | SLES 15 host with more than 20 mapped LUNs might go into maintenance mode after a reboot | SLES 15 host with more than 20 mapped LUNs might go into maintenance mode after a reboot. The maintenance mode becomes single user mode following the message:
`Give root password for maintenance (or press Control-D to continue)`
|===

== What's next?

include::_include/hu/use-linux-host-utilities.adoc[]

include::_include/hu/asm-mirroring.adoc[]

// 2024 SEP 2, ONTAPDOC-2345