---
sidebar: sidebar
permalink: hu_sles_15SP5.html
keywords: host utilities, suse linux enterprise server 15 sp5, suse, linux, 15 sp5, netapp, ontap
summary: Describes how to use SUSE Linux Enterprise Server 15 SP5 with ONTAP
---

= Using SUSE Linux Enterprise Server 15 SP5 with NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Installing the Linux Unified Host Utilities

include::_include/hu/reuse_hu_installing_luhu_with32.adoc[]

include::_include/hu/reuse_hu_cloud_note.adoc[]

== SAN Toolkit

include::_include/hu/reuse_hu_san_toolkit.adoc[]

== SAN Booting

.What you'll need
If you decide to use SAN booting, it must be supported by your configuration. You can use the link:https://mysupport.netapp.com/matrix/imt.jsp?components=84067;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For SUSE Linux Enterprise Server 15 SP5 the `/etc/multipath.conf` file must exist, but you do not need to make specific changes to the file. SUSE Linux Enterprise Server 15 SP5 is compiled with all settings required to recognize and correctly manage ONTAP LUNs.

include::_include/hu/reuse_hu_multipathing.adoc[]

include::_include/hu/reuse_hu_asa_configuration.adoc[]

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

== Recommended Settings

SUSE Linux Enterprise Server 15 SP5 OS is compiled to recognize ONTAP LUNs and automatically set all configuration parameters correctly for both ASA and non-ASA configurations. You can further optimize performance for your host configuration with the following recommended settings.

include::_include/hu/reuse_hu_recommended_settings.adoc[]



[cols=2]
[options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because of other SAN arrays still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}
devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----

== Known issues

The SUSE Linux Enterprise Server 15 SP5 with NetApp ONTAP release has the following known issues:

[options="header", cols="20, 20, 50,20"]
|===
|NetApp Bug ID	|Title	|Description	|Bugzilla ID
|1532179   	|LVM hung tasks with SAN Boot host after issuing NetApp giveback With Sles15SP5 SAN Boot host,	|Kernel disruption occurs when LVM hung tasks are seen with sanbooted Emulex HBA after storage failover giveback operation on a Sles15SP5. The kernel disruption causes the operating system to reboot and generates the vmcore file under the /var/crash/directory if kdump is configured |1208410
|===

== Release Notes

include::_include/hu/reuse_hu_release_notes.adoc[]
