---
sidebar: sidebar
permalink: hu_solaris_62.html
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap
summary: Describes how to use the Solaris Host Utilities 6.2 with ONTAP
---
= Install Solaris Host Utilities 6.2 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Solaris Host Utilities help you manage ONTAP storage attached to a Solaris host and assist technical support with gathering configuration data.

The Solaris Host Utilities support several Solaris environments and multiple transport protocols. These are the primary Solaris Host Utilities environments: 

* The native OS with MPxIO and either the Fibre Channel (FC) or iSCSI protocol on a system using either a SPARC processor or an x86/64 processor.
* Veritas Dynamic Multipathing (DMP) with either the FC or iSCSI protocol on a system using a SPARC processor, or the iSCSI protocol on a system using an x86/64 processor.

The Solaris Host Utilities 6.2 support the following Solaris series:

* Solaris 11.x
* Solaris 10.x

.Before you begin

Verify that your iSCSI, FC, or FCoE configuration is supported. You can use the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify your configuration.

.Steps

. Log in to your host as root.

. Download a copy of the compressed file containing the Host Utilities from the link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads[NetApp Support Site^] to a directory on your Solaris host:
+
[role="tabbed-block"]
====
.SPARC CPU 
--
[source,cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.x86/x64 CPU 
--
[source,cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. Go to the directory on your Solaris host containing the download.

. Unzip the file using the `gunzip` command:
+
[source,cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----

. Extract the file using the `tar xvf` command:
+
[source,cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----

. Add the packages that you extracted from tar file to your host
+
[source,cli]
----
pkgadd
----
+
The packages are added to the `/opt/NTAP/SANToolkit/bin` directory. 
+
The following example uses the `pkgadd` command to install the Solaris installation package:
+
[source,cli]
----
pkgadd -d ./NTAPSANTool.pkg
----

. Confirm that the toolkit was successfully installed by using one of the following commands:
+
[source,cli]
----
pkginfo
----
+
[source,cli]
----
ls - al
----
+
.Show example outputs
[%collapsible]
====
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====

. Configure the host parameters for your MPxIO or Veritas DMP environment:
+
[source,cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----

. Verify the installation:
+
[source,cli]
----
sanlun version
----

include::_include/hu/solaris-install-whats-next.adoc[]



