---
sidebar: sidebar
permalink: hu_sanhost_index.html
keywords: san, host, utility, software, netapp
summary: Learn about the latest information on SAN Host Utility releases and access the installation procedure for your host configuration. 
---
= Learn about SAN Host Utilities
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn about the latest information on SAN Host Utility releases and access the installation procedure for your host configuration. 

There are several SAN Host Utilities software packages available on the NetApp Support site. NetApp recommends using the SAN Host Utilities software if it's available for your SAN host.

The AIX, HP-UX, Linux, and Solaris Host Utilities software provide a command line toolkit. The toolkit helps you manage ONTAP LUNs and host bus adapters (HBAs). NetApp customer support can also use the SAN Host Utilities to gather information about your configuration if you have an issue that requires assistance. The toolkit is automatically installed when you install the Host Utilities software package. 

The Windows Host Utilities enable you to connect a Windows host computer to NetApp storage systems. The software includes an installation program that sets the required Windows registry and HBA parameters. This enables the Windows host to correctly handle the storage system behaviors for ONTAP and E-Series platforms.

NOTE: For reliable operation after installation, use the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] to verify that your host supports the complete NVMe over Fabrics (including NVMe over TCP and NVMe over Fibre Channel), iSCSI, FC, or FCoE configuration.