---
sidebar: sidebar
permalink: hu_sles_15SP6.html
keywords: host utilities, suse linux enterprise server 15 sp6, suse, linux, 15 sp6, netapp, ontap
summary: Describes how to use SUSE Linux Enterprise Server 15 SP6 with ONTAP
---
= Use SUSE Linux Enterprise Server 15 SP6 with ONTAP
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure SUSE Linux Enterprise Server 15 SP6 with ONTAP as the target. 

== Install the Linux Unified Host Utilities

include::_include/hu/reuse_hu_installing_luhu_with32.adoc[]

include::_include/hu/reuse_hu_cloud_note.adoc[]

== SAN toolkit

include::_include/hu/reuse_hu_san_toolkit.adoc[]

== SAN booting

.What you'll need
Your configuration supports SAN booting. See the link:https://mysupport.netapp.com/matrix/imt.jsp?components=84067;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For SUSE Linux Enterprise Server 15 SP6, the `/etc/multipath.conf` file must exist. You don't need to make changes to this file because SUSE Linux Enterprise Server 15 SP6 is compiled with all the settings required to recognize and correctly manage ONTAP LUNs.

include::_include/hu/reuse_hu_multipathing.adoc[]

include::_include/hu/reuse_hu_asa_configuration.adoc[]

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

include::_include/hu/reuse_hu_non_asa_configuration.adoc[]

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

== Recommended settings

The SUSE Linux Enterprise Server 15 SP6 OS is compiled to recognize ONTAP LUNs and automatically set all configuration parameters correctly for both ASA and non-ASA configurations. You can further optimize performance for your host configuration with the following recommended settings.

include::_include/hu/reuse_hu_recommended_settings.adoc[]



[cols=2]
[options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because of other SAN arrays still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}
devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----

== Known issues

There are no known issues for the SUSE Linux Enterprise Server 15 SP6 with ONTAP release.


