---
sidebar: sidebar
permalink: hu_sles_15SP6.html
keywords: host utilities, suse linux enterprise server 15 sp6, suse, linux, 15 sp6, netapp, ontap, fcp, iscsi
summary: use the ONTAP SAN host configuration settings to configure the SUSE Linux Enterprise Server 15 SP6 host with the FCP and iSCSI protocols for operation with ONTAP LUNs.
---
= Configure SUSE Linux Enterprise Server 15 SP6 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure the SUSE Linux Enterprise Server 15 SP6 host with the FCP and iSCSI protocols for operation with ONTAP LUNs.   

== Install the Linux Host Utilities

include::_include/hu/install-linux-host-utilities.adoc[]

== Enable SAN booting
include::_include/hu/enable-san-boot-linux.adoc[]

== Multipathing

You can use multipathing with SUSE Linux Enterprise Server 15 SP6 to manage ONTAP LUNs. 

To use multipathing, the `/etc/multipath.conf file` must exist. If the `/etc/multipath.conf` file doesn't exist, you can create an empty, zero-byte file by using the `touch /etc/multipath.conf` command. You don't need to make changes to the `/etc/multipath.conf` zero-byte file because SUSE Linux Enterprise Server 15 SP6 is compiled with the settings (recommended settings) required to recognize and correctly manage ONTAP LUNs. 

SUSE Linux Enterprise Server 15 SP6 also configures the parameters for all SAN Array (ASA) and non-ASA configurations.

include::_include/hu/configure-multipathing-and-optimize-performance-intro.adoc[]

* <<restore-default-setting-slessp15sp6,Restore default settings for ONTAP LUNs>>

[[exclude-devices]]

include::_include/hu/blacklist-devices.adoc[]

[[restore-default-setting-slessp15sp6]]
include::_include/hu/restore-default-settings.adoc[]

=== Examples of all ASA and non-ASA configurations
include::_include/hu/asa-configuration-intro-and-all-asa-example.adoc[]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----

include::_include/hu/non-asa-configuration-example.adoc[]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----

== Known issues

There are no known issues for the SUSE Linux Enterprise Server 15 SP6 with ONTAP release.