---
sidebar: sidebar
permalink: hu_wuhu_hba_settings.html
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform
summary: Windows Host Utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for ONTAP and E-Series platforms.
---
= Configure registry settings for Windows Host Utilities with ONTAP storage
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Windows Host Utilities require certain registry and parameter settings to verify that the Windows host correctly handles the storage system behavior.

The Windows Host Utilities sets parameter values that affect how a Windows host responds to a delay or loss of data. These values verify that a Windows host correctly handles events such as a controller failover.

Some values don't apply to the device-specific module (DSM) for SANtricity Storage Manager. Overlap between values set by the Windows Host Utilities and the DSM for SANtricity Storage Manager don't result in conflicts.

You also need to set FC, NVMe/FC, and iSCSI HBAs parameters to optimize performance and successfully handle storage system events.

Beginning with Windows Host Utilities 8.0, the installer sets the Windows, FC, iSCSI, and NVMe/FC HBA parameters to the supported values for the Windows Host. For Windows Host Utilities 7.2 and 7.1, you need to manually set the iSCSI HBA parameters.

The installer sets different values when you specify Microsoft Multipath I/O (MPIO) support during the installation.

[NOTE]
====
You need to change the LimTransferSize parameter value after installing Windows Host Utilities 7.2. See <<nvme_parameter,NVME parameters>>.

For all other parameters and registry keys for Windows Host Utilities 8.0, 7.2, or 7.1, you don't need to change the values unless technical support advises you to do so.
====

== Registry values set by Windows Host Utilities 8.0

The Windows Host Utilities installer automatically sets the Windows registry values, iSCSI HBA parameters, and NVMe parameters based on the choices that you make during the installation. You need to review these values and the operating system version. 

[role="tabbed-block"]
====
.Windows registry values
--
All values are in decimal unless otherwise stated.

NOTE: HKLM is the abbreviation for `HKEY_LOCAL_MACHINE`.

[cols=3*,options="header", cols="20,20,30"]
|===
|Registry key |Value |When set

|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters
\DsmMaximumRetryTimeDuringStateTransition
|120
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, or 2016
|HKLM\SYSTEM\CurrentControlSet
\Services\msdsm\Parameters
\DsmMaximumStateTransitionTime
|120
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, or 2016
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\DsmSupportedDeviceList
|"NETAPP LUN", "NETAPP LUN C-
Mode"
"NVMe NetApp ONTAP Con"
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\ClusDisk \Parameters\ManageDisksOnSystemBuses
|1
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \MaxRequestHoldTime
|30
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\MPDEV\MPIOSupportedDeviceList
|"NETAPP LUN",
"NETAPP LUN C-
Mode",
"NVMe NetApp ONTAP Con"
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathRecoveryInterval
|30
|When your server is Windows Server 2025, 2022, 2019, or 2016
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathVerifyEnabled
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\PathVerifyEnabled
|1
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, or 2016
|HKLM\SYSTEM\CurrentControlSet\Services
\mpio\Parameters\PDORemovePeriod
|130
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified and your server is  Windows Server 2025, 2022, 2019, or 2016
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\RetryCount
|6
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryCount
|6
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, or 2016
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\RetryInterval
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryInterval
|1
|When MPIO support is specified and your server is  Windows Server 2025, 2022, 2019, or 2016
1.2+|HKLM\SYSTEM\CurrentControlSet
\Services\disk\TimeOutValue |120 |When no MPIO support is selected 
|60 
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\UseCustomPathRecoveryInterval
|1
|When MPIO support is specified and your server is  Windows Server 2025, 2022, 2019, or 2016
|===
--

.iSCSI HBA values
--
All values are in decimal unless otherwise stated.

NOTE: HKLM is the abbreviation for `HKEY_LOCAL_MACHINE`.

[cols=3*,options="header", cols="20,20,30"]
|===
|Registry key |Value |When set
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \IPSecConfigTimeout
|60
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \LinkDownTime
|10
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \MaxRequestHoldTime
|120
|When no MPIO support is selected
|===
--

.NVMe parameters
--

Windows Host Utilities 8.0 updates the following NVMe Emulex driver parameters during installation:

* EnableNVMe = 1
* NVMEMode = 0

--
====

== Registry values set by Windows Host Utilities 7.2

The Windows Host Utilities installer automatically sets registry values and NVMe parameters based on the choices that you make during the installation. You need to review these values and the operating system version. 

[[nvme_parameter]]

[role="tabbed-block"]
====

.HKLM values
--
The Windows Host Utilities installer sets the following registry values. All values are in decimal unless otherwise stated.
[NOTE]
HKLM is the abbreviation for `HKEY_LOCAL_MACHINE`.

[cols=3*,options="header", cols="20,20,30"]
|===
|Registry key |Value |When set

|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters
\DsmMaximumRetryTimeDuringStateTransition
|120
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet
\Services\msdsm\Parameters
\DsmMaximumStateTransitionTime
|120
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\DsmSupportedDeviceList
|"NETAPP LUN", "NETAPP LUN C-
Mode"
"NVMe NetApp ONTAP Con"
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \IPSecConfigTimeout
|60
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \LinkDownTime
|10
|Always
|HKLM\SYSTEM\CurrentControlSet\Services
\ClusDisk \Parameters\ManageDisksOnSystemBuses
|1
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \MaxRequestHoldTime
|120
|When no MPIO support is selected
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \MaxRequestHoldTime
|30
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\MPDEV\MPIOSupportedDeviceList
|"NETAPP LUN",
"NETAPP LUN C-
Mode",
"NVMe NetApp ONTAP Con"
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathRecoveryInterval
|30
|When your server is Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathVerifyEnabled
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\PathVerifyEnabled
|1
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet\Services
\vnetapp\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\mpio\Parameters\PDORemovePeriod
|130
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified and your server is  Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet\Services\vnetapp
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\RetryCount
|6
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryCount
|6
|When MPIO support is specified and your server is Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\RetryInterval
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryInterval
|1
|When MPIO support is specified and your server is  Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|HKLM\SYSTEM\CurrentControlSet\Services\vnetapp
\Parameters\RetryInterval
|1
|When MPIO support is specified
1.2+|HKLM\SYSTEM\CurrentControlSet
\Services\disk\TimeOutValue |120 |When no MPIO support is selected |60 |When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\UseCustomPathRecoveryInterval
|1
|When MPIO support is specified and your server is  Windows Server 2025, 2022, 2019, 2016, or 2012 R2
|===
--

.NVMe parameters
--

Windows Host Utilities 7.2 updates the following NVMe Emulex driver parameters during installation

* EnableNVMe = 1
* NVMEMode = 0
* LimTransferSize=1
+
The LimTransferSize parameter is automatically set to "1" when you install Windows Host Utilities 7.2. After installation, you change the LimTransferSize value to "0" and reboot the server.
--
====

== Registry values set by Windows Host Utilities 7.1

The Windows Host Utilities installer automatically sets registry values based on the choices that you make during installation. You need to review these registry values and the operating system version.

The Windows Host Utilities installer sets the following values. All values are in decimal unless otherwise noted. 

[NOTE]
`HKLM` is the abbreviation for `HKEY_LOCAL_MACHINE`.

[options="header", cols= "~, 10, ~"]
|===
|Registry key |Value |When set
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters
\DsmMaximumRetryTimeDuringStateTransition
|120 |When MPIO support is specified and your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters
\DsmMaximumStateTransitionTime
|120 |When MPIO support is specified and your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008, except if Data ONTAP DSM is detected
1.2+|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\DsmSupportedDeviceList
|"NETAPPLUN" |When MPIO support is specified
|"NETAPP LUN", "NETAPP LUN C-Mode" |When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Control\Class
\{iSCSI_driver_GUID}\ instance_ID\Parameters
\IPSecConfigTimeout
|60
|Always, except when Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\{iSCSI_driver_GUID}
\ instance_ID\Parameters\LinkDownTime
|10
|Always
|HKLM\SYSTEM\CurrentControlSet\Services\ClusDisk
\Parameters\ManageDisksOnSystemBuses
|1|Always, except when Data ONTAP DSM is detected
1.2+|HKLM\SYSTEM\CurrentControlSet\Control
\Class\{iSCSI_driver_GUID}
\ instance_ID\Parameters\MaxRequestHoldTime
|120
|When no MPIO support is selected
|30
|Always, except when Data ONTAP DSM is detected
1.2+|HKLM\SYSTEM\CurrentControlSet
\Control\MPDEV\MPIOSupportedDeviceList
|"NETAPP LUN"
|When MPIO support is specified
|"NETAPP LUN", "NETAPP LUN C-Mode"
|When MPIO is support-specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathRecoveryInterval
|40
|When your server is Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2, or Windows Server 2016 only
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified and your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\msiscdsm\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified and your server is Windows Server 2003, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\vnetapp
\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified and your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\msiscdsm
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified and your server is Windows Server 2003, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\vnetapp \Parameters\PDORemovePeriod
|130
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\mpio\Parameters\RetryCount
|6
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryCount
|6
|When MPIO support is specified and your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\msiscdsm\Parameters\RetryCount
|6
|When MPIO support is specified and your server is Windows Server 2003, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\vnetapp\Parameters\RetryCount
|6
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\mpio\Parameters\RetryInterval
|1
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\RetryInterval
|1
|When MPIO support is specified and your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services
\vnetapp\Parameters\RetryInterval |1 |When MPIO support is specified, except if Data ONTAP DSM is detected
1.2+|HKLM\SYSTEM\CurrentControlSet
\Services\disk\TimeOutValue |120 |When no MPIO support is selected |60 |When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\UseCustomPathRecoveryInterval
|1
|When your server is Windows Server 2016, 2012 R2, 2012, 2008 R2, or 2008 
|===

See the https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/windows-registry-advanced-users[Microsoft documents^] for the registry parameter details.

== FC HBA values set by Windows Host Utilities

The Windows Host Utilities installer sets the required timeout values for Emulex and QLogic FC HBAs on systems using FC. 

The installer sets the following parameters for Emulex FC HBAs:

[role="tabbed-block"]
====

.When you select MPIO
--
|===
|Property type |Property value

|LinkTimeOut
|1
|NodeTimeOut
|10
|===
--

.When you don't select MPIO
--

|===
|Property type |Property value

|LinkTimeOut
|30
|NodeTimeOut
|120
|===
--
====

The installer sets the following parameters for QLogic FC HBAs:

[role="tabbed-block"]
====
.When you select MPIO
--
|===
|Property type |Property value

|LinkDownTimeOut
|1
|PortDownRetryCount
|10
|===
--

.When you don't select MPIO
--

|===
|Property type |Property value

|LinkDownTimeOut
|30
|PortDownRetryCount
|120
|===
--
====

[NOTE]
The names of the parameters might vary slightly depending on the program. For example, in the QLogic QConvergeConsole program, the parameter is displayed as `Link Down Timeout`. The Host Utilities `fcconfig.ini` file displays this parameter as either `LinkDownTimeOut` or `MpioLinkDownTimeOut`, depending on whether MPIO is specified. However, all of these names refer to the same HBA parameter. See https://www.broadcom.com/support/download-search[Emulex^] or https://driverdownloads.qlogic.com/QLogicDriverDownloads_UI/Netapp_search.aspx[QLogic^] to learn more about the timeout parameters.


== Learn about the Host Utilities changes to FC HBA driver settings

During installation of the required Emulex or QLogic HBA drivers on an FC system, Windows Host Utilities checks several parameters and, in some cases, modifies them.

The Windows Host Utilities sets values for the following parameters if MS DSM for Windows MPIO is detected:

* *LinkTimeOut*: Defines the length of time in seconds that the host port waits before resuming I/O after a physical link is down.
* *NodeTimeOut*: Defines the length of time in seconds before the host port recognizes that a connection to the target device is down.

When troubleshooting HBA issues, check to make sure these settings have the correct values. The correct values depend on two factors:

* The HBA vendor
* Whether you are using MPIO software.

You can correct the HBA settings by link:hu_wuhu_repair_remove.html[running the Repair option] in the Windows Host Utilities installer.

[role="tabbed-block"]
====

.Emulex HBA drivers
--

Verify the Emulex HBA driver settings on FC systems. These settings must exist for each port on the HBA.

.Steps

. Open OnCommand Manager.
. Select the appropriate HBA from the list and select the *Driver Parameters* tab.
+
The driver parameters appear.
+
.. If you are using MPIO software, ensure that you have the following driver settings:
+
* LinkTimeOut - 1
* NodeTimeOut - 10
.. If you aren't using MPIO software, ensure that you have the following driver settings:
+
* LinkTimeOut - 30
* NodeTimeOut - 120
--

.QLogic HBA drivers
--
Verify the QLogic HBA driver settings on FC systems. These settings must exist for each port on the HBA.

.Steps

. Open QConvergeConsole, and then select *Connect* on the toolbar.
+
The *Connect to Host* dialog box appears.
. Select the appropriate host from the list, and then select *Connect*.
+
A list of HBAs appears in the FC HBA pane.
. Select the appropriate HBA port from the list, and then select the *Settings* tab.
. Select *Advanced HBA Port Settings* from the *Select Settings* section.
. If you are using MPIO software, verify that you have the following driver settings:
+
* Link Down Timeout (linkdwnto) - 1
* Port Down Retry Count (portdwnrc) - 10
. If you aren't using MPIO software, verify that you have the following driver settings:
+
* Link Down Timeout (linkdwnto) - 30
* Port Down Retry Count (portdwnrc) - 120
--
====

// 2025 DEC 4, ONTAPDOC-3395 and NADIAA updates
// 2025 FEB 14, ONTAPDOC-2521