---
sidebar: sidebar
permalink: hu_wuhu_72.html
keywords: wuhu, 7.2, host utilities, SAN, windows, unified
summary: Windows Unified host utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for NetApp ONTAP and E-Series platforms.
---

= Windows Unified Host Utilities 7.2
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
The Windows Unified Host Utilities enable you to connect a Windows host computer to NetApp storage systems.

Windows Unified host utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for NetApp ONTAP and E-Series platforms.

When you install the host utilities software, the installer sets the required Windows registry and HBA parameters.

The following programs and files are installed on the Windows host computer. The default directory is `C:\Program Files\NetApp\Windows Host Utilities`.

|===
|Program |Purpose

|`emulexhba.reg`
|Troubleshooting program; run this program only if instructed to do so by technical support personnel.
| `\NetAppQCLI\fcconfig.exe`
|Used by the installation program to set the HBA parameters.
| `\NetAppQCLI\fcconfig.ini`
|Used by the installation program to set the HBA parameters.
|`\NetAppQCLI\*.*`
|Used by the installation program to set the QLogic FC HBA parameters.
|`san_version.exe`
|Displays the version of the host utilities and FC HBAs.
|===

The host utilities support different Windows host configurations, protocols, and multipathing options. For more information, see the https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool^].

The Windows Unified Host Utilities continues to support the following versions of Windows:

* Windows 2012
* Windows 2012R2
* Windows 2016
* Windows 2019
* Windows 2022


== Verify your host and storage system configuration

Before you install the host utilities, you must verify that the host utilities version supports your host and storage system configuration so that the software installs correctly.

.Steps

. Check the supported configuration in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].
. Check the hotfixes required for the respective host in the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[SAN host Windows documentation].
+
[NOTE]
link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html[Using Windows server 2022 with ONTAP] provides instructions on link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes[installing Windows hotfixes] for Windows server 2022. Refer to the  Windows documents in the host configurations category to find the relevant hotfix information for earlier versions of Windows server.

. Add the iSCSI, FCP, or NVMe-oF license and start the target service.
+
The FC and iSCSI protocols do not require licenses on E-Series storage systems using SANtricity Storage Manager.

. Verify your cabling.
+
See the https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7[SAN Configuration Guide^] for your ONTAP version or the https://mysupport.netapp.com/ecm/ecm_get_file/ECMLP2773533[E-Series Hardware Cabling Guide^] for detailed cabling and configuration information.

== Configure FC HBAs and switches

Install and configure one or more supported FC host bus adapters (HBAs) for FC connections to the storage system.

The Windows Host Utilities installer sets the required FC HBA settings.

[CAUTION]
Do not change the HBA settings manually.

.Steps

. Install one or more supported FC HBAs according to the instructions provided by the HBA vendor.
. Obtain the supported HBA drivers and management utilities and install them according to the instructions provided by the HBA vendor.
. Connect the HBAs to your FC switches or directly to the storage system.
. Create zones on the FC switch according to your FC switch documentation.
. For ONTAP, zone the switch by the WWPN. Be sure to use the WWPN of the logical interfaces (LIFs) and not the WWPN of the physical ports on the storage controllers. For more information, see https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7[SAN Configuration Guide^].

== Install the host utilities

The installation program installs the host utilities package and sets the Windows registry and HBA settings.

You must specify whether to include multipathing support when you install the Windows Unified Host Utilities software package. The installer prompts you for the following options. You can also run a quiet (unattended) installation from a Windows command prompt.

.Multipathing support

* Choose `MPIO` if you have more than one path from the Windows host or virtual machine to the storage system. 
* Choose `no MPIO` only if you are using a single path to the storage system.

The MPIO selection is not available for Windows XP and Windows Vista systems; multipath I/O is not supported on these guest operating systems.
For Hyper-V guests, raw (pass-through) disks do not appear in the guest OS if you choose multipathing support. You can either use raw disks, or you can use MPIO, but you cannot use both in the guest OS.

[role="tabbed-block"]
====

.Install the host utilities interactively
--

To install the host utilities software package interactively, you must run the host utilities installation program and follow the prompts.

.Steps

. Download the executable file from the https://mysupport.netapp.com/site/[NetApp Support Site^].
. Change to the directory where you downloaded the executable file.
. Run the `netapp_windows_host_utilities_7.2_x64` file and follow the instructions on the screen.
. Reboot the Windows host when prompted.
--

.Install the host utilities from a command line
--

You can perform a quiet (unattended) installation of the host utilities by entering the appropriate commands at the Windows command prompt.
The host utilities installation package must be in a path that is accessible by the Windows host. 

Follow the instructions for installing the host utilities interactively to obtain the installation package. The system automatically reboots when the installation is complete.

.Steps

. Enter the following command at the Windows command prompt:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

* `installer` is the name of the `.msi` file for your CPU architecture.
* MULTIPATHING specifies whether MPIO support is installed. The allowed values are "0" for no and "1" for yes.
* `inst_path` is the path where the host utilities files are installed. The default path is `C:\Program Files\NetApp\Windows Host Utilities\`.

[NOTE]
To see the standard Microsoft Installer (MSI) options for logging and other functions, enter `msiexec /help` at the Windows command prompt. For example, the `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` command displays logging information.

--
====



== Overview of settings used by the host utilities

The host utilities require certain registry and parameter settings to verify that the Windows host correctly handles the storage system behavior.

Windows Host Utilities set the parameters that affect how the Windows host responds to a delay or loss of data. The particular values have been selected to verify that the Windows host correctly handles events such as the failover of one controller in the storage system to its partner controller.

Not all values apply to the DSM for SANtricity Storage Manager; however, any overlap of values set by the host utilities and those set by the DSM for SANtricity Storage Manager do not result in conflicts.

FC, NVMe/FC, and iSCSI HBAs also have parameters that you must set to ensure best performance and to successfully handle storage system events.

The installation program supplied with Windows Unified Host Utilities sets the Windows, FC, and NVMe/FC HBA parameters to the supported values.

You must manually set the iSCSI HBA parameters.

The installer sets different values depending on whether you specify multipath I/O (MPIO) support when running the installation program.

You should not change these values unless technical support directs you to do so.

== Registry values set by Windows Unified Host Utilities

The Windows Unified Host Utilities installer automatically sets registry values that are based on the choices that you make during the installation. You should be aware of these registry values and the operating system version.

The following values are set by the Windows Unified Host Utilities installer. All values are decimal unless otherwise stated. 

[NOTE]
HKLM is the abbreviation for `HKEY_LOCAL_MACHINE`.

[cols=3*,options="header", cols="20,20,30"]
|===
|Registry key |Value |When set

|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters
\DsmMaximumRetryTimeDuringStateTransition
|120
|When MPIO support is specified and your server is Windows Server 2012 R2,
Windows Server 2016 and Windows 2019, or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet
\Services\msdsm\Parameters
\DsmMaximumStateTransitionTime
|120
|When MPIO support is specified and your server is Windows Server 2012 R2,
or Windows Server 2016, Windows 2019 or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\DsmSupportedDeviceList
|"NETAPP LUN", "NETAPP LUN C-
Mode"
"NVMe NetApp ONTAO Con"
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \IPSecConfigTimeout
|60
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \LinkDownTime
|10
|Always
|HKLM\SYSTEM\CurrentControlSet\Services
\ClusDisk \Parameters\ManageDisksOnSystemBuses
|1
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \MaxRequestHoldTime
|120
|When no MPIO support is selected
|HKLM\SYSTEM\CurrentControlSet\Control
\Class\ {iSCSI_driver_GUID}\ instance_ID
\Parameters \MaxRequestHoldTime
|30
|Always
|HKLM\SYSTEM\CurrentControlSet\Control
\MPDEV\MPIOSupportedDeviceList
|"NETAPP LUN",
"NETAPP LUN C-
Mode",
"NVMe NetApp ONTAO Con"
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathRecoveryInterval
|30
|When your server is Windows Server 2012 R2,
Windows Server 2016, Windows Server 2019, or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\PathVerifyEnabled
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\msdsm\Parameters\PathVerifyEnabled
|1
|When MPIO support is specified and your server is Windows Server 2012 R2,
Windows Server 2016, Windows Server 2019, or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet\Services
\vnetapp\Parameters\PathVerifyEnabled
|0
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\mpio\Parameters\PDORemovePeriod
|130
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified and your server is  Windows Server 2012 R2,
Windows Server 2016 , Windows Server 2019, or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet\Services\vnetapp
\Parameters\PDORemovePeriod
|130
|When MPIO support is specified, except if Data ONTAP DSM is detected
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\RetryCount
|6
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryCount
|6
|When MPIO support is specified and your server is Windows Server 2012 R2,
Windows Server 2016, Windows Server 2019, or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\RetryInterval
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services\msdsm
\Parameters\RetryInterval
|1
|When MPIO support is specified and your server is  Windows Server 2012 R2,
Windows Server 2016, Windows Server 2019, or Windows Server 2022
|HKLM\SYSTEM\CurrentControlSet\Services\vnetapp
\Parameters\RetryInterval
|1
|When MPIO support is specified
|HKLM\SYSTEM\CurrentControlSet\Services
\disk\TimeOutValue
|120
|When no MPIO support is selected
|HKLM\SYSTEM\CurrentControlSet\Services\mpio
\Parameters\UseCustomPathRecoveryInterval
|1
|When MPIO support is specified and your server is  Windows Server 2012 R2,
Windows Server 2016, Windows Server 2019, or Windows Server 2022
|===


Refer to the Microsoft documents for the registry parameter details.

== NVMe parameters

The following NVMe Emulex driver parameters are updated when installing WUHU 7.2:

* EnableNVMe = 1
* NVMEMode = 0
* LimTransferSize=1
 
== FC HBA values set by Windows Host Utilities

On systems using FC, the host utilities installer sets the required timeout values for Emulex and QLogic FC HBAs.

For Emulex FC HBAs, the installer sets the following parameters:

[role="tabbed-block"]
====
.When MPIO is selected
--
|===
|Property type |Property value

|LinkTimeOut
|1
|NodeTimeOut
|10
|===
--

.When MPIO is not selected
--
|===
|Property type |Property value

|LinkTimeOut
|30
|NodeTimeOut
|120
|===
--
====

For QLogic FC HBAs, the installer sets the following parameters:

[role="tabbed-block"]
====
.When MPIO is selected
--
|===
|Property type |Property value

|LinkDownTimeOut
|1
|PortDownRetryCount
|10
|===
--

.When MPIO is not selected
--
|===
|Property type |Property value

|LinkDownTimeOut
|30
|PortDownRetryCount
|120
|===
--
====

[NOTE]
The names of the parameters might vary slightly depending on the program.
For example, in the QLogic QConvergeConsole program, the parameter is displayed as `Link Down Timeout`.
The host utilities `fcconfig.ini` file displays this parameter as either `LinkDownTimeOut` or `MpioLinkDownTimeOut`, depending on whether MPIO is specified. However, all of these names refer to the same HBA parameter.

.Related information
Refer to Emulex or QLogic site to know more about the timeout parameters.

