---
sidebar: sidebar
permalink: hu_wuhu_upgrade.html
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform
summary: Windows Host Utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for ONTAP and E-Series platforms.
---
= Upgrade Windows Host Utilities for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can upgrade Windows Host Utilities software in your ONTAP storage configuration by following the installation instructions interactively or by using the Windows command line. You need to install the new Windows Host Utilities installation software on a path that is accessible to the Windows host. 

[role="tabbed-block"]
====
.Upgrade interactively
--
Upgrade the Windows Host Utilities software interactively by running the Host Utilities installation program and following the prompts.

.Steps

. Change to the directory where you downloaded the executable file.
. Run the executable file and follow the instructions on the screen.
. Reboot the Windows host when prompted.
.  After the reboot completes, check the host utility version:
.. Open *Control Panel*.
.. Go to *Program and features* and check the host utility version.
--

.Upgrade noninteractively
--
Perform a noninteractive Windows Host Utilities software upgrade by using the Windows command line.

.Steps

. Enter the following command at the Windows command prompt:
+
[source,cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----

* `installer` is the name of the `.msi` file for your CPU architecture.
* MULTIPATHING specifies whether Microsoft Multipath I/O (MPIO) support is installed. The allowed values are "0" for no and "1" for yes.
* `inst_path` is the path where the Host Utilities files are installed. The default path is `C:\Program Files\NetApp\Windows Host Utilities\`.

[NOTE]
To see the standard Microsoft Installer (MSI) options for logging and other functions, enter `msiexec /help` at the Windows command prompt. For example, the `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` command displays logging information.

The system automatically reboots when the installation is complete.
--
====