---
sidebar: sidebar
permalink: hu_wuhu_upgrade.html
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform
summary: Windows Unified Host Utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for NetApp ONTAP and E-Series platforms.
---

= Upgrade the Windows Host Utilities
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The new Host Utilities installation package must be in a path that is accessible by the Windows host. Follow the instructions for installing the Host Utilities interactively or from the Windows command line in order to upgrade the installation package.

[role="tabbed-block"]
====
.Upgrade the Host Utilities interactively
--
To upgrade the Host Utilities software package interactively, you must run the Host Utilities installation program and follow the prompts.

.Steps

. Change to the directory where you downloaded the executable file.
. Run the executable file and follow the instructions on the screen.
. Reboot the Windows host when prompted.
.  After the reboot completes, check the host utility version:
.. Open *Control Panel*.
.. Go to *Program and features* and check the host utility version.
--

.Upgrade the Host Utilities from a command line
--
You can perform a quiet (unattended) upgrade of the new Host Utilities by entering the appropriate commands at the Windows command prompt.



.Steps

. Enter the following command at the Windows command prompt:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

* `installer` is the name of the `.msi` file for your CPU architecture.
* MULTIPATHING specifies whether MPIO support is installed. The allowed values are "0" for no and "1" for yes.
* `inst_path` is the path where the Host Utilities files are installed. The default path is `C:\Program Files\NetApp\Windows Host Utilities\`.

[NOTE]
To see the standard Microsoft Installer (MSI) options for logging and other functions, enter `msiexec /help` at the Windows command prompt. For example, the `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` command displays logging information.

The system automatically reboots when the installation is complete.
--
====