---
sidebar: sidebar
permalink: hu_wuhu_71_rn.html
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes
summary: Release Notes for Windows Unified Host Utilities 7.1
---

= Windows Unified Host Utilities 7.1 Release Notes
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This Release Notes document contains the latest information for the Windows Unified Host Utilities 7.1 release, including updates about new features, enhancements, and known issues. The document is updated when new information on using the Windows Host Utilities becomes available.

== About the Windows Unified Host Utilities 7.1 release
The Windows Unified Host Utilities enable you to connect a Windows host computer to NetApp storage systems. The Windows Unified Host Utilities include an installation program that sets the required Windows registry and HBA values.

The Windows Unified Host Utilities 7.1 continues to support the following versions of Windows:

* Windows 2012
* Windows 2012R2
* Windows 2016
* Windows 2019
* Windows 2022

[NOTE]
NetApp qualifies additional components between releases of the Host Utilities software.
For the latest information about the system requirements, see the link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].


=== Features in this Host Utilities release
Windows Unified Host Utilities 7.1 includes support for E-Series storage systems, support for ONTAP 8.2 or later versions, and enhanced iSCSI timeouts for faster failover.

== Prerequisite

Install the latest hotfixes before installing the Windows Host Utilities. Refer to link:https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71.html[Windows Unified Host Utilities 7.1] document for your specific configuration hotfix requirements.


[WARNING]
*Error when installing hotfixes*
When installing required Windows hotfixes, you might get an error message saying the hotfix does not apply to your system. Some hotfixes have a dependency on other hotfixes. Install the hotfixes in numerical order to ensure they are accepted. Many hotfixes prompt you to reboot your system. You can wait until all hotfixes are installed before rebooting. If you are installing Windows Host Utilities immediately after the hotfixes, you can wait and reboot when prompted by the Host Utilities installation program.

== Known issues

Some unexpected and potentially undesired behaviors, as well as, in some cases, workarounds to avoid these behaviors, have been identified in this release. 

[cols=3,options="header", cols= "10, 30, 30"]
|===
|NetApp Bug ID	|Title |Description
|814244	|Running the linux_gos_timeout-install.sh script is no longer required on Hyper-V guests running Red Hat Enterprise Linux or SUSE Linux Enterprise Server |You are no longer required to run the `linux_gos_timeout-install.sh` script to change disk timeouts on Red Hat Enterprise Linux 5, Red Hat Enterprise Linux 6, or SUSE Linux Enterprise Server 11 Hyper-V guests because the default timeout settings are being used. The `linux_gos_timeout-install.sh` script that was included in previous versions of the Host Utilities is no longer included in the Windows Unified Host Utilities. Windows Unified Host Utilities 7.1 uses the default disk timeout settings.
|342374 |iSCSI sessions do not reconnect after reboot with mixed IPv4 and IPv6 |In a multipath I/O (MPIO) configuration or multiple connections per session (MCS) configuration that has both IPv4 and IPv6 endpoints, some iSCSI sessions might fail to reconnect after rebooting the Windows host.
To ensure that all of your iSCSI paths return after a reboot, use either all IPv4 endpoints or all IPv6. Do not mix IPv4 and IPv6.
|275185 | MCS is not supported with iSCSI software boot |When using iSCSI software boot with iSCSI multiple connections per session (MCS), the iSCSI boot leading connection cannot be protected. This can lead to disconnection from the boot LUN causing the host to crash.
Microsoft does not support MCS for iSCSI software booted hosts. Use MPIO as the high availability solution. Note that mixing MPIO and MCS is not supported.
|===

link:https://mysupport.netapp.com/site/bugs-online/product[NetApp Bugs Online^] provides complete information for most known issues, including suggested workarounds where possible.

== Known limitations

*Virtual Fibre Channel is not supported in virtual machines on Windows Server 2012 hosts* 
Virtual Fibre Channel is not supported in virtual machines on Windows Server 2012 hosts connected to FAS storage systems running Data ONTAP.

*Raw (pass-through) disks do not appear in Hyper-V guest OS*
Raw (pass-through) disks do not appear in a Hyper-V guest OS if Windows Host Utilities is installed on the guest and multipathing support is enabled. When you enable multipathing support for Windows Host Utilities, LUNs on NetApp storage systems are claimed by the Windows MPIO drivers. Raw disks that are also based on NetApp LUNs are not passed to MPIO, and therefore not visible in the guest OS. You can either use multipathing in the guest OS, or you can use raw disks, but not both.

*Guest OS install on SCSI disk fails*
You cannot boot a Hyper-V virtual machine from a SCSI-mapped disk. Use an IDE-mapped disk for the virtual machine boot disk

== About SAN Host Configuration documentation
Documentation for SAN Host Utilities is included in the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[ONTAP SAN Host Configuration documentation]. ONTAP SAN HOST configuration documentation is cumulative, covering all current SAN HOST releases. Any functional differences across releases are noted in context.

== Where to find product documentation and other information
You can access documentation for all NetApp products and find other product information resources, such as technical reports and white papers on the Product Documentation page of the NetApp corporate site.

.Related information

*Configuring and managing your ONTAP storage system*

* The link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html[ONTAP Software Setup Guide^] for your version of ONTAP
* The link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP SAN Administration Guide^] for your version of ONTAP
* The link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^] for your version of ONTAP

*Configuring and managing your E-Series storage system*

* The SANtricity Storage Manager Configuration and Provisioning for Windows Express Guide that is appropriate for your protocol
* The SANtricity Storage Manager Configuration and Provisioning Express Guide for your operating system, protocol, and version of SANtricity.
* The SANtricity Storage Manager Software Installation Reference specific for your version of SANtricity.
* The SANtricity Storage Manager Multipath Driver's Guide specific for your version of SANtricity.
* The SANtricity Storage Manager Release Notes for your version of SANtricity.

See the link:https://docs.netapp.com/us-en/e-series/getting-started/index.html[E-Series documentation^] to find SANtricity related documentation.
