---
sidebar: sidebar
permalink: hu_wuhu_repair_remove.html
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform
summary: Windows Host Utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for ONTAP and E-Series platforms.
---
= Repair and remove the Windows Host Utilities
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the *Repair* option of the Host Utilities installation program to update the Host bus adapter (HBA) and Windows registry settings. You can also remove the Host Utilities entirely, either interactively or from the Windows command line.

[role="tabbed-block"]
====
.Repair or remove interactively
--
The *Repair* option updates the Windows registry and FC HBAs with the required settings. You can also remove the Host Utilities entirely.

.Steps

. Open Windows *Programs and Features* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019, and Windows 2022).
. Select *NetApp Windows Host Utilities*.
. Select *Change*.
. Select *Repair* or *Remove*, as needed.
. Follow the instructions on the screen.
--

.Repair or remove from command line
--
The *Repair* option updates the Windows registry and FC HBAs with the required settings. You can also remove the Host Utilities entirely from a Windows command line.

.Steps

. Repair Windows Host Utilities:
+
`msiexec /f installer.msi [/quiet]`

* `/f` repairs the installation.
* `installer.msi` is the name of the Windows Host Utilities installation program on your system.
* `/quiet` suppresses all feedback and reboots the system automatically without prompting when the command completes.
--
====