---
sidebar: sidebar
permalink: hu_wuhu_71.html
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform
summary: Windows Host Utilities includes an installation program that sets the required Windows registry and HBA parameters so that the Windows host correctly handles the storage system behaviors for ONTAP and E-Series platforms.
---
= Install Windows Host Utilities 7.1 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Windows Host Utilities enable you to connect a Windows host computer to NetApp storage systems.

[[supported-windows-versions-71]]
Windows Host Utilities supports the following versions of Windows:

* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012

Windows Host Utilities includes an installation program that sets the required Windows registry and Host Bus Adapter (HBA) parameters so that a Windows host can correctly handle the storage system behaviors for ONTAP and E-Series platforms.

include::_include/windows/windows-install-chunk-a.adoc[]

|===
|Program |Purpose

|`emulexhba.reg`
|Troubleshooting program; run this program only if instructed to do so by technical support personnel.
| `\NetAppQCLI\fcconfig.exe`
|Used by the installation program to set HBA parameters.
| `\NetAppQCLI\fcconfig.ini`
|Used by the installation program to set HBA parameters.
|`\NetAppQCLI\*.*`
|Used by the installation program to set QLogic FC HBA parameters.
|`san_version.exe`
|Displays the version of the Host Utilities and FC HBAs.
|===


The Host Utilities support different Windows host configurations, protocols, and multipathing options. See the https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^] for the current list of supported configurations.

== Step 1: Verify your host and storage system configurations

Verify that your host and storage system configuration are supported before you install Windows Host Utilities for the <<supported-windows-versions-71,supported Windows version>>.

.Steps

. Check the supported configuration in the http://mysupport.netapp.com/matrix[Interoperability Matrix Tool^].
. Check the hotfixes required for your Windows Server host version in the link:https://docs.netapp.com/us-en/ontap-sanhost/index.html[SAN host Windows documentation].
+
For example, the link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html[Configure Windows Server 2022 for ONTAP storage] documentation provides the instructions for installing Windows hotfixes for Windows server 2022.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html[Add the iSCSI or FCP license^].
+
[NOTE]
The FC and iSCSI protocols don't require licenses on E-Series storage systems using the SANtricity Storage Manager.

include::_include/windows/windows-install-chunk-b.adoc[]

include::_include/windows/windows-install-host-utilities.adoc[]

[role="tabbed-block"]
====

.Install interactively
--
Install the Host Utilities software package interactively by running the Host Utilities installation program and following the prompts.


. Download the executable file from the https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads[NetApp Support Site^].
. Change to the directory from which you downloaded the executable file.
. Run the `netapp_windows_host_utilities_7.1_x64` file and follow the instructions on the screen.
. Reboot the Windows host when prompted.
--
.Install noninteractively
--
Perform a noninteractive installation of the Host Utilities by using the Windows command line. The system automatically reboots when the installation is complete.


. Enter the following command at a Windows command prompt:
+
[source,cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----

* `installer` is the name of the `.msi` file for your CPU architecture
* MULTIPATHING specifies whether MPIO support is installed. Allowed values are "0" for no, "1" for yes
* `inst_path` is the path where the Host Utilities files are installed. The default path is `C:\Program Files\NetApp\Windows Host Utilities\`.

[NOTE]
To see the standard Microsoft Installer (MSI) options for logging and other functions, enter `msiexec /help` at a Windows command prompt. For example, the`msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` command displays logging information.
--
====

include::_include/windows/windows-install-whats-next.adoc[]

// 2025 ARR 28, ontap-sanhost-issue-218