---
sidebar: sidebar
permalink: hu_windows_2025.html
keywords: windows, enterprise
summary: You can use the ONTAP SAN host configuration settings to configure Windows Server 2025 for operation with ONTAP storage.
---
= Configure Windows Server 2025 for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure Windows Server 2025 for operation with ONTAP storage. 

== Boot the Windows OS
include::_include/windows/reuse_windows_booting_OS.adoc[]

== Install Windows hotfixes
NetApp recommends installing the *latest cumulative update* available from the Microsoft Update Catalog on the host server.

.Steps

. Download the hotfixes from the link:https://www.catalog.update.microsoft.com/Search.aspx?q=update%20%22windows%20server%202025%22[Microsoft Update Catalog^].

include::_include/windows/reuse_windows_hotfix_install.adoc[]

== Install the Windows Host Utilities
include::_include/windows/reuse_windows_installing_WUHU.adoc[]

== Multipathing
include::_include/windows/reuse_windows_multipathing.adoc[]

The MPIO software presents a single disk to the Windows OS for all paths, and a device-specific module (DSM) manages path failover. On a Windows system, the two main components in any MPIO solution are the DSM and the Windows MPIO. When you select MPIO support, the Windows Host Utilities enables the MPIO feature included in Windows Server 2025. 

NOTE: Windows XP or Windows Vista running in a Hyper-V virtual machine doesn't support MPIO.

== SAN configuration

include::_include/windows/reuse_windows_asa_configuration.adoc[]


=== Non-ASA configuration
include::_include/windows/reuse_windows_non_asa_configuration.adoc[]

== Recommended settings
include::_include/windows/reuse_windows_recommended_settings.adoc[]

== Known issues
There are no known issues for the Windows Server 2025 with ONTAP release.
