---
sidebar: sidebar
permalink: hu_windows_2022.html
keywords: windows, enterprise
summary: Using Windows Server 2022 with ONTAP
---
= Use Windows Server 2022 with ONTAP
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use the ONTAP SAN host configuration settings to configure Windows Server 2022 for operation with ONTAP storage. 

== Boot the Windows OS

include::_include/windows/reuse-windows-san-boot-2022-and-later.adoc[]

== Install Windows hotfixes
NetApp recommends installing the *latest cumulative update* available from the Microsoft Update Catalog on the host server.

.Steps

. Download the hotfixes from the link:https://www.catalog.update.microsoft.com/Search.aspx?q=update%20%22windows%20server%202022%22[Microsoft Update Catalog 2022^].

include::_include/windows/reuse_windows_hotfix_install.adoc[]

== Install the Windows Host Utilities
include::_include/windows/reuse_windows_installing_WUHU.adoc[]

== Multipathing

You need to install the Microsoft Multipath I/O (MPIO) software and enable multipathing if your Windows host has more than one path to the storage system. When you select MPIO support, the Windows Host Utilities enables the MPIO feature included in Windows Server 2022. If you're not using the Windows Host Utilities, you need to enable multipathing manually.

include::_include/windows/reuse-windows-multipathing.adoc[]


== SAN configuration

include::_include/windows/reuse_windows_asa_configuration.adoc[]


=== Non-ASA configuration
include::_include/windows/reuse_windows_non_asa_configuration.adoc[]

== Recommended settings
include::_include/windows/reuse_windows_recommended_settings.adoc[]

== Known issues
There are no known issues for the Windows Server 2022 with ONTAP release.
