---
permalink: legal_notices.html
sidebar: sidebar
keywords: legal, notices, copyright, trademarks, patents
summary: Legal notices provide access to copyright statements, trademarks, patents, and more.
---
= Legal notices

:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Legal notices provide access to copyright statements, trademarks, patents, and more.

== Copyright

http://www.netapp.com/us/legal/copyright.aspx

== Trademarks

NETAPP, the NETAPP logo, and the marks listed on the NetApp Trademarks page are trademarks of NetApp, Inc. Other company and product names may be trademarks of their respective owners.

http://www.netapp.com/us/legal/netapptmlist.aspx

== Patents

A current list of NetApp owned patents can be found at:

https://www.netapp.com/us/media/patents-page.pdf

== Privacy policy

https://www.netapp.com/us/legal/privacypolicy/index.aspx

== Open source

Provides information about third-party copyright and licenses used in this product.

* link:./media/Notices-AIX61-2023.pdf[Notice for AIX^]
* link:./media/Linux_Unified_Host_Utilities.pdf[Notice for Linux^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf[Notice for Solaris^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf[Notice for Windows^] 

// 29 Mar 2023, HU notice file update