---
sidebar: sidebar
permalink: nvme_ol_83.html
keywords: nvme, linux, oracle, 8.3
summary: Setting up VMe/FC Host Configuration for Oracle Linux 8.3 with ONTAP, with examples
---

= NVMe/FC Host Configuration for Oracle Linux 8.3 with ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Supportability

NVMe/FC is supported with Oracle Linux 8.3 with Asymmetric Namespace Access (ANA) required for surviving storage failovers (SFOs) on the ONTAP array. ANA is the ALUA equivalent in the NVMe-oF environment and is currently implemented with in-kernel NVMe Multipath. This document contains the details for enabling NVMe-oF with in-kernel NVMe Multipath using ANA on OL 8.3 and ONTAP as the target.

include::_include/hu/reuse_hu_cloud_note.adoc[]

== Features

* Oracle Linux 8.3 has In-kernel NVMe multipath enabled by default for NVMe namepsaces.

* With Oracle Linux 8.3, nvme-fc auto-connect scripts are included in the native nvme-cli package. So one may rely on these native auto-connect scripts itself instead of having to install the external vendor provided outbox auto-connect scripts.

* With Oracle Linux 8.3, a native udev rule is already provided as part of the nvme-cli package which enables round-robin load balancing for NVMe multipath. So one need not manually create this rule any more .

* With Oracle Linux 8.3, both NVMe & SCSI traffic can be run on the same co-existent host. In fact, that is expected to be the commonly deployed host config for customers. So for SCSI, one may configure dm-multipath as usual for SCSI LUNs resulting in mpath devices, whereas NVMe multipath may be used to configure NVMe-oF multipath devices (i.e. /dev/nvmeXnY) on the host.

* With Oracle Linux 8.3, the NetApp plugin in the native nvme-cli is capable of displaying ONTAP details as well for ONTAP namespaces.

== Configuration requirements

Refer to the http://mysupport.netapp.com/matrix3[NetApp InterOperability Matrix (IMT)^] for exact details regarding supported configs and current list of supported configurations.

== Enable NVMe/FC with Oracle Linux 8.3

.Steps

. Install Oracle Linux 8.3 GA on the server. After the installation is complete, verify that you are running the specified Oracle Linux 8.3 GA kernel. See the https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix^] for the most current list of supported versions.
+

----
# uname -r 
_5.4.17-2011.7.4.el8uek.x86_64_
----

. Install the nvme-cli package.

+
----
# rpm -qa|grep nvme-cli

nvme-cli-1.12-2.el8.x86_64_
----

. On the Oracle Linux 8.3 host, check the hostnqn string at /etc/nvme/hostnqn and verify that it matches the hostnqn string for the corresponding subsystem on the ONTAP array.
+
----
#*cat /etc/nvme/hostnqn* +
http://nqn.2014-08.org/[_nqn.2014-08.org.nvmexpress:uuid:446c21ab-f4c1-47ed-9a8f-1def96f3fed2_]

::> vserver nvme subsystem host show -vserver vs_coexistance_2 +
Vserver Subsystem Host NQN +
------- --------- ---------------------------------------------------------- +
vs_coexistance_2 +
nvme_1 +
http://nqn.2014-08.org/[nqn.2014-08.org].nvmexpress:uuid:446c21ab-f4c1-47ed-9a8f-1def96f3fed2
----
+
[NOTE]
If the hostnqn strings do not match, you should use the vserver modify command to update the hostnqn string on your corresponding ONTAP array subsystem to match to the hostnqn string from /etc/nvme/hostnqn on the host.

. Reboot the host.
+
[NOTE] 
If you intend to run both NVMe and SCSI traffic on the same Oracle Linux 8.3 co-existent host, it is recommended to use in-kernel NVMe multipath for ONTAP namespaces and dm-multipath for ONTAP LUNs respectively. And that also means the ONTAP namespaces should be blacklisted in dm-multipath to prevent dm-multipath from claiming these namespace devices. This can be done by adding the _enable_foreign_ setting to the /etc/multipath.conf:
+
----
#*cat /etc/multipath.conf* +
_defaults \{_ +
_ enable_foreign  NONE_ +
_}
----

. Restart the multipathd daemon by running a _systemctl restart multipathd_ to let the new setting take effect.

==  Configure the Broadcom FC adapter for NVMe/FC
 
.Steps

. Verify that you are using the supported adapter. For the most current list of supported adapters, see the https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix^].

+
----
# *cat /sys/class/scsi_host/host*/modelname* +
_LPe36002-M2_ +
_LPe36002-M2_
----
+
----
__# __**cat /sys/class/scsi_host/host*/modeldesc** +
_Emulex LPe36002-M64 2-Port 64Gb Fibre Channel Adapter +
Emulex LPe36002-M64 2-Port 64Gb Fibre Channel Adapter_
----

. Verify that you are using the recommended Broadcom lpfc firmware & inbox driver. For the most current list of supported adapter driver & firmware versions, see the https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix^].
+
----
# *cat /sys/class/scsi_host/host*/fwrev* +
_12.8.351.49, sli-4:6:d +
12.8.351.49, sli-4:6:d_
----
+
----
_# *cat /sys/module/lpfc/version*_ +
_0:12.6.0.3_
----

. Verify that lpfc_enable_fc4_type is set to 3
+
----
# *cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type* +
_3_
----

. Verify that the initiator ports are up and running, and able to see the target LIFs.

+
----
# *cat /sys/class/fc_host/host*/port_name* +
_0x100000109bf0447b +
0x100000109bf0447c_
----
+
----
# *cat /sys/class/fc_host/host*/port_state* +
_Online_ +
_Online_
----
+
----
# *cat /sys/class/scsi_host/host*/nvme_info*

NVME Initiator Enabled +
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250 +
NVME LPORT lpfc0 WWPN x100000109bf0447b WWNN x200000109bf0447b DID x022400 ONLINE +
NVME RPORT WWPN x20e1d039ea243510 WWNN x20e0d039ea243510 DID x0a0314 TARGET DISCSRVC ONLINE +
NVME RPORT WWPN x20e4d039ea243510 WWNN x20e0d039ea243510 DID x0a0713 TARGET DISCSRVC ONLINE

NVME Statistics +
LS: Xmt 00000003b6 Cmpl 00000003b6 Abort 00000000 +
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000 +
Total FCP Cmpl 00000000be1425e8 Issue 00000000be1425f2 OutIO 000000000000000a +
abort 00000251 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000 +
FCP CMPL: xb 00000c5b Err 0000d176

NVME Initiator Enabled +
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250 +
NVME LPORT lpfc1 WWPN x100000109bf0447c WWNN x200000109bf0447c DID x021600 ONLINE +
NVME RPORT WWPN x20e2d039ea243510 WWNN x20e0d039ea243510 DID x0a0213 TARGET DISCSRVC ONLINE +
NVME RPORT WWPN x20e3d039ea243510 WWNN x20e0d039ea243510 DID x0a0614 TARGET DISCSRVC ONLINE

NVME Statistics +
LS: Xmt 0000000419 Cmpl 0000000419 Abort 00000000 +
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000 +
Total FCP Cmpl 00000000be37ff65 Issue 00000000be37ff84 OutIO 000000000000001f +
abort 0000025a noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000 +
FCP CMPL: xb 00000c89 Err 0000cd87
----

=== Enable 1MB I/O size

.Steps

. The _lpfc_sg_seg_cnt_ parameter needs to be set to 256 for the lpfc driver to issue I/O requests upto 1 MB size.
+

----
# *cat /etc/modprobe.d/lpfc.conf* +
_options lpfc lpfc_sg_seg_cnt=256_
----

. Run a dracut -f command and then reboot the host.

. After the host reboot, verify that _lpfc_sg_seg_cnt_ is set to 256.
+
----
# *cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt* +
_256_
----

== Configure the Marvell/QLogic FC Adapter for NVMe/FC

.Steps

. The native inbox qla2xxx driver included in the OL 8.3 GA kernel has the latest upstream fixes, essential for ONTAP support. Verify that you are running the supported adapter driver and firmware versions:

+
----
# *_cat /sys/class/fc_host/host*/symbolic_name_* +
_QLE2742 FW:v9.10.11 DVR:v10.01.00.25-k +
QLE2742 FW:v9.10.11 DVR:v10.01.00.25-k_
----

. Verify ql2xnvmeenable is set which enables the Marvell adapter to function as a NVMe/FC initiator:
+
----
_#* cat /sys/module/qla2xxx/parameters/ql2xnvmeenable*_ +
_1_
----
 

== Validating NVMe/FC

.Steps

. Verify the following NVMe/FC settings on the Oracle Linux 8.3 host:
+

----
# *cat /sys/module/nvme_core/parameters/multipath* +
_Y_

# **cat /sys/class/nvme-subsystem/nvme-subsys*/mode**l +
_NetApp ONTAP Controller_ +
_NetApp ONTAP Controller_

# *cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy* +
_round-robin_ +
_round-robin_
----

. Verify that the namespaces are created and properly discoverd on the host:

+
----
# nvme list
Node         SN                   Model                  Namespace Usage              Format FW Rev
---------------- -------------------- ---------------------------------------- --------- ------------------
/dev/nvme0n1 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 1        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n10 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 10      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n11 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 11      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n12 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 12      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n13 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 13      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n14 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 14      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n15 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 15      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n16 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 16      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n17 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 17      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n18 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 18      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n19 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 19      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n2 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 2        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n20 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 20      37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n3 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 3        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n4 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 4        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n5 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 5        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n6 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 6        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n7 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 7        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n8 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 8        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF
/dev/nvme0n9 81Ec-JRMlkL9AAAAAAAB NetApp ONTAP Controller 9        37.58 GB / 37.58 GB 4 KiB + 0 B FFFFFFFF

----

. Verify that the controller state of each path is live and have proper ANA status
+
----
# nvme list-subsys /dev/nvme0n1 +
nvme-subsys0 - NQN=http://nqn.1992-08.com/[nqn.1992-08.com].netapp:sn.b79f5c6e4d0911edb3a0d039ea243511:subsystem.nvme_1 +
\ +
+- nvme214 fc traddr=nn-0x20e0d039ea243510:pn-0x20e4d039ea243510 host_traddr=nn-0x200000109bf0447b:pn-0x100000109bf0447b live non-optimized +
+- nvme219 fc traddr=nn-0x20e0d039ea243510:pn-0x20e2d039ea243510 host_traddr=nn-0x200000109bf0447c:pn-0x100000109bf0447c live optimized +
+- nvme223 fc traddr=nn-0x20e0d039ea243510:pn-0x20e1d039ea243510 host_traddr=nn-0x200000109bf0447b:pn-0x100000109bf0447b live optimized +
+- nvme228 fc traddr=nn-0x20e0d039ea243510:pn-0x20e3d039ea243510 host_traddr=nn-0x200000109bf0447c:pn-0x100000109bf0447c live non-optimized
----

. Verify the NetApp plug-in displays proper values for each ONTAP namespace device
+
----
. # *nvme netapp ontapdevices -o column* 
_Device Vserver Namespace Path NSID UUID Size 
---------------- ------------------------- -------------------------------------------------- ---- -------------------------------------- --------- +
/dev/nvme0n1 LPE36002_ASA_BL /vol/fcnvme_1_0_0/fcnvme_ns 1 ae10e16d-1fa4-49c2-8594-02bf6f3b1af1 37.58GB +
/dev/nvme0n10 LPE36002_ASA_BL /vol/fcnvme_1_0_9/fcnvme_ns 10 2cf00782-e2bf-40fe-8495-63e4501727cd 37.58GB +
/dev/nvme0n11 LPE36002_ASA_BL /vol/fcnvme_1_1_9/fcnvme_ns 11 fbefbe6c-90fe-46a2-8a51-47bad9e2eb95 37.58GB +
/dev/nvme0n12 LPE36002_ASA_BL /vol/fcnvme_1_1_0/fcnvme_ns 12 0e9cc8fa-d821-4f1c-8944-3003dcded864 37.58GB +
/dev/nvme0n13 LPE36002_ASA_BL /vol/fcnvme_1_1_1/fcnvme_ns 13 31f03b13-aaf9-4a3f-826b-d126ef007991 37.58GB +
/dev/nvme0n14 LPE36002_ASA_BL /vol/fcnvme_1_1_8/fcnvme_ns 14 bcf4627c-5bf9-4a51-a920-5da174ec9876 37.58GB +
/dev/nvme0n15 LPE36002_ASA_BL /vol/fcnvme_1_1_7/fcnvme_ns 15 239fd09d-11db-46a3-8e94-b5ebe6eb2421 37.58GB +
/dev/nvme0n16 LPE36002_ASA_BL /vol/fcnvme_1_1_2/fcnvme_ns 16 1d8004df-f2e8-48c8-8ccb-ce45f18a15ae 37.58GB +
/dev/nvme0n17 LPE36002_ASA_BL /vol/fcnvme_1_1_3/fcnvme_ns 17 4f7afbcf-3ace-4e6c-9245-cbf5bd155ef4 37.58GB +
/dev/nvme0n18 LPE36002_ASA_BL /vol/fcnvme_1_1_4/fcnvme_ns 18 b022c944-6ebf-4986-a28c-8d9e8ec130c9 37.58GB +
/dev/nvme0n19 LPE36002_ASA_BL /vol/fcnvme_1_1_5/fcnvme_ns 19 c457d0c7-bfea-43aa-97ef-c749d8612a72 37.58GB +
/dev/nvme0n2 LPE36002_ASA_BL /vol/fcnvme_1_0_1/fcnvme_ns 2 d2413d8b-e82e-4412-89d3-c9a751ed7716 37.58GB +
/dev/nvme0n20 LPE36002_ASA_BL /vol/fcnvme_1_1_6/fcnvme_ns 20 650e0d93-967d-4415-874a-36bf9c93c952 37.58GB +
/dev/nvme0n3 LPE36002_ASA_BL /vol/fcnvme_1_0_2/fcnvme_ns 3 09d89d9a-7835-423f-93e7-f6f3ece1dcbc 37.58GB +
/dev/nvme0n4 LPE36002_ASA_BL /vol/fcnvme_1_0_3/fcnvme_ns 4 d8e99326-a67c-469f-b3e9-e0e4a38c8a76 37.58GB +
/dev/nvme0n5 LPE36002_ASA_BL /vol/fcnvme_1_0_4/fcnvme_ns 5 c91c71f9-3e04-4844-b376-30acab6311f1 37.58GB +
/dev/nvme0n6 LPE36002_ASA_BL /vol/fcnvme_1_0_5/fcnvme_ns 6 4e8b4345-e5b1-4aa4-ae1a-adf0de2879ea 37.58GB +
/dev/nvme0n7 LPE36002_ASA_BL /vol/fcnvme_1_0_6/fcnvme_ns 7 ef715a16-a946-4bb8-8735-74f214785874 37.58GB +
/dev/nvme0n8 LPE36002_ASA_BL /vol/fcnvme_1_0_7/fcnvme_ns 8 4b038502-966c-49fd-9631-a17f23478ae0 37.58GB +
/dev/nvme0n9 LPE36002_ASA_BL /vol/fcnvme_1_0_8/fcnvme_ns 9 f565724c-992f-41f6-83b5-da1fe741c09b 37.58GB_
----
+
----
. # *nvme netapp ontapdevices -o json* +
{ 
"ONTAPdevices" : [ +
\{ +
"Device" : "/dev/nvme0n1", +
"Vserver" : "LPE36002_ASA_BL", +
"Namespace_Path" : "/vol/fcnvme_1_0_0/fcnvme_ns", +
"NSID" : 1, +
"UUID" : "ae10e16d-1fa4-49c2-8594-02bf6f3b1af1", +
"Size" : "37.58GB", +
"LBA_Data_Size" : 4096, +
"Namespace_Size" : 9175040 +
}, +
\{ +
"Device" : "/dev/nvme0n10", +
"Vserver" : "LPE36002_ASA_BL", +
"Namespace_Path" : "/vol/fcnvme_1_0_9/fcnvme_ns", +
"NSID" : 10, +
"UUID" : "2cf00782-e2bf-40fe-8495-63e4501727cd", +
"Size" : "37.58GB", +
"LBA_Data_Size" : 4096, +
"Namespace_Size" : 9175040 +
}, +
\{ +
"Device" : "/dev/nvme0n11", +
"Vserver" : "LPE36002_ASA_BL", +
"Namespace_Path" : "/vol/fcnvme_1_1_9/fcnvme_ns", +
"NSID" : 11, +
"UUID" : "fbefbe6c-90fe-46a2-8a51-47bad9e2eb95", +
"Size" : "37.58GB", +
"LBA_Data_Size" : 4096, +
"Namespace_Size" : 9175040 +
}, +
\{ +
"Device" : "/dev/nvme0n12", +
"Vserver" : "LPE36002_ASA_BL", +
"Namespace_Path" : "/vol/fcnvme_1_1_0/fcnvme_ns", +
"NSID" : 12, +
"UUID" : "0e9cc8fa-d821-4f1c-8944-3003dcded864", +
"Size" : "37.58GB", +
"LBA_Data_Size" : 4096, +
"Namespace_Size" : 9175040 +
}, +
\{ +
"Device" : "/dev/nvme0n13", +
"Vserver" : "LPE36002_ASA_BL", +
"Namespace_Path" : "/vol/fcnvme_1_1_1/fcnvme_ns", +
"NSID" : 13, +
"UUID" : "31f03b13-aaf9-4a3f-826b-d126ef007991", +
"Size" : "37.58GB", +
"LBA_Data_Size" : 4096, +
"Namespace_Size" : 9175040 +
},_

----

== Troubleshooting

Before commencing any troubleshooting for any NVMe/FC failures, make sure that you are running a configuration that is compliant to the IMT specifications and then proceed with the next steps to debug any host side issues.

=== LPFC verbose logging

.Steps

. You can set the `lpfc_log_verbose` driver setting to any of the following values to log NVMe/FC events:
+
----

#define LOG_NVME 0x00100000 /* NVME general events. */ 
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */ 
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */ 
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */ 

----
+
. After setting any of these values, run `dracut-f` command to recreate the `initramfs` and reboot the host.

. After rebooting, verify the settings:
+
----
# cat /etc/modprobe.d/lpfc.conf 
options lpfc lpfc_log_verbose=0xf00083 


# cat /sys/module/lpfc/parameters/lpfc_log_verbose 
15728771 
----

=== qla2xxx verbose logging

There is no similar specific qla2xxx logging for NVMe/FC as for lpfc driver. Therefore, you may set the general qla2xxx logging level using the following steps:

.Steps

. Append the `ql2xextended_error_logging=0x1e400000` value to the corresponding `modprobe qla2xxx conf` file.

. Recreate the `initramfs` by running `dracut -f` command and then reboot the host.

. After reboot, verify that the verbose logging has been applied as follows:
+
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----

== Known issues 

[options="header", cols="20, 20, 50"]
|===
|BURTS |Title |Description |Oracle Bugzilla
|1517321 |Oracle Linux 8.x NVMe-oF Hosts create duplicate Persistent Discovery Controllers a|
On OL 8.X NVME-of hosts, Persistent Discovery Controllers (PDCs) are created by passing the -p option to the 'nvme discover' command. For a given initiator-target combination, only one PDC is expected to be created with each invocation of the 'nvme discover' command. However, beginning with ONTAP 9.10.1, Oracle Linux (OL) 8.x NVMe-oF hosts end up creating duplicate PDCs with each invocation of the 'nvme discover'
command with the -p option. This leads to wastage of resources on both the host and the target.

|https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=18118[18118^]
|===



=== Common nvme-cli errors and workarounds

The errors displayed by `nvme-cli` during nvme discover, nvme connect or nvme connect-all operations and the workarounds are shown in the following table:

[options="header", cols="20, 20, 50"]
|===
|Errors displayed by `nvme-cli`  | Probable cause | Workaround
| `Failed to write to /dev/nvme-fabrics: Invalid argument`
|Incorrect syntax
|Make sure you are using the correct syntax for the above nvme commands.
|`Failed to write to /dev/nvme-fabrics: No such file or directory`  |Multiple issues could trigger this.
Providing wrong arguments to the nvme commands is one of the common causes.
a| * Make sure you have passed the correct arguments (such as, correct WWNN string, WWPN string, and more) to the commands.
* If the arguments are correct, but you still see this error, check if the `/sys/class/scsi_host/host*/nvme_info` output is proper, the NVMe initiator showing as `Enabled`, and the NVMe/FC target LIFs properly showing up here under the remote ports sections.
Example:
+
----

# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----

* If the target LIFs don't show up as above in the nvme_info output, check the `/var/log/messages` and `dmesg` output for any suspicious NVMe/FC failures, and report or fix accordingly.

|`No discovery log entries to fetch`  a|Generally seen if the `/etc/nvme/hostnqn` string has not been added to the corresponding subsystem on the NetApp array or an incorrect `hostnqn` string has been added to the respective subsystem. a|Make sure the exact `/etc/nvme/hostnqn` string is added to the corresponding subsystem on the NetApp array (verify through the `vserver nvme subsystem host show` command).

|`Failed to write to /dev/nvme-fabrics: Operation already in progress`  a|Noticed if the controller associations or specified operations are already created or in the process of being created. This could happen as part of the auto-connect scripts installed above.
a|None. For `nvme discover`, try running this command after some time. For `nvme connect` and `connect-all`, run the `nvme list` command to verify that the namespace devices are already created and displayed on the host.

|===

=== When to contact technical support
If you are still facing issues, please collect the following files and command outputs and contact technical support for further triage:

----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----
