---
sidebar: sidebar
permalink: nvme_rhel_82.html
keywords: nvme, linux, rhel, red hat, enterprise
summary: How to Configure NVMe/FC Host for RHEL 8.2 with ONTAP
---

= NVMe/FC Host Configuration for RHEL 8.2 with ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Supportability

NVMe/FC is supported on ONTAP 9.6 or later for RHEL 8.2. The RHEL 8.2 host runs both NVMe and SCSI traffic through the same fibre channel (FC) initiator adapter ports. See the link:https://hwu.netapp.com/Home/Index[Hardware Universe^] for a list of supported FC adapters and controllers. For the most current list of supported configurations and versions, see the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix^].

== Known limitations

For RHEL 8.2, in-kernel NVMe multipath remains disabled by default. Therefore, you need to enable it manually. Steps for doing so are provided in the next section, "Enabling NVMe/FC on RHEL 8.2".

== Enable NVMe/FC on RHEL 8.2

. Install Red Hat Enterprise Linux 8.2 GA on the server.
+
If you are upgrading from RHEL 8.1 to RHEL 8.2 using `yum update/upgrade`, your `/etc/nvme/host*` files might be lost. To avoid file loss, do the following:

include::_include/nvme/reuse_nvme_enabling_step1_substeps.adoc[]

. After the installation is complete, verify that you are running the specified Red Hat Enterprise Linux kernel.
+
----
# uname -r
4.18.0-193.el8.x86_64
----
+
See the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix^] for the most current list of supported versions.

. Install the nvme-cli package.
+
----
# rpm -qa|grep nvme-cli
nvme-cli-1.9.5.el8.x86_64
----

. Enable in-kernel NVMe multipath.
+
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-193.el8.x86_64
----

.	On the RHEL 8.2 host, check the host NQN string at /etc/nvme/hostnqn and verify that it matches the host NQN string for the corresponding subsystem on the ONTAP array.
+
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1


::> vserver nvme subsystem host show -vserver vs_fcnvme_141
Vserver      Subsystem        Host           NQN
----------- --------------- ----------- ---------------
  vs_fcnvme_141
    nvme_141_1
        nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+
If the host NQN strings do not match, use the `vserver modify` command to update the host NQN string on the corresponding ONTAP array subsystem to match to host NQM string from /etc/nvme/hostnqn on the host.

. Reboot the host.
+
. Update the `enable_foreign` setting _(optional)_.
+
If you intend to run both NVMe and SCSI traffic on the same RHEL 8.2 co-existent host, we recommend you use in-kernel NVMe multipath for ONTAP namespaces and dm-multipath for ONTAP LUNs, respectively. You should aslo blacklist the ONTAP namespaces in dm-multipath to prevent dm-multipath from claiming these namespace devices. You do this by adding the `enable_foreign` setting to the /etc/multipath.conf, as shown below.
+
----
# cat /etc/multipath.conf
defaults {
   enable_foreign NONE
}
----

. Restart the multipathd daemon by running a `systemctl restart multipathd`.

== Configure the Broadcom FC adapter for NVMe/FC

include::_include/nvme/reuse_configuring_broadcom_for_rhel_nvme_part1.adoc[]

. Verify that you are using the recommended Broadcom lpfc firmware as well as the inbox driver.
+
----
# cat /sys/class/scsi_host/host*/fwrev
12.6.182.8, sli-4:2:c
12.6.182.8, sli-4:2:c
----
+
----
# cat /sys/module/lpfc/version
0:12.6.0.2
----

include::_include/nvme/reuse_configuring_broadcom_for_rhel_nvme_part2.adoc[]

==	Validate NVMe/FC

include::_include/nvme/reuse_validating_nvme_fc_rhel.adoc[]

== LPFC Verbose Logging

include::_include/nvme/reuse_nvme_verbose_logging.adoc[]
