---
sidebar: sidebar
permalink: nvme-rockylinux-92.html
keywords: nvme, linux, rocky linux, enterprise
summary: How to Configure NVMe-oF Host for Rocky Linux 9.2 with ONTAP
---
= Configure Rocky Linux 9.2 for NVMe-oF with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/nvme/nvme-introduction.adoc[]

This document describes how to configure NVMe over Fabrics (NVMe-oF) hosts for Rocky Linux 9.2. For more support and feature information, see link:hu-nvme-index.html[NVME-oF Overview^]. The following are known limitations for Rocky Linux 9.2:

* SAN booting using the NVMe-oF protocol is not currently supported.

== Step 1: Optionally, enable SAN booting

include::_include/nvme/enable-san-booting.adoc[]

== Step 2: Verify the software version and NVMe configuration

include::_include/nvme/verify-software-version-introduction.adoc[]

.Steps

. Install Rocky Linux 9.2 on the server. After the installation is complete, verify that you are running the required Rocky Linux 9.2 kernel: 
+
[source,cli]
----
uname -r
----
+
Example Rocky Linux kernel version:
+
----
5.14.0-570.12.1.el9_6.x86_64
----

include::_include/nvme/linux-validate-software-version-rockylinux.adoc[]

== Step 3: Configure NVMe/FC and NVMe/TCP

include::_include/nvme/nvme-configure.adoc[]

== Step 4: Optionally, enable 1MB I/O for NVMe/FC

include::_include/nvme/nvme-enable-1mb-io.adoc[]

== Step 5: Verify the multipathing configuration

include::_include/nvme/nvme-validate-nvme-of-rocky-linux.adoc[]

== Step 6: Review the known issues

There are no known issues.

// 2022,12-06, Jira IEOPS-690
// JIRA-1289 20-Sep-2023
