---
sidebar: sidebar
permalink: nvme-windows-2025.html
keywords: nvme, windows, enterprise
summary: NVMe/FC Host Configuration for Windows Server 2052 with ONTAP
---
= Configure Windows Server 2025 with NVMe/FC for ONTAP
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can configure NVMe over Fibre Channel (NVMe/FC) on hosts running Windows Server 2025 for operation with ONTAP LUNs.

.About this task
You can use the following support with the NVMe/FC host configuration for Windows 2025. You should also review the known limitations before starting the configuration process.

* Support available:
+
Beginning with ONTAP 9.10.1, NVMe/FC is supported for Windows Server 2025.

* Known limitations:
+
Windows Failover Cluster (WFC) isn't supported with NVMe/FC because ONTAP doesn't currently support persistent reservations with NVMe/FC.
+
NOTE: Broadcom ships an external driver for Windows NVMe/FC that is a translational SCSI ⇄ NVMe driver and not a true NVMe/FC driver. The translational overhead doesn't necessarily impact performance, but it does negate the performance benefits of NVMe/FC. As a result,  NVMe/FC and FCP performance is the same on Windows servers, unlike other operating systems such as Linux, where NVMe/FC performance is significantly better than that of FCP.

== Enable NVMe/FC 

include::_include/nvme/reuse_enabling_on_windows_init_host.adoc[]

== Configure the Broadcom FC adapter

include::_include/nvme/reuse_configuring_broadcom_for_windows.adoc[]

=== Enable MPIO for NVMe devices

include::_include/nvme/reuse_enabling_mpio_for_nvme_on_windows_host.adoc[]

== Validate the NVMe/FC configuration

include::_include/nvme/reuse_validating_nvme_fc_windows.adoc[]
