---
sidebar: sidebar
permalink: nvme-rhel-82.html
keywords: nvme, linux, rhel, red hat, enterprise
summary: How to Configure NVMe/FC Host for RHEL 8.2 with ONTAP
---
= Configure RHEL 8.2 for NVMe-oF with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/nvme/nvme-introduction.adoc[]

.About this task 
You can use the following support and features with the NVMe-oF host configuration for Red Hat Enterprise Linux (RHEL) 8.2. You should also review the known limitations before starting the configuration process.

* Support available:
** Beginning with ONTAP 9.6, NVMe/FC is supported for Red Hat Enterprise Linux (RHEL) 8.2. The RHEL 8.2 host runs both NVMe and SCSI traffic through the same FC initiator adapter ports. See the link:https://hwu.netapp.com/Home/Index[Hardware Universe^] for a list of supported FC adapters and controllers.
** Beginning with RHEL 8.2, the NetApp plug-in in the native `nvme-cli` package displays ONTAP details for both NVMe/FC and NVMe/TCP namespaces.
+
For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].
* Features available:
**	Beginning with RHEL 8.2, the native `nvme-cli` package includes `nvme-fc auto-connect` scripts, elimintating the need to install external vendor-provided outbox auto-connect scripts.
** A native `udev` rule is also provided in the `nvme-cli` package, which enables round-robin load balancing for NVMe multipath. Therefore, you do not need to manually create the rule (as per RHEL 8.1).
* Known limitations: 
** In-kernel NVMe multipath is disabled by default on NVMe-oF hosts in RHEL 8.2, so you must enable it manually.
** SAN booting using the NVMe-oF protocol is not currently supported.

== Step 1: Optionally, enable SAN booting

include::_include/nvme/enable-san-booting.adoc[]

== Enable NVMe/FC 

You can use the following procedure to enable NVMe/FC.

.Steps

. Install Red Hat Enterprise Linux 8.2 GA on the server.
+
. If you are upgrading from RHEL 8.1 to RHEL 8.2 using `yum update/upgrade`, your `/etc/nvme/host*` files might be lost. To avoid the file loss, do the following:

include::_include/nvme/reuse_nvme_enabling_step1_substeps.adoc[]

. After the installation is complete, verify that you are running the specified Red Hat Enterprise Linux kernel.
+
----
# uname -r
4.18.0-193.el8.x86_64
----
+
See the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^] for the current list of supported versions.

. Install the nvme-cli package.
+
----
# rpm -qa|grep nvme-cli
nvme-cli-1.9.5.el8.x86_64
----

. Enable in-kernel NVMe multipath.
+
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-193.el8.x86_64
----

.	On the RHEL 8.2 host, check the host NQN string at `/etc/nvme/hostnqn` and verify that it matches the host NQN string for the corresponding subsystem on the ONTAP array.
+
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1


::> vserver nvme subsystem host show -vserver vs_fcnvme_141
Vserver      Subsystem        Host           NQN
----------- --------------- ----------- ---------------
  vs_fcnvme_141
    nvme_141_1
        nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+
If the host NQN strings do not match, use the `vserver modify` command to update the host NQN string on the corresponding ONTAP array subsystem to match to host NQN string from `/etc/nvme/hostnqn` on the host.

. Reboot the host.
+
. Update the `enable_foreign` setting _(optional)_.
+
If you intend to run both NVMe and SCSI traffic on the same RHEL 8.2 host, NetApp recommends using in-kernel NVMe multipath for ONTAP namespaces and dm-multipath for ONTAP LUNs respectively. You should also blacklist the ONTAP namespaces in dm-multipath to prevent dm-multipath from claiming these namespace devices. You can do this by adding the `enable_foreign` setting to the `/etc/multipath.conf`, as shown below.
+
----
# cat /etc/multipath.conf
defaults {
   enable_foreign NONE
}
----

. Restart the multipathd daemon by running a `systemctl restart multipathd`.

== Configure the Broadcom FC adapter for NVMe/FC

You can use the following procedure to configure a Broadcom FC adapter.

include::_include/nvme/reuse_configuring_broadcom_for_rhel_nvme_part1.adoc[]

. Verify that you are using the recommended Broadcom lpfc firmware as well as the inbox driver.
+
----
# cat /sys/class/scsi_host/host*/fwrev
12.6.182.8, sli-4:2:c
12.6.182.8, sli-4:2:c
----
+
----
# cat /sys/module/lpfc/version
0:12.6.0.2
----

include::_include/nvme/reuse_configuring_broadcom_for_rhel_nvme_part2.adoc[]

== Step 4: Optionally, enable 1MB I/O 

include::_include/nvme/reuse_nvme_enabling_broadcom_1mb_size.adoc[]

==	Validate NVMe/FC

You can use the following procedure to validate NVMe/FC.

.Steps

include::_include/nvme/reuse_validating_nvme_fc_rhel.adoc[]

== Step 6: Review the known issues

There are no known issues.

// JIRA-1289 20-Sep-2023


