---
sidebar: sidebar
permalink: nvme_ol_89.html
keywords: nvme, oracle linux, 8.9, host configuration
summary: NVMe-oF Host Configuration for Oracle Linux 8.9 with ONTAP
---
= NVMe-oF Host Configuration for Oracle Linux 8.9 with ONTAP
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NVMe over Fabrics (NVMe-oF), including NVMe over Fibre Channel (NVMe/FC) and other transports, is supported with Oracle Linux 8.9 with Asymmetric Namespace Access (ANA). In NVMe-oF environments, ANA is the equivalent of ALUA multipathing in iSCSI and FC environments and is implemented with in-kernel NVMe multipath. 

The following support is available for the NVMe-oF host configuration for Oracle Linux 8.9 with ONTAP:

* Support for NVMe over TCP (NVMe/TCP) in addition to NVMe/FC. The NetApp plug-in in the native `nvme-cli` package displays the ONTAP details for both NVMe/FC and NVMe/TCP namespaces.

* Both NVMe and SCSI traffic can be run on the same host. Therefore, you can configure dm-multipath for SCSI mpath devices for SCSI LUNs, whereas you might use NVMe multipath to configure NVMe-oF namespace devices on the host.

* There is no sanlun support for NVMe-oF. Therefore, there is no host utility support for NVMe-oF on an Oracle Linux 8.9 host. You can rely on the NetApp plug-in included in the native `nvme-cli` package for all NVMe-oF transports.

For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].

== Features 

Oracle Linux 8.9 has in-kernel NVMe multipath enabled for NVMe namespaces by default; therefore, there is no need for explicit settings.

== Known limitations

SAN booting using the NVMe-oF protocol is currently not supported.

== Validate software versions

Validate the minimum supported Oracle Linux 8.9 software versions.

.Steps

. Install Oracle Linux 8.9 GA on the server. After the installation is complete, verify that you are running the specified Oracle Linux 8.9 GA kernel:
+
----
# uname -r
----
+
*Example output:*
+
----
5.15.0-200.131.27.el8uek.x86_64
----

. Install the `nvme-cli` package:
+
----
# rpm -qa|grep nvme-cli
----
+
*Example output:*
+
----
nvme-cli-1.16-9.el8.x86_64
----

. On the Oracle Linux 8.9 host, check the `hostnqn` string at `/etc/nvme/hostnqn`: 
+
----
# cat /etc/nvme/hostnqn
----
+
*Example output:*
+
----
nqn.2014-08.org.nvmexpress:uuid:edd38060-00f7-47aa-a9dc-4d8ae0cd969a
----

. Verify that the `hostnqn` string matches the `hostnqn` string for the corresponding subsystem on the ONTAP array:
+
----
::> vserver nvme subsystem host show -vserver vs_nvme177
----
+
*Example output:*
+
----
Vserver     Subsystem          Host NQN
----------- --------------- ----------------------------------------------------------
vs_nvme177  nvme_ss_ol_1       nqn.2014-08.org.nvmexpress:uuid:edd38060-00f7-47aa-a9dc-4d8ae0cd969a 
----
+
[NOTE]
If the `hostnqn` strings do not match, you can use the `vserver modify` command to update the `hostnqn` string on your corresponding ONTAP array subsystem to match the `hostnqn` string from `/etc/nvme/hostnqn` on the host.

. Reboot the host. 
+
[NOTE]
====
If you intend to run both NVMe and SCSI co-existent traffic on the same host, NetApp recommends using the in-kernel NVMe multipath for ONTAP namespaces and `dm-multipath` for ONTAP LUNs respectively. This means that the ONTAP namespaces should be excluded from `dm-multipath` to prevent `dm-multipath` from claiming these namespace devices. You can add the `enable_foreign` setting to the `/etc/multipath.conf` file: 

----
# cat /etc/multipath.conf 

defaults { 
  enable_foreign     NONE 
} 
----

Restart the multipathd daemon by running a `systemctl restart multipathd` command. This allows the new setting to take effect. 

====

== Configure NVMe/FC

Configure NVMe/FC for Broadcom/Emulex adapters or Marvell/Qlogic adapters.

[role="tabbed-block"]
=====
.Broadcom/Emulex
--
.Steps

. Verify that you are using the supported adapter model:
+
----
# cat /sys/class/scsi_host/host*/modelname
----
+
*Example output:*
+
----
LPe32002-M2
LPe32002-M2
----
+
----
# cat /sys/class/scsi_host/host*/modeldesc
----
+
*Example output:*
+
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----

. Verify that you are using the recommended Broadcom `lpfc` firmware and inbox driver:
+
----
# cat /sys/class/scsi_host/host*/fwrev
14.2.539.16, sli-4:2:c
14.2.539.16, sli-4:2:c
----
+
----
# cat /sys/module/lpfc/version
0:14.2.0.5 
----
+
For the current list of supported adapter driver and firmware versions, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].

. Verify that `lpfc_enable_fc4_type` is set to `3`:
+
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----

. Verify that the initiator ports are up and running, and that you can see the target LIFs:
+
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b3c081f
0x100000109b3c0820 
----
+
----

# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
.Show example
[%collapsible]
====
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
====
--

.Marvell/QLogic FC Adapter for NVMe/FC
--

The native inbox qla2xxx driver included in the Oracle Linux 8.9 GA kernel has the latest fixes. These fixes are essential for ONTAP support.

.Steps

.  Verify that you are running the supported adapter driver and firmware versions:
+
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2742 FW:v9.12.00 DVR:v10.02.08.100-k
QLE2742 FW:v9.12.00 DVR:v10.02.08.100-k
----

. Verify that `ql2xnvmeenable` is set. This enables the Marvell adapter to function as an NVMe/FC initiator:
+
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----
--
=====

=== Enable 1MB I/O size (Optional)

include::_include/nvme/nvme-enabling-broadcom-1mb-size.adoc[]

== Configure NVMe/TCP

NVMe/TCP does not have auto-connect functionality. Therefore, if a path goes down and is not reinstated within the default time out period of 10 minutes, NVMe/TCP cannot automatically reconnect. To avoid this scenario, you should set the retry period for storage failover events by using the following procedure. 

.Steps

. Verify that the initiator port can fetch the discovery log page data across the supported NVMe/TCP LIFs:
+
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Show example output
[%collapsible]
====
----
#  nvme discover -t tcp -w 192.168.6.13 -a 192.168.6.15
Discovery Log Number of Records 6, Generation counter 8
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: unrecognized
treq: not specified
portid: 0
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.1c6ac66338e711eda41dd039ea3ad566:discovery
traddr: 192.168.6.17
sectype: none
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: unrecognized
treq: not specified
portid: 1
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.1c6ac66338e711eda41dd039ea3ad566:discovery
traddr: 192.168.5.17
sectype: none
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: unrecognized
treq: not specified
portid: 2
trsvcid: 8009
subnqn: nqn.1992-08.com.netapp:sn.1c6ac66338e711eda41dd039ea3ad566:discovery
traddr: 192.168.6.15
sectype: none
=====Discovery Log Entry 3======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.1c6ac66338e711eda41dd039ea3ad566:subsystem.host_95
traddr: 192.168.6.17
sectype: none
..........
----
====

. Verify that the other NVMe/TCP initiator-target LIF combinations can successfully fetch discovery log page data: 
+
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
*Example output:*
+
----
# nvme discover -t tcp -w 192.168.6.1 -a 192.168.6.10  
# nvme discover -t tcp -w 192.168.6.1 -a 192.168.6.11 
# nvme discover -t tcp -w 192.168.5.1 -a 192.168.5.10 
# nvme discover -t tcp -w 192.168.5.1 -a 192.168.5.11
----

. Run the `nvme connect-all` command across all the supported NVMe/TCP initiator-target LIFs across the nodes:
+
----
nvme connect-all -t tcp -w host-traddr -a traddr -l <ctrl_loss_timeout_in_seconds>
----
+
*Example output:*
+
----
#	nvme	connect-all	-t	tcp	-w	192.168.5.1	-a	192.168.5.10	-l -1    
#	nvme	connect-all	-t	tcp	-w	192.168.5.1	-a	192.168.5.11 	-l -1
#	nvme	connect-all	-t	tcp	-w	192.168.6.1	-a	192.168.6.10	-l -1
#	nvme	connect-all	-t	tcp	-w	192.168.6.1	-a	192.168.6.11	-l -1
----
+
[NOTE]
NetApp recommends setting the `ctrl-loss-tmo` option to `-1` so that the NVMe/TCP initiator attempts to reconnect indefinitely in the event of a path loss.

== Validate NVMe-oF

You can use the following procedure to validate NVMe-oF.

.Steps

. Verify that in-kernel NVMe multipath is enabled:
+
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----

. Verify that the appropriate NVMe-oF settings (such as `model` set to `NetApp ONTAP Controller` and load balancing `iopolicy` set to `round-robin`) for the respective ONTAP namespaces correctly reflect on the host:
+
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----

. Verify that the namespaces are created and correctly discovered on the host:
+
----
# nvme list
----
+
*Example output:*
+
----
Node         SN                   Model                          
---------------------------------------------------------  
/dev/nvme0n1 814vWBNRwf9HAAAAAAAB NetApp ONTAP Controller
/dev/nvme0n2 814vWBNRwf9HAAAAAAAB NetApp ONTAP Controller
/dev/nvme0n3 814vWBNRwf9HAAAAAAAB NetApp ONTAP Controller
                                  


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 85.90 GB / 85.90 GB  4 KiB + 0 B   FFFFFFFF
2                 85.90 GB / 85.90 GB  24 KiB + 0 B  FFFFFFFF
3	                85.90 GB / 85.90 GB  4 KiB + 0 B   FFFFFFFF
      
----

. Verify that the controller state of each path is live and has the correct ANA status:
+
[role="tabbed-block"]
====
.NVMe/FC
--
----
# nvme list-subsys /dev/nvme0n1
----

*Example output:*

----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.5f5f2c4aa73b11e9967e00a098df41bd:subsystem.nvme_ss_ol_1
\
+- nvme0 fc traddr=nn-0x203700a098dfdd91:pn-0x203800a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live non-optimized
+- nvme1 fc traddr=nn-0x203700a098dfdd91:pn-0x203900a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live non-optimized 
+- nvme2 fc traddr=nn-0x203700a098dfdd91:pn-0x203a00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x203700a098dfdd91:pn-0x203d00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized



----
--

.NVMe/TCP
--
----
nvme list-subsys /dev/nvme1n22
----
*Example output*
----
nvme-subsys0 - NQN=nqn.1992- 08.com.netapp: sn.44986b09cadc11eeb309d039eab31e9d:subsystem.ol_nvme
\
+- nvme1 tcp traddr=192.168.5.11 trsvcid=4420 host_traddr=192.168.5.1 src_addr=192.168.5.1 live non-optimized
+- nvme2 tcp traddr=192.168.5.10 trsvcid=4420 host_traddr=192.168.5.1 src_addr=192.168.5.1 live optimized
+- nvme3 tcp traddr=192.168.6.11 trsvcid=4420 host_traddr=192.168.6.1 src_addr=192.168.6.1 live non-optimized
+- nvme4 tcp traddr=192.168.6.10 trsvcid=4420 host_traddr=192.168.6.1 src_addr=192.168.6.1 live  optimized


----
--
====

. Verify that the NetApp plug-in displays the correct values for each ONTAP namespace device:
+
[role="tabbed-block"]
====
.Column
--
----
# nvme netapp ontapdevices -o column
----

*Example output:*

----
Device        Vserver     Namespace Path                                                          
------------  ----------  ----------------- 
/dev/nvme0n1	vs_nvme177	/vol/vol1/ns1
/dev/nvme0n2	vs_nvme177	/vol/vol2/ns2
/dev/nvme0n3	vs_nvme177	/vol/vol3/ns3
          


NSID     UUID                                   Size
-------- -------------------------------------- -----------
1	       72b887b1-5fb6-47b8-be0b-33326e2542e2	  85.90GB
2	       04bf9f6e-9031-40ea-99c7-a1a61b2d7d08	  85.90GB
3	       264823b1-8e03-4155-80dd-e904237014a4	  85.90GB



----
--
.JSON
--
----
# nvme netapp ontapdevices -o json
----
*Example output*
----
{
"ONTAPdevices" : [
{
"Device" : "/dev/nvme0n1", "Vserver" : "vs_nvme177",
"Namespace_Path" : "/vol/vol1/ns1",
"NSID" : 1,
"UUID" : "72b887b1-5fb6-47b8-be0b-33326e2542e2", "Size" : "85.90GB",
"LBA_Data_Size" : 4096,
"Namespace_Size" : 5242880
},
{
"Device" : "/dev/nvme0n2", "Vserver" : "vs_nvme177",
"Namespace_Path" : "/vol/vol2/ns2",
 "NSID" : 2,
"UUID" : "04bf9f6e-9031-40ea-99c7-a1a61b2d7d08", "Size" : "85.90GB",
"LBA_Data_Size" : 4096,
"Namespace_Size" : 20971520
},
{
"Device" : "/dev/nvme0n3", "Vserver" : "vs_nvme177",
"Namespace_Path" : "/vol/vol3/ns3",
 "NSID" : 3,
"UUID" : "264823b1-8e03-4155-80dd-e904237014a4", "Size" : "85.90GB",
"LBA_Data_Size" : 4096,
"Namespace_Size" : 20971520
},
]
}


----
--
====

== Known issues

The NVMe-oF host configuration for Oracle Linux 8.9 with ONTAP release has the following known issues:

[cols="1a,4a,4a, options="header"]
|===
|NetApp Bug ID	|Title	|Description	
|link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1517321[1517321^]

|Oracle Linux 8.9 NVMe-oF hosts create duplicate PDCs

|On Oracle Linux 8.9 NVMe-oF hosts, Persistent Discovery Controllers (PDCs) are created by passing the `-p` option to the `nvme discover` command. For a given initiator-target combination, each execution of the `nvme discover` command is expected to create one PDC. However, beginning with Oracle Linux 8.x, NVMe-oF hosts create duplicate. This wastes resources on both the host and the target.
|===

// 2024 SEP 2, ONTAPDOC-2345
// SME feeedback, finalize for writer on vacation
// JIRA-1289 20-Sep-2023