---
sidebar: sidebar
permalink: nvme_rockylinux_810.html
keywords: nvme, linux, rocky linux, enterprise
summary: How to Configure NVMe-oF Host for Rocky Linux 8.10 with ONTAP
---

= Configure Rocky Linux 8.10 with NVMe-oF for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can configure Rocky Linux 8.10 with NVMe protocols to manage ONTAP LUNs.
[.lead]
include::_include/nvme/nvme-introduction.adoc[] 

.About this task 
You can use the following support and features with the NVMe-oF host configuration for Rocky Linux 8.10. You should also review the known limitations before starting the configuration process.

* Support available:
** Support for NVMe over TCP (NVMe/TCP) in addition to NVMe over Fibre Channel (NVMe/FC). The NetApp plug-in in the native `nvme-cli` package displays ONTAP details for both NVMe/FC and NVMe/TCP namespaces.
** Running NVMe and SCSI traffic on the same host. For example, you can configure dm-multipath for SCSI mpath devices for SCSI LUNs and use NVMe multipath to configure NVMe-oF namespace devices on the host.
+
For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].
* Features available:
** Beginning with ONTAP 9.12.1, you can use secure in-band authentication for NVMe-oF with Rocky Linux 8.10.
** Rocky Linux 8.10 enables in-kernel NVMe multipath for NVMe namespaces by default, removing the need for explicit settings.
* Known limitations: 
** In-kernel NVMe multipath is disabled by default for Rocky Linux 8.10 NVMe-oF hosts. Therefore, you need to enable it manually.
** On Rocky Linux 8.10 hosts, NVMe/TCP is a technology preview feature due to open issues. Refer to the https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html-single/8.10_release_notes/index#technology-preview_file-systems-and-storage[Rocky Linux 8.10 Release Notes^] for details.
** SAN booting using the NVMe-oF protocol is currently not supported.

== Step 1: Validate software versions
include::_include/nvme/nvme-validate-software-versions.adoc[] 

== Step 2: Configure NVMe/FC
include::_include/nvme/nvme-configure-nvme-fc.adoc[]

== Step 3: Optionally, enable 1MB I/O 
include::_include/nvme/nvme-enable-1mb-io.adoc[] 

== Step 4: Configure NVMe/TCP
include::_include/nvme/nvme-configure-nvme-tcp.adoc[]

== Step 5: Validate NVMe-oF
include::_include/nvme/nvme-validate-nvme-of.adoc[] 

== Step 6: Set up secure in-band authentication
include::_include/nvme/nvme-secure-in-band-authentication.adoc[] 

== Known issues

The NVMe-oF host configuration for Rocky Linux 8.10 with ONTAP has the following known issue:

[cols="20,40,40",options="header"]
|===
|NetApp Bug ID	|Title	|Description	

|link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047[1479047^]	|Rocky Linux 8.10 NVMe-oF hosts create duplicate persistent discovery controllers	|On NVMe over Fabrics (NVMe-oF) hosts, you can use the "nvme discover -p" command to create Persistent Discovery Controllers (PDCs). When this command is used, only one PDC should be created per initiator-target combination.  However, if you are running Rocky Linux 8.10 on an NVMe-oF host, a duplicate PDC is created each time "nvme discover -p" is executed. This leads to unnecessary usage of resources on both the host and the target.
|===

// 2024 SEP 2, ONTAPDOC-2345