---
sidebar: sidebar
permalink: nvme-rockylinux-94.html
keywords: nvme, linux, rocky linux, enterprise
summary: How to Configure NVMe-oF Host for Rocky Linux 9.4 with ONTAP
---
= Configure Rocky Linux 9.4 with NVMe-oF for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/nvme/nvme-introduction.adoc[]

Learn how to configure NVMe over Fabrics (NVMe-oF) hosts for Rocky Linux 9.4. For more support and feature information, see link:hu-nvme-index.html[NVME-oF Overview^]. 

NVMe-oF with Rocky Linux 9.4 has no known limitations.

== Step 1: Optionally, enable SAN booting

include::_include/nvme/enable-san-booting.adoc[]

== Step 2: Verify the software version and NVMe configuration

include::_include/nvme/verify-software-version-introduction.adoc[]

.Steps

. Install Rocky Linux 9.4 on the server. After the installation is complete, verify that you are running the specified Rocky Linux 9.4 kernel: 
+
[source,cli]
----
uname -r
----
+
Example Rocky Linux kernel version:
+
----
5.14.0-570.12.1.el9_6.x86_64
----

include::_include/nvme/linux-validate-software-version-rockylinux.adoc[] 

== Step 3: Configure NVMe/FC and NVMe/TCP 

include::_include/nvme/nvme-configure.adoc[]

[NOTE]
====
Beginning with Rocky Linux 9.4, the setting for the NVMe/TCP `ctrl_loss_tmo timeout` is automatically set to "off". As a result:

include::_include/nvme/ctrl-loss-tmo-default-off.adoc[]
====

== Step 4: Optionally, enable 1MB I/O for NVMe/FC

include::_include/nvme/nvme-enabling-broadcom-1mb-size.adoc[] 

== Step 5: Verify the multipathing configuration

include::_include/nvme/nvme-validate-nvme-of-rocky-linux.adoc[]

== Step 6: Set up secure in-band authentication

include::_include/nvme/nvme-secure-in-band-authentication.adoc[]

== Step 7: Review the known issues

There are no known issues.


