---
sidebar: sidebar
permalink: nvme-rockylinux-95.html
keywords: nvme, linux, rocky linux, enterprise
summary: How to Configure NVMe-oF Host for Rocky Linux 9.5 with ONTAP
---
= Configure Rocky Linux 9.5 with NVMe-oF for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Rocky Linux 9.5 hosts support the NVMe/FC and NVMe/TCP protocols with Asymmetric Namespace Access (ANA). ANA is equivalent to asymmetric logical unit access (ALUA) multipathing in iSCSI and FCP environments and is implemented using the in-kernel NVMe multipath feature.

For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].

.About this task 
You can use the following support and features with the NVMe-oF host configuration for Rocky Linux 9.5. You should also review the known limitations before starting the configuration process.

* Support available:
** Support for NVMe over TCP (NVMe/TCP) in addition to NVMe over Fibre Channel (NVMe/FC). The NetApp plug-in in the native `nvme-cli` package displays ONTAP details for both NVMe/FC and NVMe/TCP namespaces.
** Running NVMe and SCSI traffic on the same host. For example, you can configure dm-multipath for SCSI mpath devices on SCSI LUNs and use NVMe multipath to configure NVMe-oF namespace devices on the host.
* Features available:
** Beginning with ONTAP 9.12.1, you can use secure in-band authentication for NVMe-oF with Rocky Linux 9.5.
** Rocky Linux 9.5 enables in-kernel NVMe multipath for NVMe namespaces by default, removing the need for explicit settings.

* Known limitations: 
** There are no known limitations.


== Step 1: Optionally, enable SAN booting
include::_include/nvme/enable-san-booting.adoc[]

== Step 2: Validate software versions
Use the following procedure to validate the minimum supported Rocky Linux 9.5 software versions.

.Steps

. Install Rocky Linux 9.5 on the server. After the installation is complete, verify that you are running the specified Rocky Linux 9.5 kernel: 
+
[source,cli]
----
uname -r
----
+
The following example shows a Rocky Linux kernel version:
+
----
5.14.0-570.12.1.el9_6.x86_64
----
[start=2]
include::_include/nvme/validate-software-version9-rockylinux-proxmox.adoc[] 

== Step 3: Configure NVMe/FC
include::_include/nvme/nvme-configure.adoc[]

== Step 4: Optionally, enable 1MB I/O 
include::_include/nvme/nvme-enable-1mb-io.adoc[]

== Step 5: Configure NVMe/TCP

include::_include/nvme/nvme-configure-nvme-tcp-rocky-linux.adoc[]

[NOTE]
====
Beginning with Rocky Linux 9.4, the setting for the NVMe/TCP `ctrl_loss_tmo timeout` is automatically set to "off". As a result:

include::_include/nvme/ctrl-loss-tmo-default-off.adoc[]
====

== Step 6: Validate NVMe-oF

include::_include/nvme/nvme-validate-nvme-of-rocky-linux.adoc[]

== Step 7: Set up secure in-band authentication
include::_include/nvme/nvme-secure-in-band-authentication.adoc[]

== Step 8: Review the known issues

There are no known issues.

//ONTAPDOC-2561 25-Nov-2024
