---
sidebar: sidebar
permalink: nvme-proxmox-ve-8x.html
keywords: nvme, proxmox, linux, red hat, enterprise
summary: How to Configure NVMe-oF Host for Proxmox VE 8.x with ONTAP storage
---
= Configure Proxmox VE 8.x for NVMe-oF with ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/nvme/nvme-introduction.adoc[]

.About this task 
You can use the following support and features with the NVMe-oF host configuration for Proxmox 8.x. You should also review the known limitations before starting the configuration process.

* Support available:
** Support for NVMe over TCP (NVMe/TCP) in addition to NVMe over Fibre Channel (NVMe/FC). The NetApp plug-in in the native `nvme-cli` package displays ONTAP details for both NVMe/FC and NVMe/TCP namespaces.
** Running both NVMe and SCSI traffic on the same host. For example, you can configure dm-multipath for SCSI mpath devices on SCSI LUNs and use NVMe multipath to configure NVMe-oF namespace devices on the host.
+
For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].
* Features available:
** Native NVMe multipathing is always enabled for Proxmox 8.x. 
* Known limitations: 
** Avoid issuing the `nvme disconnect-all` command on systems booting from SAN over NVMe-TCP or NVMe-FC namespaces because it disconnects both root and data filesystems and might lead to system instability.

== Step 1: Optionally, enable SAN booting

include::_include/nvme/enable-san-booting.adoc[]

== Step 2: Validate software versions

Use the following procedure to validate the minimum supported Proxmox 8.x software versions.

.Steps

. Install Proxmox 8.x on the server. After the installation is complete, verify that you are running the specified Proxmox 8.x kernel: 
+
[source,cli]
----
uname -r
----
+
The following example shows a Proxmox kernel version:
+
----
6.12.0-55.9.1.el10_0.x86_64
----

include::_include/nvme/validate-software-version10-rockylinux-proxmox.adoc[]

== Step 3: Configure NVMe/FC

include::_include/nvme/configure-nvmefc-version10-rockylinux-proxmox.adoc[]

== Step 4: Optionally, enable 1MB I/O 

include::_include/nvme/nvme-enabling-broadcom-1mb-size.adoc[]

== Step 5: Verify NVMe boot services 

With Proxmox 8.x, the `nvmefc-boot-connections.service` and `nvmf-autoconnect.service` boot services included in the NVMe/FC `nvme-cli` package are automatically enabled when the system boots. 

After booting completes, verify that the `nvmefc-boot-connections.service` and `nvmf-autoconnect.service` boot services are enabled.

include::_include/nvme/verify-nvme-services.adoc[]

== Step 6: Configure NVMe/TCP

include::_include/nvme/nvme-configure-nvme-tcp.adoc[]

include::_include/nvme/configure-nvme-tcp-steps-version10-rockylinux-proxmox.adoc[]

== Step 7: Validate NVMe-oF

include::_include/nvme/nvme-validate-nvme-of.adoc[]

include::_include/nvme/validate-nvme-of-latersteps-version10-rockylinux-proxmox.adoc[]

== Step 8: Review the known issues

There are no known issues.

== What's next?

* link:https://pve.proxmox.com/wiki/Storage[Learn about configuring Proxmox storage pools and volumes].

// 2025 JUN 25, ONTAPDOC-3090
// ONTAPDOC-2561 25-Nov-2024
// ONTAPDOC-2987 13-May-2025