---
sidebar: sidebar
permalink: nvme-rockylinux-85.html
keywords: nvme, linux, rocky linux, enterprise
summary: How to Configure NVMe-oF Host for Rocky Linux 8.5 with ONTAP
---
= Configure Rocky Linux 8.5 with NVMe-oF for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Rocky Linux 8.5 hosts support the NVMe/FC and NVMe/TCP protocols with Asymmetric Namespace Access (ANA). ANA is equivalent to asymmetric logical unit access (ALUA) multipathing in iSCSI and FCP environments and is implemented using the in-kernel NVMe multipath feature.

For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].

.About this task 
You can use the following support and features with the NVMe-oF host configuration for Rocky Linux 8.5. You should also review the known limitations before starting the configuration process.

* Support available:
** Support for NVMe over TCP (NVMe/TCP) in addition to NVMe over Fibre Channel (NVMe/FC). The NetApp plug-in in the native `nvme-cli` package displays ONTAP details for both NVMe/FC and NVMe/TCP namespaces.
** Running NVMe and SCSI traffic on the same host. For example, you can configure dm-multipath for SCSI mpath devices for SCSI LUNs and use NVMe multipath to configure NVMe-oF namespace devices on the host.
* Known limitations: 
** In-kernel NVMe multipath is disabled by default for Rocky Linux 8.5 NVMe-oF hosts. Therefore, you need to enable it manually.
** On Rocky Linux 8.5 hosts, NVMe/TCP is a technology preview feature due to open issues. Refer to the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.5_release_notes/index#technology-preview_file-systems-and-storage[Rocky Linux 8.5 Release Notes^] for details.
** SAN booting using the NVMe-oF protocol is currently not supported.

== Step 1: Optionally, enable SAN booting
include::_include/nvme/nvme-enable-san-boot.adoc[]

== Step 2: Validate software versions
Use the following procedure to validate the minimum supported Rocky Linux 8.5 software versions.

.Steps

. Install Rocky Linux 8.5 on the server. After the installation is complete, verify that you are running the specified Rocky Linux 8.5 kernel: 
+
[source,cli]
----
uname -r
----
+
The following example shows a Rocky Linux kernel version:
+
----
5.14.0-570.12.1.el9_6.x86_64
----
[start=2]
include::_include/nvme/linux-validate-software-versions.adoc[] 

== Step 3: Configure NVMe/FC
include::_include/nvme/nvme-configure.adoc[]

== Step 4: Optionally, enable 1MB I/O 
include::_include/nvme/nvme-enable-1mb-io.adoc[]

== Step 5: Configure NVMe/TCP

include::_include/nvme/nvme-configure-nvme-tcp.adoc[]

== Step 6: Validate NVMe-oF
include::_include/nvme/nvme-validate-nvme-of.adoc[]

== Step 7: Review the known issues 

No known issues exist for the NVMe-oF host configuration on Rocky Linux 8.5 with ONTAP release.

// Jira EOPS-730, 2022-08-12
// JIRA-1289 20-Sep-2023
