---
sidebar: sidebar
permalink: nvme_rockylinux_95.html
keywords: nvme, linux, rocky linux, enterprise
summary: How to Configure NVMe-oF Host for Rocky Linux 9.5 with ONTAP
---

= Configure Rocky Linux 9.5 with NVMe-oF for ONTAP storage
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can configure Rocky Linux 9.5 with NVMe protocols to manage ONTAP LUNs.
[.lead]
include::_include/nvme/nvme-introduction.adoc[] 

.About this task 
You can use the following support and features with the NVMe-oF host configuration for Rocky Linux 9.5. You should also review the known limitations before starting the configuration process.

* Support available:
** Support for NVMe over TCP (NVMe/TCP) in addition to NVMe over Fibre Channel (NVMe/FC). The NetApp plug-in in the native `nvme-cli` package displays ONTAP details for both NVMe/FC and NVMe/TCP namespaces.
** Running NVMe and SCSI traffic on the same host. For example, you can configure dm-multipath for SCSI mpath devices for SCSI LUNs and use NVMe multipath to configure NVMe-oF namespace devices on the host.
+
For additional details on supported configurations, see the link:https://mysupport.netapp.com/matrix/[Interoperability Matrix Tool^].
* Features available:
** Beginning with ONTAP 9.12.1, you can use secure in-band authentication for NVMe-oF with Rocky Linux 9.5.
** Rocky Linux 9.5 enables in-kernel NVMe multipath for NVMe namespaces by default, removing the need for explicit settings.
** You can use SAN booting with the NVMe/FC protocol.
* Known limitations: 
** There are no known limitations.

== Step 1: Validate software versions
include::_include/nvme/nvme-validate-software-versions.adoc[] 

== Step 2: Configure NVMe/FC
include::_include/nvme/nvme-configure-nvme-fc.adoc[]

== Step 3: Optionally, enable 1MB I/O 
include::_include/nvme/nvme-enable-1mb-io.adoc[]

== Step 4: Configure NVMe/TCP
include::_include/nvme/nvme-configure-nvme-tcp.adoc[]

[NOTE]
Beginning with Rocky Linux 9.5, the default setting for the NVMe/TCP `ctrl_loss_tmo` timeout is turned off. This means there is no limit on the number of retries (indefinite retry). Consequently, you don't need to manually configure a specific `ctrl_loss_tmo` timeout duration when using the `nvme connect` or `nvme connect-all` commands (option -l ). With this default behavior, the NVMe/TCP controllers don't experience timeouts in the event of a path failure and remain connected indefinitely.

== Step 5: Validate NVMe-oF
include::_include/nvme/nvme-validate-nvme-of.adoc[] 

== Step 6: Optionally, enable SAN booting
include::_include/nvme/nvme-enable-san-boot.adoc[]

== Step 7: Set up secure in-band authentication
include::_include/nvme/nvme-secure-in-band-authentication.adoc[]

== Step 8: Review the known issues

No known issues exist for the NVMe-oF host configuration on Rocky Linux 9.5 with ONTAP release.

//ONTAPDOC-2561 25-Nov-2024
