---
sidebar: sidebar
permalink: nvme_rhel_81.html
keywords: nvme, linux, rhel, red hat, enterprise
summary: Describes how to configure NVMe/FC for RHEL 8.1 with ONTAP
---

= NVMe/FC host configuration for RHEL 8.1 with ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NVMe/FC is supported on ONTAP 9.6 or later for Red Hat Enterprise Linux (RHEL) 8.1. A RHEL 8.1 host can run both NVMe and SCSI traffic through the same FC initiator adapter ports. See the link:https://hwu.netapp.com/Home/Index[Hardware Universe^] for a list of supported FC adapters and controllers.

See the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool^] for the most current list of supported configurations.

==	Known limitations

* Native NVMe/FC auto-connect scripts are not available in the `nvme-cli` package. You can use the host bus adapter (HBA) vendor-provided external auto-connect script.

* NVMe multipath is disabled by default. Therefore, you need to enable it manually. 

* By default, round-robin load balancing is not enabled. You can enable this functionality by writing a `udev` rule. 

* SAN booting using the NVMe-oF protocol is currently not supported.

==	Enable NVMe/FC 

You can use the following procedure to enable NVMe/FC.

.Steps

. Install Red Hat Enterprise Linux 8.1 on the server.

. After the installation is complete, verify that you are running the specified RHEL kernel: 
+
----
# uname -r
4.18.0-147.el8.x86_64
----
+
See the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool^] for the most current list of supported versions.

. Install the `nvme-cli-1.8.1-3.el8` package:
+
----
# rpm -qa|grep nvme-cli
nvme-cli-1.8.1-3.el8.x86_64
----

. Enable in-kernel NVMe multipath:
+
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-147.el8.x86_64
----

. Add the following string as a separate udev rule at `/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules`. This enables round-robin load balancing for NVMe multipath:
+
----
# Enable round-robin for NetApp ONTAP
ACTION==”add”, SUBSYSTEM==”nvme-subsystem”, ATTR{model}==”NetApp ONTAP Controller”, ATTR{iopolicy}=”round-robin
----

. On the RHEL 8.1 host, check the host NQN string at `/etc/nvme/hostnqn` and verify that it matches the host NQN string for the corresponding subsystem on the ONTAP array:
+
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
----
*> vserver nvme subsystem host show -vserver vs_nvme_10
Vserver Subsystem Host NQN
------- --------- -------------------------------------- -----------
rhel_141_nvme_ss_10_0
nqn.2014-08.org.nvmexpress:uuid:75953f3b-77fe-4e03-bf3c-09d5a156fbcd
----
+
[NOTE] 
If the host NQN strings do not match, use the `vserver modify` command to update the host NQN string on your corresponding ONTAP array subsystem to match with the host NQN string from `/etc/nvme/hostnqn` on the host.

. Reboot the host.

==	Configure the Broadcom FC adapter for NVMe/FC

You can use the following procedure to configure a Broadcom FC adapter.

.Steps

. Verify that you are using the supported adapter. See the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix Tool^] for the most current list of supported adapters.

+
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----

. Copy and install the Broadcom lpfc outbox driver and auto-connect scripts:
+
----
# tar -xvzf elx-lpfc-dd-rhel8-12.4.243.20-ds-1.tar.gz
# cd elx-lpfc-dd-rhel8-12.4.2453.20-ds-1
# ./elx_lpfc_install-sh -i -n
----
+
NOTE: The native drivers that are bundled with the OS are called the inbox drivers. If you download the outbox drivers (drivers that are not included with an OS release), an auto-connect script is included in the download and should be installed as part of the driver installation process.

. Reboot the host.

. Verify that you are using the recommended Broadcom lpfc firmware, outbox driver, and auto-connect package versions:
+
----
# cat /sys/class/scsi_host/host*/fwrev
12.4.243.20, sil-4.2.c
12.4.243.20, sil-4.2.c
----
+
----
# cat /sys/module/lpfc/version
0:12.4.243.20
----
+
----
# rpm -qa | grep nvmefc
nvmefc-connect-12.6.61.0-1.noarch
----

. Verify that `lpfc_enable_fc4_type` is set to 3:
+
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----

. Verify that the initiator ports are up and running:
+
----
# cat /sys/class/fc_host/host*/port_name
0x10000090fae0ec61
0x10000090fae0ec62
----
+
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----

. Verify that the NVMe/FC initiator ports are enabled, running, and you can see the target LIFs:
+
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 NVME 2947 SCSI 2977 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec61 WWNN x20000090fae0ec61 DID x012000 ONLINE
NVME RPORT WWPN x202d00a098c80f09 WWNN x202c00a098c80f09 DID x010201 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203100a098c80f09 WWNN x202c00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
…
----

==	Enable 1MB I/O Size for Broadcom NVMe/FC

include::_include/nvme/reuse_nvme_enabling_broadcom_1mb_size.adoc[]

==	Validate NVMe/FC

You can use the following procedure to validate NVMe/FC.

.Steps

include::_include/nvme/reuse_validating_nvme_fc_rhel.adoc[]


// JIRA-1289 20-Sep-2023
