---
sidebar: sidebar
permalink: overview.html
keywords: nvme, windows, enterprise
summary: This content provides distribution-specific guidance on how to configure cloud clients connected to Cloud Volumes ONTAP and Amazon FSx for ONTAP and SAN hosts connected to on-premises ONTAP storage.
---

= SAN host configuration overview
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

This content provides host and version specific best practices to quickly configure SAN hosts connected to ONTAP storage.  

Your SAN hosts and ONTAP storage can reside either on-premises, in the cloud, or both.  

NOTE: In a cloud environment, hosts are typically referred to as clients. All host specific information in this content also applies to cloud clients.

For example you can configure on-premises ONTAP storage to connect to on-premises SAN hosts or to connect to SAN cloud clients.  You could also configure link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[Cloud Volumes ONTAP^] or link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html[Amazon FSx for ONTAP^] to connect to on-premises SAN hosts or to connect to SAN cloud clients.

Proper configuration is important for best performance and successful failover.  

For iSCSI and FC, this content replaces the previous documentation for Linux Unified Host Utilities.
