---
sidebar: sidebar
permalink: overview.html
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp
summary: This content provides distribution-specific guidance on how to configure cloud clients connected to Cloud Volumes ONTAP and Amazon FSx for ONTAP and SAN hosts connected to on-premises ONTAP storage.
---

= SAN host configuration overview
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Host Utilities tools enable you to connect SAN hosts to virtual disks (LUNs) on NetApp storage systems.

Use the host and version-specific configuration documentation to quickly configure SAN hosts connected to ONTAP storage.

Your SAN hosts and ONTAP storage can reside either on-premises, in the cloud, or both.

NOTE: In a cloud environment, hosts are typically referred to as clients. All host-specific information in this content also applies to cloud clients.

For example, you can configure on-premises ONTAP storage, link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[Cloud Volumes ONTAP^], or link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html[Amazon FSx for NetApp ONTAP^] to connect to on-premises SAN hosts or SAN cloud clients. 

Correct configuration is important for best performance and successful failover. Use the recommendations outlined in the documentation to optimize the performance of SAN hosts.

.Related information

* The link:https://docs.netapp.com/us-en/ontap/san-config/index.html[ONTAP SAN Configuration^] for your version of ONTAP
* The link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP SAN Administration Guide^] for your version of ONTAP
* The link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP Release Notes^] for your version of ONTAP
* The link:https://docs.netapp.com/us-en/e-series/index.html[E-Series documentation^] to find SANtricity related documentation.