---
sidebar: sidebar
permalink: san-host-index.html
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp
summary: This content provides distribution-specific guidance on how to configure cloud clients connected to Cloud Volumes ONTAP and Amazon FSx for ONTAP and SAN hosts connected to on-premises ONTAP storage.
---
= Learn about SAN host configurations
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should configure SAN hosts for multipathing and with specific parameters and settings critical for correct operation with ONTAP LUNs. The host configuration varies depending on the host operating system and the protocol. Correct configuration is important for best performance and successful failover. 

* link:hu-fcp-scsi-index.html[Learn about configuring ONTAP SAN hosts with the FCP and iSCSI protocols]
* link:hu-nvme-index.html[Learn about configuring ONTAP SAN hosts with the NVMe-oF protocol]

Your SAN hosts and ONTAP storage can reside either on-premises, in the cloud, or both.

NOTE: In a cloud environment, hosts are typically referred to as clients. All host-specific information in this content also applies to cloud clients.

For example, you can configure on-premises ONTAP storage to connect to on-premises SAN hosts or SAN cloud clients. You can also configure storage services running on a cloud environment such as link:https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html[Cloud Volumes ONTAP^] or link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/index.html[Amazon FSx for NetApp ONTAP^] to connect to on-premises SAN hosts or SAN cloud clients.


.Related information

* link:https://docs.netapp.com/us-en/ontap/san-config/index.html[ONTAP SAN configuration reference^]
* link:https://docs.netapp.com/us-en/ontap/san-management/index.html[ONTAP SAN storage management^] 
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^]
* SANtricity related documentation in the link:https://docs.netapp.com/us-en/e-series/index.html[E-Series systems documentation^] 