=== Configure multipathing

The first time you create the `multipath.conf` file, you might need to enable and start the multipath services. You should also verify that the host is configured with the recommended settings for the ONTAP LUNs.

.Steps

. Verify that the `multipath.conf` file is enabled and running the multipath services:
+
`# systemctl enable multipathd`
+
`# systemctl start multipathd`

. Verify that you have the recommended settings for ONTAP LUNs:
+
`multipath -ll`
+
The following table shows the critical multipathd parameters for ONTAP LUNs and the recommended values.
+
[cols=2]
[options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

CAUTION: Overriding the recommended setting for a parameter can have a negative impact on performance. Contact NetApp support or your OS vendor if you need to override a recommended setting to ensure the impact is fully understood.

=== Use multipathing to optimize performance

You can use the `multipath.conf` file with the recommended settings for ONTAP LUNs to optimize the performance of your host configuration: 

* <<exclude-devices,Exclude devices from multipath by adding them to a blacklist>>