[role="tabbed-block"]
=====
.Oracle Linux Standalone
--
To ensure that multipathing is configured correctly for your host, verify that `/etc/multipath.conf` is defined and that the NetApp-recommended settings are configured for your ONTAP LUNs.

.Steps

. Verify that the `/etc/multipath.conf` file exists. If the file doesn't exist, create an empty, zero-byte file:
+
[source,cli]
----
touch /etc/multipath.conf
----

. The first time the `multipath.conf` file is created, you might need to enable and start the multipath services to load the recommended settings:
+
[source,cli]
----
systemctl enable multipathd
----
+
[source,cli]
----
systemctl start multipathd
----

. Each time you boot the host, the empty `/etc/multipath.conf` zero-byte file automatically loads the NetApp recommended host multipath parameters as the default settings. You shouldn't need to make changes to the `/etc/multipath.conf` file for your host because the operating system is compiled with the multipath parameters that recognize and manage ONTAP LUNs correctly.
+
The following table shows the native Linux OS compiled multipath parameter settings for ONTAP LUNs.
+
.Show parameter settings
[%collapsible]
====
[[multipath-parameter-settings]]
[cols=2]
[options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===
====

. Verify the parameter settings and path status for your ONTAP LUNs:
+
[source,cli]
----
multipath -ll
----
+
The default multipath parameters support ASA, AFF, and FAS configurations. In these configurations, a single ONTAP LUN shouldn't require more than four paths. Having more than four paths can cause problems during a storage failure.
+
The following example outputs show the correct parameter settings and path status for ONTAP LUNs in an ASA, AFF, or FAS configuration.

*ASA configuration*

An ASA configuration optimizes all paths to a given LUN, keeping them active. This improves performance by serving I/O operations through all paths at the same time.

.Show example
[%collapsible]
====
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
====

*AFF or FAS configuration*

An AFF or FAS configuration should have two groups of paths with higher and lower priorities. Higher priority Active/Optimized paths are served by the controller where the aggregate is located. Lower priority paths are active but non-optimized because they are served by a different controller. Non-optimized paths are only used when optimized paths aren’t available.

The following example displays the output for an ONTAP LUN with two Active/Optimized paths and two Active/Non-Optimized paths:

.Show example
[%collapsible]
====
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====
--

.OLVM - ONTAP HA
--
If you are using Oracle Linux Virtualization Manager (OLVM), Linux hypervisor default multipath parameters are controlled by the VDSM daemon. It is not recommended to directly modify default OLVM VDSM-generated `/etc/multipath.conf` values. Override the default multipath values by using a multipath drop-in file.

NetApp recommends the following drop-in file for ONTAP HA configurations to override the default `dev_loss_tmo` and `no_path_retry` values. The remaining multipath parameters align with the parameter settings table in the Oracle Linux Standalone tab.

.Steps

. Create the drop-in file and add the following content:
+
[source,cli]
----
cat <<'EOF' > /etc/multipath/conf.d/ontap-ha-mpath-netapp.conf
# Finite multipath retry window aligned with sanlock io_timeout
# default sanlock:io_timeout=10s, polling_interval=5s => no_path_retry = (8*10)/5 = 16

devices {
  device {
    vendor "NETAPP"
    product "LUN"
    no_path_retry 16
    dev_loss_tmo "infinity"
  }
}
EOF
----

. Reload the multipath daemon:
+
[source,cli]
----
systemctl reload multipathd
----

. Verify the updated multipath configuration:
+
[source,cli]
----
multipath -ll
----
--

.OLVM - ONTAP SnapMirror active sync
--
If you are using Oracle Linux Virtualization Manager (OLVM), Linux hypervisor default multipath parameters are controlled by the VDSM daemon. It is not recommended to directly modify default OLVM VDSM-generated `/etc/multipath.conf` values. Override the default multipath values by using a multipath drop-in file.

.Steps

If you are using an ONTAP SnapMirror active sync configuration with Oracle Linux Virtualization Manager (OLVM), additional configuration is required to ensure correct host and virtual machine behavior during SnapMirror active sync storage failover events.
+
With Oracle Linux Virtualization Manager (OLVM), default sanlock and multipath timeout values can result in unintended high-availability virtual machine (VM) failovers during unplanned storage site failover events. This occurs because the default lease renewal window can expire before multipath recovery completes.
+
Perform the configuration steps described in the NetApp Knowledge Base article https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Oracle_Linux_Virtualization_Manager_-_Sanlock_Settings_for_ONTAP_SnapMirror_Active_Sync[Oracle Linux Virtualization Manager - Sanlock Settings for ONTAP SnapMirror Active Sync] to adjust the sanlock and multipath timeout values to ensure that the lease renewal window is sufficient for multipath recovery to complete during a storage failover event.
--
=====