The first time you create the `multipath.conf` file, you might need to enable and start the multipath services: 

[source,cli]
----
systemctl enable multipathd
----

[source,cli]
----
systemctl start multipathd
----

You don't need to make changes to the `/etc/multipath.conf` zero-byte file for SUSE Linux Enterprise Server 15 SP6 because the operating system is compiled with the multipath parameters that recognize and manage ONTAP LUNs correctly. 

An empty `/etc/multipath.conf` file automatically loads the NetApp recommended host multipath parameters as the default settings when the operating system boots. The following table shows the critical multipath parameters for ONTAP LUNs. These parameters are compiled with built-in Device Mapper Multipathing libraries. 

[[multipath-parameter-settings]]
[cols=2]
[options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "2 pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| no_path_retry | queue
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "service-time 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

The default multipath parameters loaded from an empty, zero-byte `/etc/multipath.conf` file support both NetApp ASA (all-flash SAN array) and non-ASA array configurations.

You can use the following multipath command to verify the settings for your ONTAP LUNs:

[source,cli]
----
multipath -ll
----
