The NetApp Linux Host Utilities software package is available on the https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads[NetApp Support Site^] in a 32-bit or 64-bit .rpm file.

NetApp strongly recommends installing the Linux Host Utilities, but it is not mandatory. The utilities do not change any settings on your Linux host. The utilities improve management and assist NetApp customer support in gathering information about your configuration.

.Steps

. If you have a version of Linux Host Utilities currently installed, use the following command to remove it:
+
`rpm -e netapp_linux_unified_host_utilities-7-1`
+
For older versions of Linux Host Utilities, go to the directory where the host utility software is installed and enter the `uninstall` command.

.	Download either the 32-bit or 64-bit Linux Host Utilities software package from the link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads[NetApp Support Site^] to your host.

.	Go to the directory to which you downloaded the software package and use the following command to install it:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm`
+
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----

. Verify the installation:
+
`sanlun version`
+
----
sanlun version 7.1.386.1644
----
