. NetApp also recommends using the following recommended settings if your storage configuration includes MetroCluster, Oracle Solaris virtualization, or SnapMirror active sync.
+
[role="tabbed-block"]
=====
.MetroCluster
--
By default, the Solaris OS fails to execute the I/O operations after *20s* if all paths to a LUN are lost. This is controlled by the `fcp_offline_delay` parameter. The default value for `fcp_offline_delay` is the appropriate for standard ONTAP clusters. However, in MetroCluster configurations, you must increase the value of `fcp_offline_delay` to *120s* to ensure that I/O doesn't prematurely time out during operations, including unplanned failovers. 

For additional information and recommended changes to default settings for MetroCluster, see the Knowledge Base article https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration[Solaris host support considerations in a MetroCluster configuration^].
--

.Oracle Solaris virtualization
--
* Solaris virtualization options include Solaris Logical Domains (also called LDOMs or Oracle VM Server for SPARC), Solaris Dynamic Domains, Solaris Zones, and Solaris Containers. These technologies are also referred to as "Oracle Virtual Machines".

* You can use multiple options together, for example, a Solaris Container within a particular Solaris Logical Domain.

* NetApp supports the use of Solaris virtualization technologies where the overall configuration is supported by Oracle and any partition with direct access to LUNs is listed on the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^] in a supported configuration. This includes root containers, LDOM I/O domains, and LDOM using NPIV to access LUNs.

* Partitions or virtual machines that use only virtualized storage resources, such as a `vdsk`, don't need specific qualifications because they don't have direct access to ONTAP LUNs. You only need to verify that the partition or virtual machine that has direct access to the underlying LUN, such as an LDOM I/O domain, is listed on the link:https://imt.netapp.com/matrix/#welcome[Interoperability Matrix Tool^].

.Steps
When LUNs are used as virtual disk devices within an LDOM, the source of the LUN is masked by virtualization and the LDOM doesn't correctly detect the block sizes. To prevent this issue:

. Patch the LDOM OS for _Oracle Bug 15824910_ 
. Create a `vdc.conf` file that sets the block size of the virtual disk to `4096`. See Oracle DOC: 2157669.1 for more information. 
. Verify the patch installation to ensure that the recommended settings have been configured correctly:
.. Create a zpool:
+
`zpool create zpool_name disk_list`
.. Run `zdb -C` against the zpool and verify that the value of *ashift* is `12`.
+
If the value of *ashift* isn't `12`, re run `zdb -C11`, and verify that the correct patch was installed and recheck the contents of `vdc.conf`.
+
Don't proceed until *ashift* shows a value of `12`.

NOTE: Patches are available for Oracle bug 15824910 on several Solaris versions. Contact Oracle if you need assistance in determining the best kernel patch.
--

.SnapMirror active sync
--
Beginning with ONTAP 9.9.1, SnapMirror active sync setting configurations are supported in the Solaris host. To verify that the Solaris client applications are non-disruptive when an unplanned site failover switchover occurs in a SnapMirror active sync environment, you must configure the `scsi-vhci-failover-override` setting on the Solaris host. This setting overrides the failover module `f_tpgs` to prevent the execution of the code path that detects the contradiction.

.Steps

. Create the configuration file `/etc/driver/drv/scsi_vhci.conf` with an entry similar to the following example for the NetApp storage type connected to the host:
+
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. Verify that the override parameter has been successfully applied:
+
`devprop`
+
`mdb`
+
.Show example
[%collapsible]
====
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k
----

----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----
====

NOTE: After `scsi-vhci-failover-override` has been applied, `conf` is added to `svl_fops_name`. For additional information and recommended changes to default settings, refer to the NetApp Knowledge Base article https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration[Solaris Host support recommended settings in SnapMirror active sync configuration^].
--
=====