Multipathing enables you to configure multiple network paths between the host and storage systems. If one path fails, traffic continues on the remaining paths. When you install Solaris Host Utilities 11.4, Oracle Solaris I/O Multipathing (MPxIO) is enabled by default. 

.Steps 
. In the `/kernel/drv/fp.conf` file, verify that `mpxio-disable=no`.
. The NetApp recommended host multipath parameters are loaded as the default settings.
+
The following table shows the native Solaris OS compiled multipath parameter settings for ONTAP LUNs.
+
.Show parameter settings
[%collapsible]
====
[[multipath-parameter-settings]]
[cols=2]
[options="header"]
|===
| Parameter
| Setting
| throttle_max
| 8
| not_ready_retries
| 300
| busy_retries
| 30
| reset_retries
| 30
| throttle_min
| 2
| timeout_retries
| 10
| physical_block_size
| 4096
| disksort
| false
| cache-nonvolatile
| true
|===
====

. Verify the parameter settings and path status for your ONTAP LUNs:
+
`mpathadm show lu <LUN>`
+
The default multipath parameters support ASA, AFF, and FAS configurations.
+
The following example outputs show the correct parameter settings and path status for ONTAP LUNs in an ASA, AFF, or FAS configuration. 
+
----
root@sparc-s7-55-148:~# sanlun lun show -pv
 
                    ONTAP Path: Solaris_148_siteA:/vol/Triage/lun
                           LUN: 0
                      LUN Size: 20g
                   Host Device: /dev/rdsk/c0t600A098038314B32685D573064776172d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----

.AFF or FAS configuration
--
An AFF or FAS configuration should have two groups of paths with higher and lower priorities. Higher priority Active/Optimized paths are served by the controller where the aggregate is located. Lower priority paths are active but non-optimized because they are served by a different controller. Non-optimized paths are only used when optimized paths aren’t available.

The following example displays the output for an ONTAP LUN with two Active/Optimized paths and two Active/Non-Optimized paths:

----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====
